// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type {
  AddGroupMemberData,
  AddGroupMemberErrors,
  AddGroupMemberResponses,
  CreateApiKeyData,
  CreateApiKeyErrors,
  CreateApiKeyResponses,
  CreateEventData,
  CreateEventErrors,
  CreateEventFormData,
  CreateEventFormErrors,
  CreateEventFormResponses,
  CreateEventPaymentData,
  CreateEventPaymentErrors,
  CreateEventPaymentResponses,
  CreateEventRegistrationData,
  CreateEventRegistrationErrors,
  CreateEventRegistrationResponses,
  CreateEventResponses,
  CreateFineData,
  CreateFineErrors,
  CreateFineResponses,
  CreateFormData,
  CreateFormErrors,
  CreateFormResponses,
  CreateFormSubmissionData,
  CreateFormSubmissionErrors,
  CreateFormSubmissionResponses,
  CreateGroupData,
  CreateGroupErrors,
  CreateGroupFormData,
  CreateGroupFormErrors,
  CreateGroupFormResponses,
  CreateGroupResponses,
  CreateJobData,
  CreateJobErrors,
  CreateJobResponses,
  CreateNewsData,
  CreateNewsErrors,
  CreateNewsReactionData,
  CreateNewsReactionErrors,
  CreateNewsReactionResponses,
  CreateNewsResponses,
  DeleteApiKeyData,
  DeleteApiKeyErrors,
  DeleteApiKeyResponses,
  DeleteEventData,
  DeleteEventErrors,
  DeleteEventRegistrationData,
  DeleteEventRegistrationResponses,
  DeleteEventResponses,
  DeleteFineData,
  DeleteFineErrors,
  DeleteFineResponses,
  DeleteFormData,
  DeleteFormErrors,
  DeleteFormResponses,
  DeleteFormSubmissionData,
  DeleteFormSubmissionErrors,
  DeleteFormSubmissionResponses,
  DeleteGroupData,
  DeleteGroupErrors,
  DeleteGroupResponses,
  DeleteJobData,
  DeleteJobErrors,
  DeleteJobResponses,
  DeleteNewsData,
  DeleteNewsErrors,
  DeleteNewsReactionData,
  DeleteNewsReactionErrors,
  DeleteNewsReactionResponses,
  DeleteNewsResponses,
  DeleteNotificationData,
  DeleteNotificationErrors,
  DeleteNotificationResponses,
  DownloadFormSubmissionsData,
  DownloadFormSubmissionsErrors,
  DownloadFormSubmissionsResponses,
  GetApiKeyData,
  GetApiKeyErrors,
  GetApiKeyResponses,
  GetEventFormData,
  GetEventFormErrors,
  GetEventFormResponses,
  GetFavoriteEventsData,
  GetFavoriteEventsResponses,
  GetFineData,
  GetFineErrors,
  GetFineResponses,
  GetFormData,
  GetFormErrors,
  GetFormResponses,
  GetFormStatisticsData,
  GetFormStatisticsErrors,
  GetFormStatisticsResponses,
  GetFormSubmissionData,
  GetFormSubmissionErrors,
  GetFormSubmissionResponses,
  GetGroupData,
  GetGroupErrors,
  GetGroupResponses,
  GetJobData,
  GetJobErrors,
  GetJobResponses,
  GetNewsData,
  GetNewsErrors,
  GetNewsResponses,
  GetUserSettingsData,
  GetUserSettingsErrors,
  GetUserSettingsResponses,
  HandlePaymentWebhookData,
  HandlePaymentWebhookErrors,
  HandlePaymentWebhookResponses,
  ListAllergiesData,
  ListAllergiesResponses,
  ListApiKeysData,
  ListApiKeysErrors,
  ListApiKeysResponses,
  ListEventFormsData,
  ListEventFormsErrors,
  ListEventFormsResponses,
  ListEventRegistrationsData,
  ListEventRegistrationsResponses,
  ListEventsData,
  ListEventsResponses,
  ListFinesData,
  ListFinesErrors,
  ListFinesResponses,
  ListFormsData,
  ListFormsResponses,
  ListFormSubmissionsData,
  ListFormSubmissionsErrors,
  ListFormSubmissionsResponses,
  ListGroupFormsData,
  ListGroupFormsErrors,
  ListGroupFormsResponses,
  ListGroupMembersData,
  ListGroupMembersErrors,
  ListGroupMembersResponses,
  ListGroupsData,
  ListGroupsResponses,
  ListJobsData,
  ListJobsResponses,
  ListNewsData,
  ListNewsResponses,
  ListNotificationsData,
  ListNotificationsErrors,
  ListNotificationsResponses,
  MarkNotificationReadData,
  MarkNotificationReadErrors,
  MarkNotificationReadResponses,
  OnboardUserData,
  OnboardUserErrors,
  OnboardUserResponses,
  RegenerateApiKeyData,
  RegenerateApiKeyErrors,
  RegenerateApiKeyResponses,
  RemoveGroupMemberData,
  RemoveGroupMemberErrors,
  RemoveGroupMemberResponses,
  SendCustomEmailData,
  SendCustomEmailErrors,
  SendCustomEmailResponses,
  UpdateApiKeyData,
  UpdateApiKeyErrors,
  UpdateApiKeyResponses,
  UpdateEventData,
  UpdateEventErrors,
  UpdateEventFavoriteData,
  UpdateEventFavoriteErrors,
  UpdateEventFavoriteResponses,
  UpdateEventResponses,
  UpdateFineData,
  UpdateFineErrors,
  UpdateFineResponses,
  UpdateFormData,
  UpdateFormErrors,
  UpdateFormResponses,
  UpdateGroupData,
  UpdateGroupErrors,
  UpdateGroupMemberRoleData,
  UpdateGroupMemberRoleErrors,
  UpdateGroupMemberRoleResponses,
  UpdateGroupResponses,
  UpdateJobData,
  UpdateJobErrors,
  UpdateJobResponses,
  UpdateNewsData,
  UpdateNewsErrors,
  UpdateNewsResponses,
  UpdateUserSettingsData,
  UpdateUserSettingsErrors,
  UpdateUserSettingsResponses,
  ValidateApiKeyData,
  ValidateApiKeyResponses,
} from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * List API keys
 *
 * Get a list of all API keys. Does not include the full key values. Requires 'api-keys:view' permission.
 */
export const listApiKeys = <ThrowOnError extends boolean = false>(options?: Options<ListApiKeysData, ThrowOnError>) => {
  return (options?.client ?? client).get<ListApiKeysResponses, ListApiKeysErrors, ThrowOnError>({
    url: '/api/api-keys',
    ...options,
  });
};

/**
 * Create API key
 *
 * Create a new API key. The full key is returned only once and cannot be retrieved again. Requires 'api-keys:create' permission.
 */
export const createApiKey = <ThrowOnError extends boolean = false>(options?: Options<CreateApiKeyData, ThrowOnError>) => {
  return (options?.client ?? client).post<CreateApiKeyResponses, CreateApiKeyErrors, ThrowOnError>({
    url: '/api/api-keys',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * Delete API key
 *
 * Delete an API key. This action is irreversible. Requires 'api-keys:delete' permission.
 */
export const deleteApiKey = <ThrowOnError extends boolean = false>(options: Options<DeleteApiKeyData, ThrowOnError>) => {
  return (options.client ?? client).delete<DeleteApiKeyResponses, DeleteApiKeyErrors, ThrowOnError>({
    url: '/api/api-keys/{id}',
    ...options,
  });
};

/**
 * Get API key
 *
 * Get a single API key by ID. Does not include the full key value. Requires 'api-keys:view' permission.
 */
export const getApiKey = <ThrowOnError extends boolean = false>(options: Options<GetApiKeyData, ThrowOnError>) => {
  return (options.client ?? client).get<GetApiKeyResponses, GetApiKeyErrors, ThrowOnError>({
    url: '/api/api-keys/{id}',
    ...options,
  });
};

/**
 * Update API key
 *
 * Update an API key's metadata (name, description, permissions, metadata). Cannot update the key itself - use regenerate for that. Requires 'api-keys:update' permission.
 */
export const updateApiKey = <ThrowOnError extends boolean = false>(options: Options<UpdateApiKeyData, ThrowOnError>) => {
  return (options.client ?? client).patch<UpdateApiKeyResponses, UpdateApiKeyErrors, ThrowOnError>({
    url: '/api/api-keys/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * Regenerate API key
 *
 * Generate a new key value for an existing API key. The old key will be invalidated. The new full key is returned only once and cannot be retrieved again. Requires 'api-keys:update' permission.
 */
export const regenerateApiKey = <ThrowOnError extends boolean = false>(options: Options<RegenerateApiKeyData, ThrowOnError>) => {
  return (options.client ?? client).post<RegenerateApiKeyResponses, RegenerateApiKeyErrors, ThrowOnError>({
    url: '/api/api-keys/{id}/regenerate',
    ...options,
  });
};

/**
 * Validate API key
 *
 * Check if an API key is valid and return its details. This is a public endpoint that does not require authentication. Updates the lastUsedAt timestamp if the key is valid.
 */
export const validateApiKey = <ThrowOnError extends boolean = false>(options?: Options<ValidateApiKeyData, ThrowOnError>) => {
  return (options?.client ?? client).post<ValidateApiKeyResponses, unknown, ThrowOnError>({
    url: '/api/api-keys/validate',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * Send custom email
 *
 * Send a custom email with structured content blocks. Requires API key authentication via Bearer token.
 */
export const sendCustomEmail = <ThrowOnError extends boolean = false>(options?: Options<SendCustomEmailData, ThrowOnError>) => {
  return (options?.client ?? client).post<SendCustomEmailResponses, SendCustomEmailErrors, ThrowOnError>({
    url: '/api/email/send',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * List events
 */
export const listEvents = <ThrowOnError extends boolean = false>(options?: Options<ListEventsData, ThrowOnError>) => {
  return (options?.client ?? client).get<ListEventsResponses, unknown, ThrowOnError>({
    url: '/api/event',
    ...options,
  });
};

/**
 * Create event
 *
 * Create a new event. Requires 'events:create' permission.
 */
export const createEvent = <ThrowOnError extends boolean = false>(options?: Options<CreateEventData, ThrowOnError>) => {
  return (options?.client ?? client).post<CreateEventResponses, CreateEventErrors, ThrowOnError>({
    url: '/api/event',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * Update event
 *
 * Update an event by its ID. Event creators can update their own events. Users with 'events:update' or 'events:manage' permission can update any event.
 */
export const updateEvent = <ThrowOnError extends boolean = false>(options: Options<UpdateEventData, ThrowOnError>) => {
  return (options.client ?? client).put<UpdateEventResponses, UpdateEventErrors, ThrowOnError>({
    url: '/api/event/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * Delete an event
 *
 * Delete an event by its ID. Event creators can delete their own events. Users with 'events:delete' permission can delete any event. This action is irreversible and will remove all associated data, including registrations and feedback.
 */
export const deleteEvent = <ThrowOnError extends boolean = false>(options: Options<DeleteEventData, ThrowOnError>) => {
  return (options.client ?? client).delete<DeleteEventResponses, DeleteEventErrors, ThrowOnError>({
    url: '/api/event/{eventId}',
    ...options,
  });
};

/**
 * Update event favorite
 */
export const updateEventFavorite = <ThrowOnError extends boolean = false>(options: Options<UpdateEventFavoriteData, ThrowOnError>) => {
  return (options.client ?? client).put<UpdateEventFavoriteResponses, UpdateEventFavoriteErrors, ThrowOnError>({
    url: '/api/event/favorite/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * Get all my favorite events
 *
 * Retrieve a list of all events you have marked as favorite.
 */
export const getFavoriteEvents = <ThrowOnError extends boolean = false>(options?: Options<GetFavoriteEventsData, ThrowOnError>) => {
  return (options?.client ?? client).get<GetFavoriteEventsResponses, unknown, ThrowOnError>({
    url: '/api/event/favorite',
    ...options,
  });
};

/**
 * Unregister from event
 */
export const deleteEventRegistration = <ThrowOnError extends boolean = false>(options: Options<DeleteEventRegistrationData, ThrowOnError>) => {
  return (options.client ?? client).delete<DeleteEventRegistrationResponses, unknown, ThrowOnError>({
    url: '/api/event/{eventId}/registration',
    ...options,
  });
};

/**
 * Get event registrations
 */
export const listEventRegistrations = <ThrowOnError extends boolean = false>(options: Options<ListEventRegistrationsData, ThrowOnError>) => {
  return (options.client ?? client).get<ListEventRegistrationsResponses, unknown, ThrowOnError>({
    url: '/api/event/{eventId}/registration',
    ...options,
  });
};

/**
 * Register to an event
 */
export const createEventRegistration = <ThrowOnError extends boolean = false>(options: Options<CreateEventRegistrationData, ThrowOnError>) => {
  return (options.client ?? client).post<CreateEventRegistrationResponses, CreateEventRegistrationErrors, ThrowOnError>({
    url: '/api/event/{eventId}/registration',
    ...options,
  });
};

/**
 * Create payment for event
 *
 * Initiates a Vipps payment for an event registration. User must have a registered status for the event.
 */
export const createEventPayment = <ThrowOnError extends boolean = false>(options: Options<CreateEventPaymentData, ThrowOnError>) => {
  return (options.client ?? client).post<CreateEventPaymentResponses, CreateEventPaymentErrors, ThrowOnError>({
    url: '/api/event/{eventId}/payment',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * Vipps payment webhook
 *
 * Webhook endpoint for Vipps to notify about payment status changes. Updates payment record based on Vipps payment state.
 */
export const handlePaymentWebhook = <ThrowOnError extends boolean = false>(options?: Options<HandlePaymentWebhookData, ThrowOnError>) => {
  return (options?.client ?? client).post<HandlePaymentWebhookResponses, HandlePaymentWebhookErrors, ThrowOnError>({
    url: '/api/event/payment/webhook',
    ...options,
  });
};

/**
 * List event forms
 *
 * Get all forms (survey and evaluation) for an event
 */
export const listEventForms = <ThrowOnError extends boolean = false>(options: Options<ListEventFormsData, ThrowOnError>) => {
  return (options.client ?? client).get<ListEventFormsResponses, ListEventFormsErrors, ThrowOnError>({
    url: '/api/event/{eventId}/forms',
    ...options,
  });
};

/**
 * Create event form
 *
 * Create a survey or evaluation form for an event. Requires event write permission.
 */
export const createEventForm = <ThrowOnError extends boolean = false>(options: Options<CreateEventFormData, ThrowOnError>) => {
  return (options.client ?? client).post<CreateEventFormResponses, CreateEventFormErrors, ThrowOnError>({
    url: '/api/event/{eventId}/forms',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * Get event form
 *
 * Get a specific form (survey or evaluation) for an event with all fields and options
 */
export const getEventForm = <ThrowOnError extends boolean = false>(options: Options<GetEventFormData, ThrowOnError>) => {
  return (options.client ?? client).get<GetEventFormResponses, GetEventFormErrors, ThrowOnError>({
    url: '/api/event/{eventId}/forms/{type}',
    ...options,
  });
};

/**
 * List forms
 *
 * List all form templates by default. Use ?all=true to include all forms. Returns template forms by default.
 */
export const listForms = <ThrowOnError extends boolean = false>(options?: Options<ListFormsData, ThrowOnError>) => {
  return (options?.client ?? client).get<ListFormsResponses, unknown, ThrowOnError>({
    url: '/api/forms',
    ...options,
  });
};

/**
 * Create form
 *
 * Create a new base form template. Requires 'forms:create' permission.
 */
export const createForm = <ThrowOnError extends boolean = false>(options?: Options<CreateFormData, ThrowOnError>) => {
  return (options?.client ?? client).post<CreateFormResponses, CreateFormErrors, ThrowOnError>({
    url: '/api/forms',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * Delete form
 *
 * Delete a form and all associated data. Requires permission to manage the form.
 */
export const deleteForm = <ThrowOnError extends boolean = false>(options: Options<DeleteFormData, ThrowOnError>) => {
  return (options.client ?? client).delete<DeleteFormResponses, DeleteFormErrors, ThrowOnError>({
    url: '/api/forms/{id}',
    ...options,
  });
};

/**
 * Get form
 *
 * Get a form by ID with all fields and options
 */
export const getForm = <ThrowOnError extends boolean = false>(options: Options<GetFormData, ThrowOnError>) => {
  return (options.client ?? client).get<GetFormResponses, GetFormErrors, ThrowOnError>({
    url: '/api/forms/{id}',
    ...options,
  });
};

/**
 * Update form
 *
 * Update a form. Requires permission to manage the form.
 */
export const updateForm = <ThrowOnError extends boolean = false>(options: Options<UpdateFormData, ThrowOnError>) => {
  return (options.client ?? client).patch<UpdateFormResponses, UpdateFormErrors, ThrowOnError>({
    url: '/api/forms/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * Get form statistics
 *
 * Get aggregated statistics for a form. Requires permission to manage the form.
 */
export const getFormStatistics = <ThrowOnError extends boolean = false>(options: Options<GetFormStatisticsData, ThrowOnError>) => {
  return (options.client ?? client).get<GetFormStatisticsResponses, GetFormStatisticsErrors, ThrowOnError>({
    url: '/api/forms/{id}/statistics',
    ...options,
  });
};

/**
 * List submissions
 *
 * List all submissions for a form. Requires permission to manage the form.
 */
export const listFormSubmissions = <ThrowOnError extends boolean = false>(options: Options<ListFormSubmissionsData, ThrowOnError>) => {
  return (options.client ?? client).get<ListFormSubmissionsResponses, ListFormSubmissionsErrors, ThrowOnError>({
    url: '/api/forms/{formId}/submissions',
    ...options,
  });
};

/**
 * Create submission
 *
 * Submit answers to a form
 */
export const createFormSubmission = <ThrowOnError extends boolean = false>(options: Options<CreateFormSubmissionData, ThrowOnError>) => {
  return (options.client ?? client).post<CreateFormSubmissionResponses, CreateFormSubmissionErrors, ThrowOnError>({
    url: '/api/forms/{formId}/submissions',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * Get submission
 *
 * Get a specific submission. Can view own submission or requires permission to manage the form.
 */
export const getFormSubmission = <ThrowOnError extends boolean = false>(options: Options<GetFormSubmissionData, ThrowOnError>) => {
  return (options.client ?? client).get<GetFormSubmissionResponses, GetFormSubmissionErrors, ThrowOnError>({
    url: '/api/forms/{formId}/submissions/{id}',
    ...options,
  });
};

/**
 * Download submissions as CSV
 *
 * Download all submissions for a form as CSV. Requires permission to manage the form.
 */
export const downloadFormSubmissions = <ThrowOnError extends boolean = false>(options: Options<DownloadFormSubmissionsData, ThrowOnError>) => {
  return (options.client ?? client).get<DownloadFormSubmissionsResponses, DownloadFormSubmissionsErrors, ThrowOnError>({
    url: '/api/forms/{formId}/submissions/download',
    ...options,
  });
};

/**
 * Delete submission with reason
 *
 * Delete a submission and notify the user with a reason. Admin only.
 */
export const deleteFormSubmission = <ThrowOnError extends boolean = false>(options: Options<DeleteFormSubmissionData, ThrowOnError>) => {
  return (options.client ?? client).delete<DeleteFormSubmissionResponses, DeleteFormSubmissionErrors, ThrowOnError>({
    url: '/api/forms/{formId}/submissions/{id}/destroy_with_reason',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * List notifications for authenticated user
 *
 * Returns paginated list of notifications for the authenticated user, ordered by most recent first
 */
export const listNotifications = <ThrowOnError extends boolean = false>(options?: Options<ListNotificationsData, ThrowOnError>) => {
  return (options?.client ?? client).get<ListNotificationsResponses, ListNotificationsErrors, ThrowOnError>({
    url: '/api/notification',
    ...options,
  });
};

/**
 * Delete notification
 *
 * Delete a notification by ID. User must be authenticated and own the notification.
 */
export const deleteNotification = <ThrowOnError extends boolean = false>(options: Options<DeleteNotificationData, ThrowOnError>) => {
  return (options.client ?? client).delete<DeleteNotificationResponses, DeleteNotificationErrors, ThrowOnError>({
    url: '/api/notification/{id}',
    ...options,
  });
};

/**
 * Mark notification as read or unread
 *
 * Update the read status of a notification. User must be authenticated and own the notification.
 */
export const markNotificationRead = <ThrowOnError extends boolean = false>(options: Options<MarkNotificationReadData, ThrowOnError>) => {
  return (options.client ?? client).patch<MarkNotificationReadResponses, MarkNotificationReadErrors, ThrowOnError>({
    url: '/api/notification/{id}/read',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * List groups
 *
 * Retrieve a list of all groups. Supports optional filtering by type and search query.
 */
export const listGroups = <ThrowOnError extends boolean = false>(options?: Options<ListGroupsData, ThrowOnError>) => {
  return (options?.client ?? client).get<ListGroupsResponses, unknown, ThrowOnError>({
    url: '/api/groups',
    ...options,
  });
};

/**
 * Create group
 *
 * Create a new group. Requires 'groups:create' permission.
 */
export const createGroup = <ThrowOnError extends boolean = false>(options?: Options<CreateGroupData, ThrowOnError>) => {
  return (options?.client ?? client).post<CreateGroupResponses, CreateGroupErrors, ThrowOnError>({
    url: '/api/groups',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * Delete a group
 *
 * Delete a group by its slug. Requires being a group leader OR having 'groups:delete' permission (globally or scoped to this group). This action is irreversible and will remove all associated data, including memberships and fines.
 */
export const deleteGroup = <ThrowOnError extends boolean = false>(options: Options<DeleteGroupData, ThrowOnError>) => {
  return (options.client ?? client).delete<DeleteGroupResponses, DeleteGroupErrors, ThrowOnError>({
    url: '/api/groups/{slug}',
    ...options,
  });
};

/**
 * Get group by slug
 *
 * Retrieve detailed information about a specific group by its slug identifier.
 */
export const getGroup = <ThrowOnError extends boolean = false>(options: Options<GetGroupData, ThrowOnError>) => {
  return (options.client ?? client).get<GetGroupResponses, GetGroupErrors, ThrowOnError>({
    url: '/api/groups/{slug}',
    ...options,
  });
};

/**
 * Partially update group
 *
 * Partially update an existing group by its slug. Only provided fields will be updated. Requires being a group leader OR having 'groups:update' permission (globally or scoped to this group).
 */
export const updateGroup = <ThrowOnError extends boolean = false>(options: Options<UpdateGroupData, ThrowOnError>) => {
  return (options.client ?? client).patch<UpdateGroupResponses, UpdateGroupErrors, ThrowOnError>({
    url: '/api/groups/{slug}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * List fines for a group
 *
 * Retrieve a list of fines for a group. Users can view their own fines, fines admins can view all fines for their group. Supports filtering by status and user.
 */
export const listFines = <ThrowOnError extends boolean = false>(options: Options<ListFinesData, ThrowOnError>) => {
  return (options.client ?? client).get<ListFinesResponses, ListFinesErrors, ThrowOnError>({
    url: '/api/groups/{groupSlug}/fines',
    ...options,
  });
};

/**
 * Create fine
 *
 * Create a new fine for a group member. Requires being a group leader OR having 'fines:create' permission (globally or scoped to this group).
 */
export const createFine = <ThrowOnError extends boolean = false>(options: Options<CreateFineData, ThrowOnError>) => {
  return (options.client ?? client).post<CreateFineResponses, CreateFineErrors, ThrowOnError>({
    url: '/api/groups/{groupSlug}/fines',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * Delete a fine
 *
 * Delete a fine by its ID. Requires being the fines admin OR having 'fines:delete' permission (globally or scoped to this group). This action is irreversible.
 */
export const deleteFine = <ThrowOnError extends boolean = false>(options: Options<DeleteFineData, ThrowOnError>) => {
  return (options.client ?? client).delete<DeleteFineResponses, DeleteFineErrors, ThrowOnError>({
    url: '/api/groups/{groupSlug}/fines/{fineId}',
    ...options,
  });
};

/**
 * Get fine by ID
 *
 * Retrieve detailed information about a specific fine. Users can view their own fines, fines admins can view all fines for their group.
 */
export const getFine = <ThrowOnError extends boolean = false>(options: Options<GetFineData, ThrowOnError>) => {
  return (options.client ?? client).get<GetFineResponses, GetFineErrors, ThrowOnError>({
    url: '/api/groups/{groupSlug}/fines/{fineId}',
    ...options,
  });
};

/**
 * Partially update fine
 *
 * Partially update a fine. Only provided fields will be updated. Users can add defense to their own fines. Fines admins can update status and approve/reject fines.
 */
export const updateFine = <ThrowOnError extends boolean = false>(options: Options<UpdateFineData, ThrowOnError>) => {
  return (options.client ?? client).patch<UpdateFineResponses, UpdateFineErrors, ThrowOnError>({
    url: '/api/groups/{groupSlug}/fines/{fineId}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * List group members
 *
 * Retrieve a list of all members in a group.
 */
export const listGroupMembers = <ThrowOnError extends boolean = false>(options: Options<ListGroupMembersData, ThrowOnError>) => {
  return (options.client ?? client).get<ListGroupMembersResponses, ListGroupMembersErrors, ThrowOnError>({
    url: '/api/groups/{groupSlug}/members',
    ...options,
  });
};

/**
 * Add member to group
 *
 * Add a member to a group. Requires 'groups:manage' permission.
 */
export const addGroupMember = <ThrowOnError extends boolean = false>(options: Options<AddGroupMemberData, ThrowOnError>) => {
  return (options.client ?? client).post<AddGroupMemberResponses, AddGroupMemberErrors, ThrowOnError>({
    url: '/api/groups/{groupSlug}/members',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * Remove member from group
 *
 * Remove a member from a group. Requires 'groups:manage' permission.
 */
export const removeGroupMember = <ThrowOnError extends boolean = false>(options: Options<RemoveGroupMemberData, ThrowOnError>) => {
  return (options.client ?? client).delete<RemoveGroupMemberResponses, RemoveGroupMemberErrors, ThrowOnError>({
    url: '/api/groups/{groupSlug}/members/{userId}',
    ...options,
  });
};

/**
 * Update member role
 *
 * Update a member's role in a group. Requires 'groups:manage' permission.
 */
export const updateGroupMemberRole = <ThrowOnError extends boolean = false>(options: Options<UpdateGroupMemberRoleData, ThrowOnError>) => {
  return (options.client ?? client).patch<UpdateGroupMemberRoleResponses, UpdateGroupMemberRoleErrors, ThrowOnError>({
    url: '/api/groups/{groupSlug}/members/{userId}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * List group forms
 *
 * Get all forms for a group, filtered by user permissions
 */
export const listGroupForms = <ThrowOnError extends boolean = false>(options: Options<ListGroupFormsData, ThrowOnError>) => {
  return (options.client ?? client).get<ListGroupFormsResponses, ListGroupFormsErrors, ThrowOnError>({
    url: '/api/groups/{slug}/forms',
    ...options,
  });
};

/**
 * Create group form
 *
 * Create a form for a group. Requires group leader permission or forms:create permission.
 */
export const createGroupForm = <ThrowOnError extends boolean = false>(options: Options<CreateGroupFormData, ThrowOnError>) => {
  return (options.client ?? client).post<CreateGroupFormResponses, CreateGroupFormErrors, ThrowOnError>({
    url: '/api/groups/{slug}/forms',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * List news articles
 *
 * Get a paginated list of all news articles. Public endpoint.
 */
export const listNews = <ThrowOnError extends boolean = false>(options?: Options<ListNewsData, ThrowOnError>) => {
  return (options?.client ?? client).get<ListNewsResponses, unknown, ThrowOnError>({
    url: '/api/news',
    ...options,
  });
};

/**
 * Create news article
 *
 * Create a new news article. Requires 'news:create' permission.
 */
export const createNews = <ThrowOnError extends boolean = false>(options?: Options<CreateNewsData, ThrowOnError>) => {
  return (options?.client ?? client).post<CreateNewsResponses, CreateNewsErrors, ThrowOnError>({
    url: '/api/news',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * Delete news article
 *
 * Delete a news article. Requires 'news:delete' or 'news:manage' permission (global or scoped) or being the creator.
 */
export const deleteNews = <ThrowOnError extends boolean = false>(options: Options<DeleteNewsData, ThrowOnError>) => {
  return (options.client ?? client).delete<DeleteNewsResponses, DeleteNewsErrors, ThrowOnError>({
    url: '/api/news/{id}',
    ...options,
  });
};

/**
 * Get news article
 *
 * Get a single news article by ID. Public endpoint.
 */
export const getNews = <ThrowOnError extends boolean = false>(options: Options<GetNewsData, ThrowOnError>) => {
  return (options.client ?? client).get<GetNewsResponses, GetNewsErrors, ThrowOnError>({
    url: '/api/news/{id}',
    ...options,
  });
};

/**
 * Update news article
 *
 * Update a news article. Requires 'news:update' or 'news:manage' permission (global or scoped) or being the creator.
 */
export const updateNews = <ThrowOnError extends boolean = false>(options: Options<UpdateNewsData, ThrowOnError>) => {
  return (options.client ?? client).patch<UpdateNewsResponses, UpdateNewsErrors, ThrowOnError>({
    url: '/api/news/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * Remove reaction from news
 *
 * Remove your emoji reaction from a news article.
 */
export const deleteNewsReaction = <ThrowOnError extends boolean = false>(options: Options<DeleteNewsReactionData, ThrowOnError>) => {
  return (options.client ?? client).delete<DeleteNewsReactionResponses, DeleteNewsReactionErrors, ThrowOnError>({
    url: '/api/news/{id}/reactions',
    ...options,
  });
};

/**
 * Add reaction to news
 *
 * Add or update emoji reaction to a news article. Requires authentication.
 */
export const createNewsReaction = <ThrowOnError extends boolean = false>(options: Options<CreateNewsReactionData, ThrowOnError>) => {
  return (options.client ?? client).post<CreateNewsReactionResponses, CreateNewsReactionErrors, ThrowOnError>({
    url: '/api/news/{id}/reactions',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * List job postings
 *
 * Get a list of job postings. Supports search and expired filtering. Public endpoint.
 */
export const listJobs = <ThrowOnError extends boolean = false>(options?: Options<ListJobsData, ThrowOnError>) => {
  return (options?.client ?? client).get<ListJobsResponses, unknown, ThrowOnError>({
    url: '/api/jobs',
    ...options,
  });
};

/**
 * Create job posting
 *
 * Create a new job posting. Requires 'jobs:create' permission.
 */
export const createJob = <ThrowOnError extends boolean = false>(options?: Options<CreateJobData, ThrowOnError>) => {
  return (options?.client ?? client).post<CreateJobResponses, CreateJobErrors, ThrowOnError>({
    url: '/api/jobs',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * Delete job posting
 *
 * Delete a job posting. Requires 'jobs:delete' or 'jobs:manage' permission (global or scoped) or being the creator.
 */
export const deleteJob = <ThrowOnError extends boolean = false>(options: Options<DeleteJobData, ThrowOnError>) => {
  return (options.client ?? client).delete<DeleteJobResponses, DeleteJobErrors, ThrowOnError>({
    url: '/api/jobs/{id}',
    ...options,
  });
};

/**
 * Get job posting
 *
 * Get a single job posting by ID. Public endpoint.
 */
export const getJob = <ThrowOnError extends boolean = false>(options: Options<GetJobData, ThrowOnError>) => {
  return (options.client ?? client).get<GetJobResponses, GetJobErrors, ThrowOnError>({
    url: '/api/jobs/{id}',
    ...options,
  });
};

/**
 * Update job posting
 *
 * Update a job posting. Requires 'jobs:update' or 'jobs:manage' permission (global or scoped) or being the creator.
 */
export const updateJob = <ThrowOnError extends boolean = false>(options: Options<UpdateJobData, ThrowOnError>) => {
  return (options.client ?? client).patch<UpdateJobResponses, UpdateJobErrors, ThrowOnError>({
    url: '/api/jobs/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * Get current user settings
 *
 * Retrieve the authenticated user's settings including preferences and allergies.
 */
export const getUserSettings = <ThrowOnError extends boolean = false>(options?: Options<GetUserSettingsData, ThrowOnError>) => {
  return (options?.client ?? client).get<GetUserSettingsResponses, GetUserSettingsErrors, ThrowOnError>({
    url: '/api/user/me/settings',
    ...options,
  });
};

/**
 * Update user settings
 *
 * Partially update the authenticated user's settings. Only provided fields will be updated. User must have completed onboarding first.
 */
export const updateUserSettings = <ThrowOnError extends boolean = false>(options?: Options<UpdateUserSettingsData, ThrowOnError>) => {
  return (options?.client ?? client).patch<UpdateUserSettingsResponses, UpdateUserSettingsErrors, ThrowOnError>({
    url: '/api/user/me/settings',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * Complete user onboarding
 *
 * Create initial user settings and mark the user as onboarded. Can only be called once per user.
 */
export const onboardUser = <ThrowOnError extends boolean = false>(options?: Options<OnboardUserData, ThrowOnError>) => {
  return (options?.client ?? client).post<OnboardUserResponses, OnboardUserErrors, ThrowOnError>({
    url: '/api/user/me/settings',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * List all allergies
 *
 * Retrieve a list of all possible allergies that users can have.
 */
export const listAllergies = <ThrowOnError extends boolean = false>(options?: Options<ListAllergiesData, ThrowOnError>) => {
  return (options?.client ?? client).get<ListAllergiesResponses, unknown, ThrowOnError>({
    url: '/api/user/allergy',
    ...options,
  });
};
