// This file is auto-generated by @hey-api/openapi-ts

import type {
  CreateApiKeyResponse,
  GetApiKeyResponse,
  GetFavoriteEventsResponse,
  ListApiKeysResponse,
  ListEventsResponse,
  ListNotificationsResponse,
  MarkNotificationReadResponse,
  RegenerateApiKeyResponse,
  UpdateApiKeyResponse,
  ValidateApiKeyResponse,
} from './types.gen';

export const listApiKeysResponseTransformer = async (data: any): Promise<ListApiKeysResponse> => {
  data = data.map((item: any) => {
    if (item.lastUsedAt) {
      item.lastUsedAt = new Date(item.lastUsedAt);
    }
    item.createdAt = new Date(item.createdAt);
    item.updatedAt = new Date(item.updatedAt);
    return item;
  });
  return data;
};

export const createApiKeyResponseTransformer = async (data: any): Promise<CreateApiKeyResponse> => {
  if (data.lastUsedAt) {
    data.lastUsedAt = new Date(data.lastUsedAt);
  }
  data.createdAt = new Date(data.createdAt);
  data.updatedAt = new Date(data.updatedAt);
  return data;
};

export const getApiKeyResponseTransformer = async (data: any): Promise<GetApiKeyResponse> => {
  if (data.lastUsedAt) {
    data.lastUsedAt = new Date(data.lastUsedAt);
  }
  data.createdAt = new Date(data.createdAt);
  data.updatedAt = new Date(data.updatedAt);
  return data;
};

export const updateApiKeyResponseTransformer = async (data: any): Promise<UpdateApiKeyResponse> => {
  if (data.lastUsedAt) {
    data.lastUsedAt = new Date(data.lastUsedAt);
  }
  data.createdAt = new Date(data.createdAt);
  data.updatedAt = new Date(data.updatedAt);
  return data;
};

export const regenerateApiKeyResponseTransformer = async (data: any): Promise<RegenerateApiKeyResponse> => {
  if (data.lastUsedAt) {
    data.lastUsedAt = new Date(data.lastUsedAt);
  }
  data.createdAt = new Date(data.createdAt);
  data.updatedAt = new Date(data.updatedAt);
  return data;
};

export const validateApiKeyResponseTransformer = async (data: any): Promise<ValidateApiKeyResponse> => {
  if (data.apiKey) {
    if (data.apiKey.lastUsedAt) {
      data.apiKey.lastUsedAt = new Date(data.apiKey.lastUsedAt);
    }
    data.apiKey.createdAt = new Date(data.apiKey.createdAt);
    data.apiKey.updatedAt = new Date(data.apiKey.updatedAt);
  }
  return data;
};

export const listEventsResponseTransformer = async (data: any): Promise<ListEventsResponse> => {
  data = data.map((item: any) => {
    item.startTime = new Date(item.startTime);
    item.endTime = new Date(item.endTime);
    item.createdAt = new Date(item.createdAt);
    item.updatedAt = new Date(item.updatedAt);
    return item;
  });
  return data;
};

export const getFavoriteEventsResponseTransformer = async (data: any): Promise<GetFavoriteEventsResponse> => {
  data = data.map((item: any) => {
    item.createdAt = new Date(item.createdAt);
    return item;
  });
  return data;
};

export const listNotificationsResponseTransformer = async (data: any): Promise<ListNotificationsResponse> => {
  data = data.map((item: any) => {
    item.createdAt = new Date(item.createdAt);
    item.updatedAt = new Date(item.updatedAt);
    return item;
  });
  return data;
};

export const markNotificationReadResponseTransformer = async (data: any): Promise<MarkNotificationReadResponse> => {
  data.updatedAt = new Date(data.updatedAt);
  return data;
};
