// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: 'http://localhost:4000' | 'https://photon.tihlde.org' | (string & {});
};

export type ListApiKeysData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/api-keys';
};

export type ListApiKeysErrors = {
  /**
   * Forbidden - Missing api-keys:view permission
   */
  403: unknown;
};

export type ListApiKeysResponses = {
  /**
   * List of API keys
   */
  200: Array<{
    /**
     * API key ID
     */
    id: string;
    /**
     * Name of the API key
     */
    name: string;
    /**
     * Description of the API key
     */
    description: string;
    /**
     * First 12 characters of the key for display
     */
    keyPrefix: string;
    /**
     * User ID who created this key
     */
    createdById: string | null;
    /**
     * When the key was last used
     */
    lastUsedAt: Date | null;
    /**
     * Array of permissions granted to this API key
     */
    permissions: Array<string>;
    /**
     * Optional metadata as key-value pairs
     */
    metadata: {
      [key: string]: unknown;
    } | null;
    /**
     * When the key was created
     */
    createdAt: Date;
    /**
     * When the key was last updated
     */
    updatedAt: Date;
  }>;
};

export type ListApiKeysResponse = ListApiKeysResponses[keyof ListApiKeysResponses];

export type CreateApiKeyData = {
  body?: {
    /**
     * Name for the API key
     */
    name: string;
    /**
     * Detailed description of the API key's purpose
     */
    description: string;
    /**
     * Array of permissions granted to this API key (e.g., ['email:send', 'news:create']). Service validates against allowed permissions.
     */
    permissions: Array<string>;
    /**
     * Optional metadata as key-value pairs
     */
    metadata?: {
      [key: string]: unknown;
    };
  };
  path?: never;
  query?: never;
  url: '/api/api-keys';
};

export type CreateApiKeyErrors = {
  /**
   * Forbidden - Missing api-keys:create permission
   */
  403: unknown;
};

export type CreateApiKeyResponses = {
  /**
   * API key created successfully. The 'key' field contains the full API key and will not be shown again.
   */
  201: {
    /**
     * API key ID
     */
    id: string;
    /**
     * Name of the API key
     */
    name: string;
    /**
     * Description of the API key
     */
    description: string;
    /**
     * First 12 characters of the key for display
     */
    keyPrefix: string;
    /**
     * User ID who created this key
     */
    createdById: string | null;
    /**
     * When the key was last used
     */
    lastUsedAt: Date | null;
    /**
     * Array of permissions granted to this API key
     */
    permissions: Array<string>;
    /**
     * Optional metadata as key-value pairs
     */
    metadata: {
      [key: string]: unknown;
    } | null;
    /**
     * When the key was created
     */
    createdAt: Date;
    /**
     * When the key was last updated
     */
    updatedAt: Date;
    /**
     * The full API key - ONLY returned on creation and regeneration. Cannot be retrieved again.
     */
    key: string;
  };
};

export type CreateApiKeyResponse = CreateApiKeyResponses[keyof CreateApiKeyResponses];

export type DeleteApiKeyData = {
  body?: never;
  path: {
    /**
     * API key ID
     */
    id: string;
  };
  query?: never;
  url: '/api/api-keys/{id}';
};

export type DeleteApiKeyErrors = {
  /**
   * Forbidden - Missing api-keys:delete permission
   */
  403: unknown;
  /**
   * API key not found
   */
  404: unknown;
};

export type DeleteApiKeyResponses = {
  /**
   * API key deleted successfully
   */
  200: {
    /**
     * Success message
     */
    message: string;
  };
};

export type DeleteApiKeyResponse = DeleteApiKeyResponses[keyof DeleteApiKeyResponses];

export type GetApiKeyData = {
  body?: never;
  path: {
    /**
     * API key ID
     */
    id: string;
  };
  query?: never;
  url: '/api/api-keys/{id}';
};

export type GetApiKeyErrors = {
  /**
   * Forbidden - Missing api-keys:view permission
   */
  403: unknown;
  /**
   * API key not found
   */
  404: unknown;
};

export type GetApiKeyResponses = {
  /**
   * API key details
   */
  200: {
    /**
     * API key ID
     */
    id: string;
    /**
     * Name of the API key
     */
    name: string;
    /**
     * Description of the API key
     */
    description: string;
    /**
     * First 12 characters of the key for display
     */
    keyPrefix: string;
    /**
     * User ID who created this key
     */
    createdById: string | null;
    /**
     * When the key was last used
     */
    lastUsedAt: Date | null;
    /**
     * Array of permissions granted to this API key
     */
    permissions: Array<string>;
    /**
     * Optional metadata as key-value pairs
     */
    metadata: {
      [key: string]: unknown;
    } | null;
    /**
     * When the key was created
     */
    createdAt: Date;
    /**
     * When the key was last updated
     */
    updatedAt: Date;
  };
};

export type GetApiKeyResponse = GetApiKeyResponses[keyof GetApiKeyResponses];

export type UpdateApiKeyData = {
  body?: {
    /**
     * Name for the API key
     */
    name?: string;
    /**
     * Detailed description of the API key's purpose
     */
    description?: string;
    /**
     * Array of permissions granted to this API key
     */
    permissions?: Array<string>;
    /**
     * Optional metadata as key-value pairs
     */
    metadata?: {
      [key: string]: unknown;
    };
  };
  path: {
    /**
     * API key ID
     */
    id: string;
  };
  query?: never;
  url: '/api/api-keys/{id}';
};

export type UpdateApiKeyErrors = {
  /**
   * Forbidden - Missing api-keys:update permission
   */
  403: unknown;
  /**
   * API key not found
   */
  404: unknown;
};

export type UpdateApiKeyResponses = {
  /**
   * API key updated successfully
   */
  200: {
    /**
     * API key ID
     */
    id: string;
    /**
     * Name of the API key
     */
    name: string;
    /**
     * Description of the API key
     */
    description: string;
    /**
     * First 12 characters of the key for display
     */
    keyPrefix: string;
    /**
     * User ID who created this key
     */
    createdById: string | null;
    /**
     * When the key was last used
     */
    lastUsedAt: Date | null;
    /**
     * Array of permissions granted to this API key
     */
    permissions: Array<string>;
    /**
     * Optional metadata as key-value pairs
     */
    metadata: {
      [key: string]: unknown;
    } | null;
    /**
     * When the key was created
     */
    createdAt: Date;
    /**
     * When the key was last updated
     */
    updatedAt: Date;
  };
};

export type UpdateApiKeyResponse = UpdateApiKeyResponses[keyof UpdateApiKeyResponses];

export type RegenerateApiKeyData = {
  body?: never;
  path: {
    /**
     * API key ID
     */
    id: string;
  };
  query?: never;
  url: '/api/api-keys/{id}/regenerate';
};

export type RegenerateApiKeyErrors = {
  /**
   * Forbidden - Missing api-keys:update permission
   */
  403: unknown;
  /**
   * API key not found
   */
  404: unknown;
};

export type RegenerateApiKeyResponses = {
  /**
   * API key regenerated successfully. The 'key' field contains the new API key and will not be shown again.
   */
  200: {
    /**
     * API key ID
     */
    id: string;
    /**
     * Name of the API key
     */
    name: string;
    /**
     * Description of the API key
     */
    description: string;
    /**
     * First 12 characters of the key for display
     */
    keyPrefix: string;
    /**
     * User ID who created this key
     */
    createdById: string | null;
    /**
     * When the key was last used
     */
    lastUsedAt: Date | null;
    /**
     * Array of permissions granted to this API key
     */
    permissions: Array<string>;
    /**
     * Optional metadata as key-value pairs
     */
    metadata: {
      [key: string]: unknown;
    } | null;
    /**
     * When the key was created
     */
    createdAt: Date;
    /**
     * When the key was last updated
     */
    updatedAt: Date;
    /**
     * The full API key - ONLY returned on creation and regeneration. Cannot be retrieved again.
     */
    key: string;
  };
};

export type RegenerateApiKeyResponse = RegenerateApiKeyResponses[keyof RegenerateApiKeyResponses];

export type ValidateApiKeyData = {
  body?: {
    /**
     * The API key to validate
     */
    key: string;
  };
  path?: never;
  query?: never;
  url: '/api/api-keys/validate';
};

export type ValidateApiKeyResponses = {
  /**
   * Validation result. If valid=true, includes the API key details and permissions.
   */
  200: {
    /**
     * Whether the API key is valid
     */
    valid: boolean;
    /**
     * The API key details and permissions if valid. Undefined if invalid.
     */
    apiKey?: {
      /**
       * API key ID
       */
      id: string;
      /**
       * Name of the API key
       */
      name: string;
      /**
       * Description of the API key
       */
      description: string;
      /**
       * First 12 characters of the key for display
       */
      keyPrefix: string;
      /**
       * User ID who created this key
       */
      createdById: string | null;
      /**
       * When the key was last used
       */
      lastUsedAt: Date | null;
      /**
       * Array of permissions granted to this API key
       */
      permissions: Array<string>;
      /**
       * Optional metadata as key-value pairs
       */
      metadata: {
        [key: string]: unknown;
      } | null;
      /**
       * When the key was created
       */
      createdAt: Date;
      /**
       * When the key was last updated
       */
      updatedAt: Date;
    };
  };
};

export type ValidateApiKeyResponse = ValidateApiKeyResponses[keyof ValidateApiKeyResponses];

export type SendCustomEmailData = {
  body?: {
    /**
     * Recipient email address (string) or list of recipient email addresses (array)
     */
    to: string | Array<string>;
    /**
     * Email subject line
     */
    subject: string;
    /**
     * Array of content blocks (title, text, or button) to render in the email
     */
    content: Array<
      | {
          /**
           * Content block type
           */
          type: 'title';
          /**
           * The title text to display
           */
          content: string;
        }
      | {
          /**
           * Content block type
           */
          type: 'text';
          /**
           * The paragraph text to display
           */
          content: string;
        }
      | {
          /**
           * Content block type
           */
          type: 'button';
          /**
           * The button label text
           */
          text: string;
          /**
           * The URL the button links to
           */
          url: string;
        }
    >;
  };
  path?: never;
  query?: never;
  url: '/api/email/send';
};

export type SendCustomEmailErrors = {
  /**
   * Missing or invalid Authorization header
   */
  401: unknown;
  /**
   * Invalid API key
   */
  403: unknown;
  /**
   * Email API not configured
   */
  503: unknown;
};

export type SendCustomEmailResponses = {
  /**
   * Email queued successfully
   */
  200: {
    success: boolean;
    message: string;
    jobIds: Array<string>;
    recipientCount: number;
  };
};

export type SendCustomEmailResponse = SendCustomEmailResponses[keyof SendCustomEmailResponses];

export type ListEventsData = {
  body?: never;
  path?: never;
  query?: {
    limit?: number;
    offset?: number;
  };
  url: '/api/event';
};

export type ListEventsResponses = {
  /**
   * OK
   */
  200: Array<{
    /**
     * Event ID
     */
    id: string;
    /**
     * Event slug
     */
    slug: string;
    /**
     * Event title
     */
    title: string;
    /**
     * Event location (nullable)
     */
    location?: string | null;
    /**
     * Event start time (ISO 8601)
     */
    startTime: Date;
    /**
     * Event end time (ISO 8601)
     */
    endTime: Date;
    /**
     * Event organizer (nullable)
     */
    organizer: {
      /**
       * Organizer name
       */
      name: string;
      /**
       * Organizer slug
       */
      slug: string;
      /**
       * Organizer type
       */
      type: string;
    } | null;
    /**
     * Is registration closed
     */
    closed: boolean;
    /**
     * Event image URL (nullable)
     */
    image: string | null;
    /**
     * Event creation time (ISO 8601)
     */
    createdAt: Date;
    /**
     * Event update time (ISO 8601)
     */
    updatedAt: Date;
    /**
     * Event category
     */
    category: {
      /**
       * Category slug
       */
      slug: string;
      /**
       * Category label
       */
      label: string;
    };
  }>;
};

export type ListEventsResponse = ListEventsResponses[keyof ListEventsResponses];

export type CreateEventData = {
  body?: {
    /**
     * Short title of the event
     */
    title: string;
    /**
     * Description of the event
     */
    description: string;
    /**
     * Category slug for the event
     */
    categorySlug: string;
    /**
     * Slug of the group organizing the event
     */
    organizerGroupSlug: string;
    /**
     * Location of the event (physical or online)
     */
    location: string;
    /**
     * Main image to display for the event
     */
    imageUrl: string | null;
    /**
     * When the event starts
     */
    start: Date;
    /**
     * When the event ends
     */
    end: Date;
    /**
     * Timestamp for when registrations open. If null, open immediately.
     */
    registrationStart: Date | null;
    /**
     * When the registration for the event ends. After this time, users cannot sign up.
     */
    registrationEnd: Date;
    /**
     * Deadline timestamp for when users cannot cancel anymore. After this, no-shows may receive strikes.
     */
    cancellationDeadline: Date | null;
    /**
     * Maximum number of participants allowed. If null, no capacity limit.
     */
    capacity: number | null;
    /**
     * Is the event closed for new registrations? This overrides registrationStart/End
     */
    isRegistrationClosed: boolean;
    /**
     * Do users need to sign up to attend the event?
     */
    requiresSigningUp: boolean;
    /**
     * Should users be allowed to join a waitlist if the event is full?
     */
    allowWaitlist: boolean;
    /**
     * List of priority pools, with priority in descending order. Each pool contains a list of group slugs. Users in groups in the first pool have highest priority, then second pool, etc. Users not in any pool have lowest priority.
     */
    priorityPools: Array<{
      /**
       * Group slugs in this pool
       */
      groups: Array<string>;
    }> | null;
    /**
     * Only allow users in at least one priority pool to sign up. Can only be true if at least one group is in priorityPools.
     */
    onlyAllowPrioritized: boolean;
    /**
     * Can this event give strike penalties to users?
     */
    canCauseStrikes: boolean;
    /**
     * Should the system enforce strike rules for this event?
     */
    enforcesPreviousStrikes: boolean;
    /**
     * Is this a paid event?
     */
    isPaidEvent: boolean;
    /**
     * Price in NOK for attending the event. Can only be set if isPaidEvent is true.
     */
    price: number | null;
    /**
     * The time (in minutes) between sign up and payment must be made. After this period, unpaid registrations are cancelled. Can only be set if isPaidEvent is true.
     */
    paymentGracePeriodMinutes: number | null;
    /**
     * User ID of the primary contact person for the event
     */
    contactPersonUserId: string | null;
    /**
     * Should users be able to react to this event with emojis?
     */
    reactionsAllowed: boolean;
  };
  path?: never;
  query?: never;
  url: '/api/event';
};

export type CreateEventErrors = {
  /**
   * Forbidden - Missing events:create permission
   */
  403: unknown;
};

export type CreateEventResponses = {
  /**
   * Created
   */
  201: {
    eventId: string;
  };
};

export type CreateEventResponse = CreateEventResponses[keyof CreateEventResponses];

export type UpdateEventData = {
  body?: {
    /**
     * Short title of the event
     */
    title?: string;
    /**
     * Description of the event
     */
    description?: string;
    /**
     * Category slug for the event
     */
    categorySlug?: string;
    /**
     * Slug of the group organizing the event
     */
    organizerGroupSlug?: string;
    /**
     * Location of the event (physical or online)
     */
    location?: string;
    /**
     * Main image to display for the event
     */
    imageUrl?: string | null;
    /**
     * When the event starts
     */
    start?: Date;
    /**
     * When the event ends
     */
    end?: Date;
    /**
     * Timestamp for when registrations open. If null, open immediately.
     */
    registrationStart?: Date | null;
    /**
     * When the registration for the event ends. After this time, users cannot sign up.
     */
    registrationEnd?: Date;
    /**
     * Deadline timestamp for when users cannot cancel anymore. After this, no-shows may receive strikes.
     */
    cancellationDeadline?: Date | null;
    /**
     * Maximum number of participants allowed. If null, no capacity limit.
     */
    capacity?: number | null;
    /**
     * Is the event closed for new registrations? This overrides registrationStart/End
     */
    isRegistrationClosed?: boolean;
    /**
     * Do users need to sign up to attend the event?
     */
    requiresSigningUp?: boolean;
    /**
     * Should users be allowed to join a waitlist if the event is full?
     */
    allowWaitlist?: boolean;
    /**
     * List of priority pools, with priority in descending order. Each pool contains a list of group slugs. Users in groups in the first pool have highest priority, then second pool, etc. Users not in any pool have lowest priority.
     */
    priorityPools?: Array<{
      /**
       * Group slugs in this pool
       */
      groups: Array<string>;
    }> | null;
    /**
     * Only allow users in at least one priority pool to sign up. Can only be true if at least one group is in priorityPools.
     */
    onlyAllowPrioritized?: boolean;
    /**
     * Can this event give strike penalties to users?
     */
    canCauseStrikes?: boolean;
    /**
     * Should the system enforce strike rules for this event?
     */
    enforcesPreviousStrikes?: boolean;
    /**
     * Is this a paid event?
     */
    isPaidEvent?: boolean;
    /**
     * Price in NOK for attending the event. Can only be set if isPaidEvent is true.
     */
    price?: number | null;
    /**
     * The time (in minutes) between sign up and payment must be made. After this period, unpaid registrations are cancelled. Can only be set if isPaidEvent is true.
     */
    paymentGracePeriodMinutes?: number | null;
    /**
     * User ID of the primary contact person for the event
     */
    contactPersonUserId?: string | null;
    /**
     * Should users be able to react to this event with emojis?
     */
    reactionsAllowed?: boolean;
  };
  path: {
    id: string;
  };
  query?: never;
  url: '/api/event/{id}';
};

export type UpdateEventErrors = {
  /**
   * Forbidden - You must be the event creator or have events:update/events:manage permission
   */
  403: unknown;
  /**
   * Not found
   */
  404: unknown;
};

export type UpdateEventResponses = {
  /**
   * Updated
   */
  200: unknown;
};

export type DeleteEventData = {
  body?: never;
  path: {
    eventId: string;
  };
  query?: never;
  url: '/api/event/{eventId}';
};

export type DeleteEventErrors = {
  /**
   * Forbidden - You must be the event creator or have events:delete permission
   */
  403: unknown;
  /**
   * Not Found - Event with the specified ID does not exist
   */
  404: unknown;
};

export type DeleteEventResponses = {
  /**
   * Event successfully deleted
   */
  200: unknown;
};

export type UpdateEventFavoriteData = {
  body?: {
    /**
     * Is favorite
     */
    isFavorite: boolean;
  };
  path: {
    id: string;
  };
  query?: never;
  url: '/api/event/favorite/{id}';
};

export type UpdateEventFavoriteErrors = {
  /**
   * Not found
   */
  404: unknown;
};

export type UpdateEventFavoriteResponses = {
  /**
   * Updated
   */
  200: unknown;
};

export type GetFavoriteEventsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/event/favorite';
};

export type GetFavoriteEventsResponses = {
  /**
   * List of favorite events
   */
  200: Array<{
    /**
     * Event ID
     */
    eventId: string;
    /**
     * Event title
     */
    title: string;
    /**
     * Event slug
     */
    slug: string;
    /**
     * When you added this event to your favorites
     */
    createdAt: Date;
  }>;
};

export type GetFavoriteEventsResponse = GetFavoriteEventsResponses[keyof GetFavoriteEventsResponses];

export type DeleteEventRegistrationData = {
  body?: never;
  path: {
    eventId: string;
  };
  query?: never;
  url: '/api/event/{eventId}/registration';
};

export type DeleteEventRegistrationResponses = {
  /**
   * OK
   */
  200: {
    [key: string]: unknown;
  };
};

export type DeleteEventRegistrationResponse = DeleteEventRegistrationResponses[keyof DeleteEventRegistrationResponses];

export type ListEventRegistrationsData = {
  body?: never;
  path: {
    eventId: string;
  };
  query?: {
    limit?: number;
    offset?: number;
  };
  url: '/api/event/{eventId}/registration';
};

export type ListEventRegistrationsResponses = {
  /**
   * OK
   */
  200: Array<{
    registeredUsers: Array<{
      /**
       * User id
       */
      id: string;
      /**
       * User name
       */
      name: string;
      /**
       * User image url (if any)
       */
      image: string | null;
    }>;
    /**
     * Total registered users. These users have access to the event.
     */
    registeredCount: number;
    /**
     * Number of users on the waitlist. These users are waiting in queue for a spot.
     */
    waitlistCount: number;
  }>;
};

export type ListEventRegistrationsResponse = ListEventRegistrationsResponses[keyof ListEventRegistrationsResponses];

export type CreateEventRegistrationData = {
  body?: never;
  path: {
    eventId: string;
  };
  query?: never;
  url: '/api/event/{eventId}/registration';
};

export type CreateEventRegistrationErrors = {
  /**
   * Event not found
   */
  404: unknown;
  /**
   * Event is not open for registration or user already registered
   */
  409: unknown;
};

export type CreateEventRegistrationResponses = {
  /**
   * OK
   */
  200: {
    eventId: string;
    userId: string;
    status: 'pending';
    createdAt: string;
  };
};

export type CreateEventRegistrationResponse = CreateEventRegistrationResponses[keyof CreateEventRegistrationResponses];

export type CreateEventPaymentData = {
  body?: {
    /**
     * URL to redirect user after payment
     */
    returnUrl: string;
    /**
     * User flow type for payment
     */
    userFlow?: 'WEB_REDIRECT' | 'NATIVE_REDIRECT';
  };
  path: {
    eventId: string;
  };
  query?: never;
  url: '/api/event/{eventId}/payment';
};

export type CreateEventPaymentErrors = {
  /**
   * Bad request - event not found or not a paid event
   */
  400: unknown;
  /**
   * Event or registration not found
   */
  404: unknown;
  /**
   * Payment already exists for this user and event
   */
  409: unknown;
};

export type CreateEventPaymentResponses = {
  /**
   * Payment created successfully
   */
  201: {
    eventId: string;
    userId: string;
    checkoutUrl: string;
    amount: number;
    currency: string;
  };
};

export type CreateEventPaymentResponse = CreateEventPaymentResponses[keyof CreateEventPaymentResponses];

export type HandlePaymentWebhookData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/event/payment/webhook';
};

export type HandlePaymentWebhookErrors = {
  /**
   * Invalid webhook payload
   */
  400: unknown;
  /**
   * Payment not found
   */
  404: unknown;
};

export type HandlePaymentWebhookResponses = {
  /**
   * Webhook processed successfully
   */
  200: unknown;
};

export type ListEventFormsData = {
  body?: never;
  path: {
    eventId: string;
  };
  query?: never;
  url: '/api/event/{eventId}/forms';
};

export type ListEventFormsErrors = {
  /**
   * Event not found
   */
  404: unknown;
};

export type ListEventFormsResponses = {
  /**
   * Success
   */
  200: Array<{
    id: string;
    title: string;
    description: string | null;
    type: 'survey' | 'evaluation';
    resource_type: string;
    viewer_has_answered: boolean;
    created_at: string;
    updated_at: string;
  }>;
};

export type ListEventFormsResponse = ListEventFormsResponses[keyof ListEventFormsResponses];

export type CreateEventFormData = {
  body?: {
    title: string;
    description?: string;
    template?: boolean;
    fields?: Array<{
      title: string;
      type: 'text_answer' | 'multiple_select' | 'single_select';
      required?: boolean;
      order?: number;
      options?: Array<{
        title: string;
        order?: number;
      }>;
    }>;
    event: string;
    type: 'survey' | 'evaluation';
  };
  path: {
    eventId: string;
  };
  query?: never;
  url: '/api/event/{eventId}/forms';
};

export type CreateEventFormErrors = {
  /**
   * Bad request - Form already exists for this event type
   */
  400: unknown;
  /**
   * Forbidden
   */
  403: unknown;
  /**
   * Event not found
   */
  404: unknown;
};

export type CreateEventFormResponses = {
  /**
   * Created
   */
  201: unknown;
};

export type GetEventFormData = {
  body?: never;
  path: {
    eventId: string;
    type: string;
  };
  query?: never;
  url: '/api/event/{eventId}/forms/{type}';
};

export type GetEventFormErrors = {
  /**
   * Forbidden - Evaluation forms require attendance
   */
  403: unknown;
  /**
   * Form not found
   */
  404: unknown;
};

export type GetEventFormResponses = {
  /**
   * Success
   */
  200: {
    id: string;
    title: string;
    description: string | null;
    type: 'survey' | 'evaluation';
    resource_type: string;
    viewer_has_answered: boolean;
    website_url: string;
    created_at: string;
    updated_at: string;
    fields: Array<{
      id: string;
      title: string;
      type: 'text_answer' | 'multiple_select' | 'single_select';
      required: boolean;
      order: number;
      options: Array<{
        id: string;
        title: string;
        order: number;
      }>;
    }>;
  };
};

export type GetEventFormResponse = GetEventFormResponses[keyof GetEventFormResponses];

export type ListFormsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/forms';
};

export type ListFormsResponses = {
  /**
   * Success
   */
  200: Array<{
    id: string;
    title: string;
    description: string | null;
    template: boolean;
    resource_type: string;
    viewer_has_answered: boolean;
    created_at: string;
    updated_at: string;
  }>;
};

export type ListFormsResponse = ListFormsResponses[keyof ListFormsResponses];

export type CreateFormData = {
  body?: {
    title: string;
    description?: string;
    template?: boolean;
    fields?: Array<{
      title: string;
      type: 'text_answer' | 'multiple_select' | 'single_select';
      required?: boolean;
      order?: number;
      options?: Array<{
        title: string;
        order?: number;
      }>;
    }>;
  };
  path?: never;
  query?: never;
  url: '/api/forms';
};

export type CreateFormErrors = {
  /**
   * Forbidden - Missing forms:create permission
   */
  403: unknown;
};

export type CreateFormResponses = {
  /**
   * Created
   */
  201: {
    id: string;
    title: string;
    description: string | null;
    template: boolean;
    created_at: string;
    updated_at: string;
  };
};

export type CreateFormResponse = CreateFormResponses[keyof CreateFormResponses];

export type DeleteFormData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/api/forms/{id}';
};

export type DeleteFormErrors = {
  /**
   * Forbidden
   */
  403: unknown;
  /**
   * Form not found
   */
  404: unknown;
};

export type DeleteFormResponses = {
  /**
   * Success
   */
  200: unknown;
};

export type GetFormData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/api/forms/{id}';
};

export type GetFormErrors = {
  /**
   * Form not found
   */
  404: unknown;
};

export type GetFormResponses = {
  /**
   * Success
   */
  200: {
    id: string;
    title: string;
    description: string | null;
    template: boolean;
    resource_type: string;
    viewer_has_answered: boolean;
    website_url: string;
    created_at: string;
    updated_at: string;
    fields: Array<{
      id: string;
      title: string;
      type: 'text_answer' | 'multiple_select' | 'single_select';
      required: boolean;
      order: number;
      options: Array<{
        id: string;
        title: string;
        order: number;
      }>;
    }>;
  };
};

export type GetFormResponse = GetFormResponses[keyof GetFormResponses];

export type UpdateFormData = {
  body?: {
    title?: string;
    description?: string;
    template?: boolean;
    fields?: Array<{
      id?: string;
      title: string;
      type: 'text_answer' | 'multiple_select' | 'single_select';
      required?: boolean;
      order?: number;
      options?: Array<{
        id?: string;
        title: string;
        order?: number;
      }>;
    }>;
  };
  path: {
    id: string;
  };
  query?: never;
  url: '/api/forms/{id}';
};

export type UpdateFormErrors = {
  /**
   * Forbidden
   */
  403: unknown;
  /**
   * Form not found
   */
  404: unknown;
};

export type UpdateFormResponses = {
  /**
   * Success
   */
  200: unknown;
};

export type GetFormStatisticsData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/api/forms/{id}/statistics';
};

export type GetFormStatisticsErrors = {
  /**
   * Forbidden
   */
  403: unknown;
  /**
   * Form not found
   */
  404: unknown;
};

export type GetFormStatisticsResponses = {
  /**
   * Success
   */
  200: {
    id: string;
    title: string;
    resource_type: string;
    statistics: Array<{
      id: string;
      title: string;
      type: 'multiple_select' | 'single_select';
      required: boolean;
      options: Array<{
        id: string;
        title: string;
        answer_amount: number;
        answer_percentage: number;
      }>;
    }>;
  };
};

export type GetFormStatisticsResponse = GetFormStatisticsResponses[keyof GetFormStatisticsResponses];

export type ListFormSubmissionsData = {
  body?: never;
  path: {
    formId: string;
  };
  query?: never;
  url: '/api/forms/{formId}/submissions';
};

export type ListFormSubmissionsErrors = {
  /**
   * Forbidden
   */
  403: unknown;
  /**
   * Form not found
   */
  404: unknown;
};

export type ListFormSubmissionsResponses = {
  /**
   * Success
   */
  200: Array<{
    id: string;
    user: {
      id: string;
      name: string;
      email: string;
    };
    created_at: string;
    updated_at: string;
    answers: Array<{
      id: string;
      field_id: string | null;
      answer_text: string | null;
      selected_options: Array<{
        id: string;
        title: string;
      }>;
    }>;
  }>;
};

export type ListFormSubmissionsResponse = ListFormSubmissionsResponses[keyof ListFormSubmissionsResponses];

export type CreateFormSubmissionData = {
  body?: {
    answers: Array<{
      field: {
        id: string;
      };
      answer_text?: string;
      selected_options?: Array<{
        id: string;
      }>;
    }>;
  };
  path: {
    formId: string;
  };
  query?: never;
  url: '/api/forms/{formId}/submissions';
};

export type CreateFormSubmissionErrors = {
  /**
   * Forbidden - Cannot submit to this form
   */
  403: unknown;
  /**
   * Form not found
   */
  404: unknown;
  /**
   * Conflict - Duplicate submission not allowed
   */
  409: unknown;
};

export type CreateFormSubmissionResponses = {
  /**
   * Created
   */
  201: unknown;
};

export type GetFormSubmissionData = {
  body?: never;
  path: {
    formId: string;
    id: string;
  };
  query?: never;
  url: '/api/forms/{formId}/submissions/{id}';
};

export type GetFormSubmissionErrors = {
  /**
   * Forbidden
   */
  403: unknown;
  /**
   * Submission not found
   */
  404: unknown;
};

export type GetFormSubmissionResponses = {
  /**
   * Success
   */
  200: {
    id: string;
    user: {
      id: string;
      name: string;
      email: string;
    };
    created_at: string;
    updated_at: string;
    answers: Array<{
      id: string;
      field_id: string | null;
      answer_text: string | null;
      selected_options: Array<{
        id: string;
        title: string;
      }>;
    }>;
  };
};

export type GetFormSubmissionResponse = GetFormSubmissionResponses[keyof GetFormSubmissionResponses];

export type DownloadFormSubmissionsData = {
  body?: never;
  path: {
    formId: string;
  };
  query?: never;
  url: '/api/forms/{formId}/submissions/download';
};

export type DownloadFormSubmissionsErrors = {
  /**
   * Forbidden
   */
  403: unknown;
  /**
   * Form not found
   */
  404: unknown;
};

export type DownloadFormSubmissionsResponses = {
  /**
   * Success - Returns CSV file
   */
  200: unknown;
};

export type DeleteFormSubmissionData = {
  body?: {
    reason: string;
  };
  path: {
    formId: string;
    id: string;
  };
  query?: never;
  url: '/api/forms/{formId}/submissions/{id}/destroy_with_reason';
};

export type DeleteFormSubmissionErrors = {
  /**
   * Submission not found
   */
  404: unknown;
};

export type DeleteFormSubmissionResponses = {
  /**
   * Success
   */
  200: unknown;
};

export type ListNotificationsData = {
  body?: never;
  path?: never;
  query?: {
    limit?: number;
    offset?: number;
  };
  url: '/api/notification';
};

export type ListNotificationsErrors = {
  /**
   * Unauthorized - user not authenticated
   */
  401: unknown;
};

export type ListNotificationsResponses = {
  /**
   * OK
   */
  200: Array<{
    /**
     * Notification ID
     */
    id: string;
    /**
     * User ID
     */
    userId: string;
    /**
     * Notification title
     */
    title: string;
    /**
     * Notification description
     */
    description: string;
    /**
     * Optional link URL (nullable)
     */
    link: string | null;
    /**
     * Whether notification is read
     */
    isRead: boolean;
    /**
     * Notification creation time (ISO 8601)
     */
    createdAt: Date;
    /**
     * Notification update time (ISO 8601)
     */
    updatedAt: Date;
  }>;
};

export type ListNotificationsResponse = ListNotificationsResponses[keyof ListNotificationsResponses];

export type DeleteNotificationData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/api/notification/{id}';
};

export type DeleteNotificationErrors = {
  /**
   * Unauthorized - user not authenticated
   */
  401: unknown;
  /**
   * Notification not found or not owned by user
   */
  404: unknown;
};

export type DeleteNotificationResponses = {
  /**
   * Notification deleted successfully
   */
  200: {
    /**
     * Whether deletion was successful
     */
    success: boolean;
  };
};

export type DeleteNotificationResponse = DeleteNotificationResponses[keyof DeleteNotificationResponses];

export type MarkNotificationReadData = {
  body?: {
    /**
     * Whether notification should be marked as read
     */
    isRead: boolean;
  };
  path: {
    id: string;
  };
  query?: never;
  url: '/api/notification/{id}/read';
};

export type MarkNotificationReadErrors = {
  /**
   * Unauthorized - user not authenticated
   */
  401: unknown;
  /**
   * Notification not found or not owned by user
   */
  404: unknown;
};

export type MarkNotificationReadResponses = {
  /**
   * Notification updated successfully
   */
  200: {
    /**
     * Notification ID
     */
    id: string;
    /**
     * Updated read status
     */
    isRead: boolean;
    /**
     * Notification update time (ISO 8601)
     */
    updatedAt: Date;
  };
};

export type MarkNotificationReadResponse = MarkNotificationReadResponses[keyof MarkNotificationReadResponses];

export type ListGroupsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/groups';
};

export type ListGroupsResponses = {
  /**
   * List of groups retrieved successfully
   */
  200: Array<{
    /**
     * Group slug
     */
    slug: string;
    /**
     * Group image URL
     */
    imageUrl: string | null;
    /**
     * Group name
     */
    name: string;
    /**
     * Group description
     */
    description: string | null;
    /**
     * Group contact email
     */
    contactEmail: string | null;
    /**
     * Group type
     */
    type: string;
    /**
     * Group fines info
     */
    finesInfo: string;
    /**
     * Group fines activated
     */
    finesActivated: boolean;
    /**
     * Group fines admin ID
     */
    finesAdminId: string | null;
    /**
     * Creation timestamp
     */
    createdAt: string;
    /**
     * Last update timestamp
     */
    updatedAt: string;
  }>;
};

export type ListGroupsResponse = ListGroupsResponses[keyof ListGroupsResponses];

export type CreateGroupData = {
  body?: {
    /**
     * Unique group slug identifier
     */
    slug: string;
    /**
     * Group image URL
     */
    imageUrl?: string;
    /**
     * Group name
     */
    name: string;
    /**
     * Group description
     */
    description?: string;
    /**
     * Group contact email
     */
    contactEmail?: string;
    /**
     * Group type (e.g., committee, study, interestgroup)
     */
    type: string;
    /**
     * Information about group fines policy
     */
    finesInfo?: string;
    /**
     * Whether fines are activated for this group
     */
    finesActivated?: boolean;
    /**
     * User ID of the fines administrator
     */
    finesAdminId?: string;
  };
  path?: never;
  query?: never;
  url: '/api/groups';
};

export type CreateGroupErrors = {
  /**
   * Bad Request - Invalid input or slug already exists
   */
  400: unknown;
  /**
   * Forbidden - Missing groups:create permission
   */
  403: unknown;
};

export type CreateGroupResponses = {
  /**
   * Group created successfully
   */
  201: unknown;
};

export type DeleteGroupData = {
  body?: never;
  path: {
    slug: string;
  };
  query?: never;
  url: '/api/groups/{slug}';
};

export type DeleteGroupErrors = {
  /**
   * Forbidden - Not a group leader or missing groups:delete permission
   */
  403: unknown;
  /**
   * Not Found - Group with the specified slug does not exist
   */
  404: unknown;
};

export type DeleteGroupResponses = {
  /**
   * Group successfully deleted
   */
  204: void;
};

export type DeleteGroupResponse = DeleteGroupResponses[keyof DeleteGroupResponses];

export type GetGroupData = {
  body?: never;
  path: {
    slug: string;
  };
  query?: never;
  url: '/api/groups/{slug}';
};

export type GetGroupErrors = {
  /**
   * Not Found - Group with the specified slug does not exist
   */
  404: unknown;
};

export type GetGroupResponses = {
  /**
   * Group details retrieved successfully
   */
  200: {
    /**
     * Group slug
     */
    slug: string;
    /**
     * Group image URL
     */
    imageUrl: string | null;
    /**
     * Group name
     */
    name: string;
    /**
     * Group description
     */
    description: string | null;
    /**
     * Group contact email
     */
    contactEmail: string | null;
    /**
     * Group type
     */
    type: string;
    /**
     * Group fines info
     */
    finesInfo: string;
    /**
     * Group fines activated
     */
    finesActivated: boolean;
    /**
     * Group fines admin ID
     */
    finesAdminId: string | null;
    /**
     * Creation timestamp
     */
    createdAt: string;
    /**
     * Last update timestamp
     */
    updatedAt: string;
  };
};

export type GetGroupResponse = GetGroupResponses[keyof GetGroupResponses];

export type UpdateGroupData = {
  body?: {
    /**
     * Group image URL
     */
    imageUrl?: string;
    /**
     * Group name
     */
    name?: string;
    /**
     * Group description
     */
    description?: string | null;
    /**
     * Group contact email
     */
    contactEmail?: string | null;
    /**
     * Group type
     */
    type?: string;
    /**
     * Information about group fines policy
     */
    finesInfo?: string;
    /**
     * Whether fines are activated for this group
     */
    finesActivated?: boolean;
    /**
     * User ID of the fines administrator
     */
    finesAdminId?: string | null;
  };
  path: {
    slug: string;
  };
  query?: never;
  url: '/api/groups/{slug}';
};

export type UpdateGroupErrors = {
  /**
   * Bad Request - Invalid input
   */
  400: unknown;
  /**
   * Forbidden - Not a group leader or missing groups:update permission
   */
  403: unknown;
  /**
   * Not Found - Group with the specified slug does not exist
   */
  404: unknown;
};

export type UpdateGroupResponses = {
  /**
   * Group updated successfully
   */
  200: unknown;
};

export type ListFinesData = {
  body?: never;
  path: {
    groupSlug: string;
  };
  query?: never;
  url: '/api/groups/{groupSlug}/fines';
};

export type ListFinesErrors = {
  /**
   * Forbidden - Not authorized to view fines for this group
   */
  403: unknown;
  /**
   * Not Found - Group not found
   */
  404: unknown;
};

export type ListFinesResponses = {
  /**
   * List of fines retrieved successfully
   */
  200: Array<{
    /**
     * Fine ID
     */
    id: string;
    /**
     * User ID who received the fine
     */
    userId: string;
    /**
     * Group slug that issued the fine
     */
    groupSlug: string;
    /**
     * Reason for the fine
     */
    reason: string;
    /**
     * Fine amount in NOK
     */
    amount: number;
    /**
     * User's defense text
     */
    defense: string | null;
    /**
     * Fine status (pending, approved, paid, rejected)
     */
    status: string;
    /**
     * User who created the fine
     */
    createdByUserId: string | null;
    /**
     * User who approved the fine
     */
    approvedByUserId: string | null;
    /**
     * Approval timestamp
     */
    approvedAt: string | null;
    /**
     * Payment timestamp
     */
    paidAt: string | null;
    /**
     * Creation timestamp
     */
    createdAt: string;
    /**
     * Last update timestamp
     */
    updatedAt: string;
  }>;
};

export type ListFinesResponse = ListFinesResponses[keyof ListFinesResponses];

export type CreateFineData = {
  body?: {
    /**
     * User ID who receives the fine
     */
    userId: string;
    /**
     * Group slug that issues the fine
     */
    groupSlug: string;
    /**
     * Reason for the fine
     */
    reason: string;
    /**
     * Fine amount in NOK
     */
    amount: number;
    /**
     * User's defense text
     */
    defense?: string;
  };
  path: {
    groupSlug: string;
  };
  query?: never;
  url: '/api/groups/{groupSlug}/fines';
};

export type CreateFineErrors = {
  /**
   * Bad Request - Invalid input or fines not activated for group
   */
  400: unknown;
  /**
   * Forbidden - Not authorized to create fines for this group
   */
  403: unknown;
  /**
   * Not Found - Group or user not found
   */
  404: unknown;
};

export type CreateFineResponses = {
  /**
   * Fine created successfully
   */
  201: unknown;
};

export type DeleteFineData = {
  body?: never;
  path: {
    groupSlug: string;
    fineId: string;
  };
  query?: never;
  url: '/api/groups/{groupSlug}/fines/{fineId}';
};

export type DeleteFineErrors = {
  /**
   * Forbidden - Not authorized to delete this fine
   */
  403: unknown;
  /**
   * Not Found - Fine or group not found
   */
  404: unknown;
};

export type DeleteFineResponses = {
  /**
   * Fine successfully deleted
   */
  204: void;
};

export type DeleteFineResponse = DeleteFineResponses[keyof DeleteFineResponses];

export type GetFineData = {
  body?: never;
  path: {
    groupSlug: string;
    fineId: string;
  };
  query?: never;
  url: '/api/groups/{groupSlug}/fines/{fineId}';
};

export type GetFineErrors = {
  /**
   * Forbidden - Not authorized to view this fine
   */
  403: unknown;
  /**
   * Not Found - Fine or group not found
   */
  404: unknown;
};

export type GetFineResponses = {
  /**
   * Fine details retrieved successfully
   */
  200: {
    /**
     * Fine ID
     */
    id: string;
    /**
     * User ID who received the fine
     */
    userId: string;
    /**
     * Group slug that issued the fine
     */
    groupSlug: string;
    /**
     * Reason for the fine
     */
    reason: string;
    /**
     * Fine amount in NOK
     */
    amount: number;
    /**
     * User's defense text
     */
    defense: string | null;
    /**
     * Fine status (pending, approved, paid, rejected)
     */
    status: string;
    /**
     * User who created the fine
     */
    createdByUserId: string | null;
    /**
     * User who approved the fine
     */
    approvedByUserId: string | null;
    /**
     * Approval timestamp
     */
    approvedAt: string | null;
    /**
     * Payment timestamp
     */
    paidAt: string | null;
    /**
     * Creation timestamp
     */
    createdAt: string;
    /**
     * Last update timestamp
     */
    updatedAt: string;
  };
};

export type GetFineResponse = GetFineResponses[keyof GetFineResponses];

export type UpdateFineData = {
  body?: {
    /**
     * User's defense text
     */
    defense?: string;
    /**
     * Fine status
     */
    status?: 'pending' | 'approved' | 'paid' | 'rejected';
    /**
     * User who approved the fine
     */
    approvedByUserId?: string;
  };
  path: {
    groupSlug: string;
    fineId: string;
  };
  query?: never;
  url: '/api/groups/{groupSlug}/fines/{fineId}';
};

export type UpdateFineErrors = {
  /**
   * Bad Request - Invalid status transition
   */
  400: unknown;
  /**
   * Forbidden - Not authorized to update this fine
   */
  403: unknown;
  /**
   * Not Found - Fine or group not found
   */
  404: unknown;
};

export type UpdateFineResponses = {
  /**
   * Fine updated successfully
   */
  200: unknown;
};

export type ListGroupMembersData = {
  body?: never;
  path: {
    groupSlug: string;
  };
  query?: never;
  url: '/api/groups/{groupSlug}/members';
};

export type ListGroupMembersErrors = {
  /**
   * Not Found - Group not found
   */
  404: unknown;
};

export type ListGroupMembersResponses = {
  /**
   * List of members retrieved successfully
   */
  200: Array<{
    /**
     * User ID
     */
    userId: string;
    /**
     * Group slug
     */
    groupSlug: string;
    /**
     * Membership role
     */
    role: string;
    /**
     * Membership creation timestamp
     */
    createdAt: string;
    /**
     * Membership update timestamp
     */
    updatedAt: string;
  }>;
};

export type ListGroupMembersResponse = ListGroupMembersResponses[keyof ListGroupMembersResponses];

export type AddGroupMemberData = {
  body?: {
    /**
     * User ID to add as member
     */
    userId: string;
    /**
     * Membership role
     */
    role?: 'member' | 'leader';
  };
  path: {
    groupSlug: string;
  };
  query?: never;
  url: '/api/groups/{groupSlug}/members';
};

export type AddGroupMemberErrors = {
  /**
   * Bad Request - User already a member or user not found
   */
  400: unknown;
  /**
   * Forbidden - Missing groups:manage permission
   */
  403: unknown;
  /**
   * Not Found - Group not found
   */
  404: unknown;
};

export type AddGroupMemberResponses = {
  /**
   * Member added successfully
   */
  201: unknown;
};

export type RemoveGroupMemberData = {
  body?: never;
  path: {
    groupSlug: string;
    userId: string;
  };
  query?: never;
  url: '/api/groups/{groupSlug}/members/{userId}';
};

export type RemoveGroupMemberErrors = {
  /**
   * Forbidden - Missing groups:manage permission
   */
  403: unknown;
  /**
   * Not Found - Group, user, or membership not found
   */
  404: unknown;
};

export type RemoveGroupMemberResponses = {
  /**
   * Member removed successfully
   */
  204: void;
};

export type RemoveGroupMemberResponse = RemoveGroupMemberResponses[keyof RemoveGroupMemberResponses];

export type UpdateGroupMemberRoleData = {
  body?: {
    /**
     * Membership role
     */
    role: 'member' | 'leader';
  };
  path: {
    groupSlug: string;
    userId: string;
  };
  query?: never;
  url: '/api/groups/{groupSlug}/members/{userId}';
};

export type UpdateGroupMemberRoleErrors = {
  /**
   * Forbidden - Missing groups:manage permission
   */
  403: unknown;
  /**
   * Not Found - Group, user, or membership not found
   */
  404: unknown;
};

export type UpdateGroupMemberRoleResponses = {
  /**
   * Member role updated successfully
   */
  200: unknown;
};

export type ListGroupFormsData = {
  body?: never;
  path: {
    slug: string;
  };
  query?: never;
  url: '/api/groups/{slug}/forms';
};

export type ListGroupFormsErrors = {
  /**
   * Group not found
   */
  404: unknown;
};

export type ListGroupFormsResponses = {
  /**
   * Success
   */
  200: Array<{
    id: string;
    title: string;
    description: string | null;
    group: string;
    email_receiver_on_submit: string | null;
    can_submit_multiple: boolean;
    is_open_for_submissions: boolean;
    only_for_group_members: boolean;
    resource_type: string;
    viewer_has_answered: boolean;
    created_at: string;
    updated_at: string;
  }>;
};

export type ListGroupFormsResponse = ListGroupFormsResponses[keyof ListGroupFormsResponses];

export type CreateGroupFormData = {
  body?: {
    title: string;
    description?: string;
    template?: boolean;
    fields?: Array<{
      title: string;
      type: 'text_answer' | 'multiple_select' | 'single_select';
      required?: boolean;
      order?: number;
      options?: Array<{
        title: string;
        order?: number;
      }>;
    }>;
    group: string;
    email_receiver_on_submit?: string;
    can_submit_multiple?: boolean;
    is_open_for_submissions?: boolean;
    only_for_group_members?: boolean;
  };
  path: {
    slug: string;
  };
  query?: never;
  url: '/api/groups/{slug}/forms';
};

export type CreateGroupFormErrors = {
  /**
   * Forbidden
   */
  403: unknown;
  /**
   * Group not found
   */
  404: unknown;
};

export type CreateGroupFormResponses = {
  /**
   * Created
   */
  201: unknown;
};

export type ListNewsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/news';
};

export type ListNewsResponses = {
  /**
   * List of news articles
   */
  200: unknown;
};

export type CreateNewsData = {
  body?: {
    /**
     * News article title
     */
    title: string;
    /**
     * News article subtitle/ingress
     */
    header: string;
    /**
     * Main content of the news
     */
    body: string;
    /**
     * Optional image URL
     */
    imageUrl?: string;
    /**
     * Alt text for the image
     */
    imageAlt?: string;
    /**
     * Whether reactions are enabled
     */
    emojisAllowed?: boolean;
  };
  path?: never;
  query?: never;
  url: '/api/news';
};

export type CreateNewsErrors = {
  /**
   * Forbidden - Missing news:create permission
   */
  403: unknown;
};

export type CreateNewsResponses = {
  /**
   * News article created successfully
   */
  201: unknown;
};

export type DeleteNewsData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/api/news/{id}';
};

export type DeleteNewsErrors = {
  /**
   * Forbidden - Insufficient permissions
   */
  403: unknown;
  /**
   * News article not found
   */
  404: unknown;
};

export type DeleteNewsResponses = {
  /**
   * News article deleted successfully
   */
  200: unknown;
};

export type GetNewsData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/api/news/{id}';
};

export type GetNewsErrors = {
  /**
   * News article not found
   */
  404: unknown;
};

export type GetNewsResponses = {
  /**
   * News article details
   */
  200: unknown;
};

export type UpdateNewsData = {
  body?: {
    title?: string;
    header?: string;
    body?: string;
    imageUrl?: string | null;
    imageAlt?: string | null;
    emojisAllowed?: boolean;
  };
  path: {
    id: string;
  };
  query?: never;
  url: '/api/news/{id}';
};

export type UpdateNewsErrors = {
  /**
   * Forbidden - Insufficient permissions
   */
  403: unknown;
  /**
   * News article not found
   */
  404: unknown;
};

export type UpdateNewsResponses = {
  /**
   * News article updated successfully
   */
  200: unknown;
};

export type DeleteNewsReactionData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/api/news/{id}/reactions';
};

export type DeleteNewsReactionErrors = {
  /**
   * News article or reaction not found
   */
  404: unknown;
};

export type DeleteNewsReactionResponses = {
  /**
   * Reaction removed successfully
   */
  200: unknown;
};

export type CreateNewsReactionData = {
  body?: {
    /**
     * Emoji reaction (e.g., 👍, ❤️, 😂)
     */
    emoji: string;
  };
  path: {
    id: string;
  };
  query?: never;
  url: '/api/news/{id}/reactions';
};

export type CreateNewsReactionErrors = {
  /**
   * Forbidden - Reactions not allowed on this news article
   */
  403: unknown;
  /**
   * News article not found
   */
  404: unknown;
};

export type CreateNewsReactionResponses = {
  /**
   * Reaction added successfully
   */
  201: unknown;
};

export type ListJobsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/jobs';
};

export type ListJobsResponses = {
  /**
   * List of job postings
   */
  200: unknown;
};

export type CreateJobData = {
  body?: {
    /**
     * Job posting title
     */
    title: string;
    /**
     * Short description/summary
     */
    ingress?: string;
    /**
     * Full job description
     */
    body?: string;
    /**
     * Company name
     */
    company: string;
    /**
     * Job location
     */
    location: string;
    /**
     * Application deadline
     */
    deadline?: Date;
    /**
     * Whether hiring is ongoing
     */
    isContinuouslyHiring?: boolean;
    /**
     * Type of employment
     */
    jobType?: 'full_time' | 'part_time' | 'summer_job' | 'other';
    /**
     * Contact email
     */
    email?: string;
    /**
     * Application or company URL
     */
    link?: string;
    /**
     * Target class start
     */
    classStart?: 'first' | 'second' | 'third' | 'fourth' | 'fifth' | 'alumni';
    /**
     * Target class end
     */
    classEnd?: 'first' | 'second' | 'third' | 'fourth' | 'fifth' | 'alumni';
    /**
     * Company logo
     */
    imageUrl?: string;
    /**
     * Logo alt text
     */
    imageAlt?: string;
  };
  path?: never;
  query?: never;
  url: '/api/jobs';
};

export type CreateJobErrors = {
  /**
   * Bad Request - Invalid input
   */
  400: unknown;
  /**
   * Forbidden - Missing jobs:create permission
   */
  403: unknown;
};

export type CreateJobResponses = {
  /**
   * Job posting created successfully
   */
  201: unknown;
};

export type DeleteJobData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/api/jobs/{id}';
};

export type DeleteJobErrors = {
  /**
   * Forbidden - Insufficient permissions
   */
  403: unknown;
  /**
   * Job posting not found
   */
  404: unknown;
};

export type DeleteJobResponses = {
  /**
   * Job posting deleted successfully
   */
  200: unknown;
};

export type GetJobData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/api/jobs/{id}';
};

export type GetJobErrors = {
  /**
   * Job posting not found
   */
  404: unknown;
};

export type GetJobResponses = {
  /**
   * Job posting details
   */
  200: unknown;
};

export type UpdateJobData = {
  body?: {
    title?: string;
    ingress?: string;
    body?: string;
    company?: string;
    location?: string;
    deadline?: Date | null;
    isContinuouslyHiring?: boolean;
    jobType?: 'full_time' | 'part_time' | 'summer_job' | 'other';
    email?: string | null;
    link?: string | null;
    classStart?: 'first' | 'second' | 'third' | 'fourth' | 'fifth' | 'alumni';
    classEnd?: 'first' | 'second' | 'third' | 'fourth' | 'fifth' | 'alumni';
    imageUrl?: string | null;
    imageAlt?: string | null;
  };
  path: {
    id: string;
  };
  query?: never;
  url: '/api/jobs/{id}';
};

export type UpdateJobErrors = {
  /**
   * Forbidden - Insufficient permissions
   */
  403: unknown;
  /**
   * Job posting not found
   */
  404: unknown;
};

export type UpdateJobResponses = {
  /**
   * Job posting updated successfully
   */
  200: unknown;
};

export type GetUserSettingsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/user/me/settings';
};

export type GetUserSettingsErrors = {
  /**
   * Not Found - User settings do not exist (user needs to complete onboarding)
   */
  404: unknown;
};

export type GetUserSettingsResponses = {
  /**
   * User settings retrieved successfully
   */
  200: {
    gender: 'male' | 'female' | 'other';
    allowsPhotosByDefault: boolean;
    acceptsEventRules: boolean;
    imageUrl?: string;
    bioDescription?: string;
    githubUrl?: string;
    linkedinUrl?: string;
    receiveMailCommunication: boolean;
    allergies?: Array<string>;
    /**
     * Whether the user has completed onboarding
     */
    isOnboarded: boolean;
  };
};

export type GetUserSettingsResponse = GetUserSettingsResponses[keyof GetUserSettingsResponses];

export type UpdateUserSettingsData = {
  body?: {
    gender?: 'male' | 'female' | 'other';
    allowsPhotosByDefault?: boolean;
    acceptsEventRules?: boolean;
    imageUrl?: string;
    bioDescription?: string;
    githubUrl?: string;
    linkedinUrl?: string;
    receiveMailCommunication?: boolean;
    allergies?: Array<string>;
  };
  path?: never;
  query?: never;
  url: '/api/user/me/settings';
};

export type UpdateUserSettingsErrors = {
  /**
   * Bad Request - Invalid input
   */
  400: unknown;
  /**
   * Not Found - User settings do not exist (user needs to complete onboarding first)
   */
  404: unknown;
};

export type UpdateUserSettingsResponses = {
  /**
   * Settings updated successfully
   */
  200: {
    gender?: 'male' | 'female' | 'other';
    allowsPhotosByDefault?: boolean;
    acceptsEventRules?: boolean;
    imageUrl?: string;
    bioDescription?: string;
    githubUrl?: string;
    linkedinUrl?: string;
    receiveMailCommunication?: boolean;
    allergies?: Array<string>;
  };
};

export type UpdateUserSettingsResponse = UpdateUserSettingsResponses[keyof UpdateUserSettingsResponses];

export type OnboardUserData = {
  body?: {
    gender: 'male' | 'female' | 'other';
    allowsPhotosByDefault: boolean;
    acceptsEventRules: boolean;
    imageUrl?: string;
    bioDescription?: string;
    githubUrl?: string;
    linkedinUrl?: string;
    receiveMailCommunication: boolean;
    allergies?: Array<string>;
  };
  path?: never;
  query?: never;
  url: '/api/user/me/settings';
};

export type OnboardUserErrors = {
  /**
   * Bad Request - User has already completed onboarding
   */
  400: unknown;
};

export type OnboardUserResponses = {
  /**
   * User onboarded successfully
   */
  201: {
    gender: 'male' | 'female' | 'other';
    allowsPhotosByDefault: boolean;
    acceptsEventRules: boolean;
    imageUrl?: string;
    bioDescription?: string;
    githubUrl?: string;
    linkedinUrl?: string;
    receiveMailCommunication: boolean;
    allergies?: Array<string>;
  };
};

export type OnboardUserResponse = OnboardUserResponses[keyof OnboardUserResponses];

export type ListAllergiesData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/user/allergy';
};

export type ListAllergiesResponses = {
  /**
   * List of allergies retrieved successfully
   */
  200: Array<{
    /**
     * Unique identifier for the allergy
     */
    slug: string;
    /**
     * Display name of the allergy
     */
    label: string;
    /**
     * Detailed description of the allergy
     */
    description: string | null;
  }>;
};

export type ListAllergiesResponse = ListAllergiesResponses[keyof ListAllergiesResponses];
