contact_links:
  - name: Join our Slack
    url: https://tihlde.slack.com/
    about: Ask questions and get support
  - name: Contact
    url: https://tihlde.org/om/kontakt-oss/
    about: Different ways of contacting TIHLDE
