// This file is auto-generated by @hey-api/openapi-ts

import { infiniteQueryOptions, queryOptions, type DefaultError, type InfiniteData, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import {
  deleteApiApiKeysId,
  deleteApiEventEventId,
  deleteApiEventEventIdRegistration,
  deleteApiFormsFormIdSubmissionsIdDestroyWithReason,
  deleteApiFormsId,
  deleteApiGroupsGroupSlugFinesFineId,
  deleteApiGroupsGroupSlugMembersUserId,
  deleteApiGroupsSlug,
  deleteApiJobsId,
  deleteApiNewsId,
  deleteApiNewsIdReactions,
  deleteApiNotificationId,
  getApiApiKeys,
  getApiApiKeysId,
  getApiEvent,
  getApiEventEventIdForms,
  getApiEventEventIdFormsType,
  getApiEventEventIdRegistration,
  getApiEventFavorite,
  getApiForms,
  getApiFormsFormIdSubmissions,
  getApiFormsFormIdSubmissionsDownload,
  getApiFormsFormIdSubmissionsId,
  getApiFormsId,
  getApiFormsIdStatistics,
  getApiGroups,
  getApiGroupsGroupSlugFines,
  getApiGroupsGroupSlugFinesFineId,
  getApiGroupsGroupSlugMembers,
  getApiGroupsSlug,
  getApiGroupsSlugForms,
  getApiJobs,
  getApiJobsId,
  getApiNews,
  getApiNewsId,
  getApiNotification,
  getApiUserAllergy,
  getApiUserMeSettings,
  patchApiApiKeysId,
  patchApiFormsId,
  patchApiGroupsGroupSlugFinesFineId,
  patchApiGroupsGroupSlugMembersUserId,
  patchApiGroupsSlug,
  patchApiJobsId,
  patchApiNewsId,
  patchApiNotificationIdRead,
  patchApiUserMeSettings,
  postApiApiKeys,
  postApiApiKeysIdRegenerate,
  postApiApiKeysValidate,
  postApiEmailSend,
  postApiEvent,
  postApiEventEventIdForms,
  postApiEventEventIdPayment,
  postApiEventEventIdRegistration,
  postApiEventPaymentWebhook,
  postApiForms,
  postApiFormsFormIdSubmissions,
  postApiGroups,
  postApiGroupsGroupSlugFines,
  postApiGroupsGroupSlugMembers,
  postApiGroupsSlugForms,
  postApiJobs,
  postApiNews,
  postApiNewsIdReactions,
  postApiUserMeSettings,
  putApiEventFavoriteId,
  putApiEventId,
  type Options,
} from '../sdk.gen';
import type {
  DeleteApiApiKeysIdData,
  DeleteApiApiKeysIdResponse,
  DeleteApiEventEventIdData,
  DeleteApiEventEventIdRegistrationData,
  DeleteApiEventEventIdRegistrationResponse,
  DeleteApiFormsFormIdSubmissionsIdDestroyWithReasonData,
  DeleteApiFormsIdData,
  DeleteApiGroupsGroupSlugFinesFineIdData,
  DeleteApiGroupsGroupSlugFinesFineIdResponse,
  DeleteApiGroupsGroupSlugMembersUserIdData,
  DeleteApiGroupsGroupSlugMembersUserIdResponse,
  DeleteApiGroupsSlugData,
  DeleteApiGroupsSlugResponse,
  DeleteApiJobsIdData,
  DeleteApiNewsIdData,
  DeleteApiNewsIdReactionsData,
  DeleteApiNotificationIdData,
  DeleteApiNotificationIdResponse,
  GetApiApiKeysData,
  GetApiApiKeysIdData,
  GetApiApiKeysIdResponse,
  GetApiApiKeysResponse,
  GetApiEventData,
  GetApiEventEventIdFormsData,
  GetApiEventEventIdFormsResponse,
  GetApiEventEventIdFormsTypeData,
  GetApiEventEventIdFormsTypeResponse,
  GetApiEventEventIdRegistrationData,
  GetApiEventEventIdRegistrationResponse,
  GetApiEventFavoriteData,
  GetApiEventFavoriteResponse,
  GetApiEventResponse,
  GetApiFormsData,
  GetApiFormsFormIdSubmissionsData,
  GetApiFormsFormIdSubmissionsDownloadData,
  GetApiFormsFormIdSubmissionsIdData,
  GetApiFormsFormIdSubmissionsIdResponse,
  GetApiFormsFormIdSubmissionsResponse,
  GetApiFormsIdData,
  GetApiFormsIdResponse,
  GetApiFormsIdStatisticsData,
  GetApiFormsIdStatisticsResponse,
  GetApiFormsResponse,
  GetApiGroupsData,
  GetApiGroupsGroupSlugFinesData,
  GetApiGroupsGroupSlugFinesFineIdData,
  GetApiGroupsGroupSlugFinesFineIdResponse,
  GetApiGroupsGroupSlugFinesResponse,
  GetApiGroupsGroupSlugMembersData,
  GetApiGroupsGroupSlugMembersResponse,
  GetApiGroupsResponse,
  GetApiGroupsSlugData,
  GetApiGroupsSlugFormsData,
  GetApiGroupsSlugFormsResponse,
  GetApiGroupsSlugResponse,
  GetApiJobsData,
  GetApiJobsIdData,
  GetApiNewsData,
  GetApiNewsIdData,
  GetApiNotificationData,
  GetApiNotificationResponse,
  GetApiUserAllergyData,
  GetApiUserAllergyResponse,
  GetApiUserMeSettingsData,
  GetApiUserMeSettingsResponse,
  PatchApiApiKeysIdData,
  PatchApiApiKeysIdResponse,
  PatchApiFormsIdData,
  PatchApiGroupsGroupSlugFinesFineIdData,
  PatchApiGroupsGroupSlugMembersUserIdData,
  PatchApiGroupsSlugData,
  PatchApiJobsIdData,
  PatchApiNewsIdData,
  PatchApiNotificationIdReadData,
  PatchApiNotificationIdReadResponse,
  PatchApiUserMeSettingsData,
  PatchApiUserMeSettingsResponse,
  PostApiApiKeysData,
  PostApiApiKeysIdRegenerateData,
  PostApiApiKeysIdRegenerateResponse,
  PostApiApiKeysResponse,
  PostApiApiKeysValidateData,
  PostApiApiKeysValidateResponse,
  PostApiEmailSendData,
  PostApiEmailSendResponse,
  PostApiEventData,
  PostApiEventEventIdFormsData,
  PostApiEventEventIdPaymentData,
  PostApiEventEventIdPaymentResponse,
  PostApiEventEventIdRegistrationData,
  PostApiEventEventIdRegistrationResponse,
  PostApiEventPaymentWebhookData,
  PostApiEventResponse,
  PostApiFormsData,
  PostApiFormsFormIdSubmissionsData,
  PostApiFormsResponse,
  PostApiGroupsData,
  PostApiGroupsGroupSlugFinesData,
  PostApiGroupsGroupSlugMembersData,
  PostApiGroupsSlugFormsData,
  PostApiJobsData,
  PostApiNewsData,
  PostApiNewsIdReactionsData,
  PostApiUserMeSettingsData,
  PostApiUserMeSettingsResponse,
  PutApiEventFavoriteIdData,
  PutApiEventIdData,
} from '../types.gen';

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
    _id: string;
    _infinite?: boolean;
    tags?: ReadonlyArray<string>;
  },
];

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
  tags?: ReadonlyArray<string>,
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (tags) {
    params.tags = tags;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return [params];
};

export const getApiApiKeysQueryKey = (options?: Options<GetApiApiKeysData>) => createQueryKey('getApiApiKeys', options);

/**
 * List API keys
 *
 * Get a list of all API keys. Does not include the full key values. Requires 'api-keys:view' permission.
 */
export const getApiApiKeysOptions = (options?: Options<GetApiApiKeysData>) =>
  queryOptions<GetApiApiKeysResponse, DefaultError, GetApiApiKeysResponse, ReturnType<typeof getApiApiKeysQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiApiKeys({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getApiApiKeysQueryKey(options),
  });

/**
 * Create API key
 *
 * Create a new API key. The full key is returned only once and cannot be retrieved again. Requires 'api-keys:create' permission.
 */
export const postApiApiKeysMutation = (
  options?: Partial<Options<PostApiApiKeysData>>,
): UseMutationOptions<PostApiApiKeysResponse, DefaultError, Options<PostApiApiKeysData>> => {
  const mutationOptions: UseMutationOptions<PostApiApiKeysResponse, DefaultError, Options<PostApiApiKeysData>> = {
    mutationFn: async (fnOptions) => {
      const { data } = await postApiApiKeys({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Delete API key
 *
 * Delete an API key. This action is irreversible. Requires 'api-keys:delete' permission.
 */
export const deleteApiApiKeysIdMutation = (
  options?: Partial<Options<DeleteApiApiKeysIdData>>,
): UseMutationOptions<DeleteApiApiKeysIdResponse, DefaultError, Options<DeleteApiApiKeysIdData>> => {
  const mutationOptions: UseMutationOptions<DeleteApiApiKeysIdResponse, DefaultError, Options<DeleteApiApiKeysIdData>> = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteApiApiKeysId({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getApiApiKeysIdQueryKey = (options: Options<GetApiApiKeysIdData>) => createQueryKey('getApiApiKeysId', options);

/**
 * Get API key
 *
 * Get a single API key by ID. Does not include the full key value. Requires 'api-keys:view' permission.
 */
export const getApiApiKeysIdOptions = (options: Options<GetApiApiKeysIdData>) =>
  queryOptions<GetApiApiKeysIdResponse, DefaultError, GetApiApiKeysIdResponse, ReturnType<typeof getApiApiKeysIdQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiApiKeysId({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getApiApiKeysIdQueryKey(options),
  });

/**
 * Update API key
 *
 * Update an API key's metadata (name, description, permissions, metadata). Cannot update the key itself - use regenerate for that. Requires 'api-keys:update' permission.
 */
export const patchApiApiKeysIdMutation = (
  options?: Partial<Options<PatchApiApiKeysIdData>>,
): UseMutationOptions<PatchApiApiKeysIdResponse, DefaultError, Options<PatchApiApiKeysIdData>> => {
  const mutationOptions: UseMutationOptions<PatchApiApiKeysIdResponse, DefaultError, Options<PatchApiApiKeysIdData>> = {
    mutationFn: async (fnOptions) => {
      const { data } = await patchApiApiKeysId({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Regenerate API key
 *
 * Generate a new key value for an existing API key. The old key will be invalidated. The new full key is returned only once and cannot be retrieved again. Requires 'api-keys:update' permission.
 */
export const postApiApiKeysIdRegenerateMutation = (
  options?: Partial<Options<PostApiApiKeysIdRegenerateData>>,
): UseMutationOptions<PostApiApiKeysIdRegenerateResponse, DefaultError, Options<PostApiApiKeysIdRegenerateData>> => {
  const mutationOptions: UseMutationOptions<PostApiApiKeysIdRegenerateResponse, DefaultError, Options<PostApiApiKeysIdRegenerateData>> = {
    mutationFn: async (fnOptions) => {
      const { data } = await postApiApiKeysIdRegenerate({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Validate API key
 *
 * Check if an API key is valid and return its details. This is a public endpoint that does not require authentication. Updates the lastUsedAt timestamp if the key is valid.
 */
export const postApiApiKeysValidateMutation = (
  options?: Partial<Options<PostApiApiKeysValidateData>>,
): UseMutationOptions<PostApiApiKeysValidateResponse, DefaultError, Options<PostApiApiKeysValidateData>> => {
  const mutationOptions: UseMutationOptions<PostApiApiKeysValidateResponse, DefaultError, Options<PostApiApiKeysValidateData>> = {
    mutationFn: async (fnOptions) => {
      const { data } = await postApiApiKeysValidate({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Send custom email
 *
 * Send a custom email with structured content blocks. Requires API key authentication via Bearer token.
 */
export const postApiEmailSendMutation = (
  options?: Partial<Options<PostApiEmailSendData>>,
): UseMutationOptions<PostApiEmailSendResponse, DefaultError, Options<PostApiEmailSendData>> => {
  const mutationOptions: UseMutationOptions<PostApiEmailSendResponse, DefaultError, Options<PostApiEmailSendData>> = {
    mutationFn: async (fnOptions) => {
      const { data } = await postApiEmailSend({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getApiEventQueryKey = (options?: Options<GetApiEventData>) => createQueryKey('getApiEvent', options);

/**
 * List events
 */
export const getApiEventOptions = (options?: Options<GetApiEventData>) =>
  queryOptions<GetApiEventResponse, DefaultError, GetApiEventResponse, ReturnType<typeof getApiEventQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiEvent({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getApiEventQueryKey(options),
  });

const createInfiniteParams = <K extends Pick<QueryKey<Options>[0], 'body' | 'headers' | 'path' | 'query'>>(queryKey: QueryKey<Options>, page: K) => {
  const params = {
    ...queryKey[0],
  };
  if (page.body) {
    params.body = {
      ...(queryKey[0].body as any),
      ...(page.body as any),
    };
  }
  if (page.headers) {
    params.headers = {
      ...queryKey[0].headers,
      ...page.headers,
    };
  }
  if (page.path) {
    params.path = {
      ...(queryKey[0].path as any),
      ...(page.path as any),
    };
  }
  if (page.query) {
    params.query = {
      ...(queryKey[0].query as any),
      ...(page.query as any),
    };
  }
  return params as unknown as typeof page;
};

export const getApiEventInfiniteQueryKey = (options?: Options<GetApiEventData>): QueryKey<Options<GetApiEventData>> =>
  createQueryKey('getApiEvent', options, true);

/**
 * List events
 */
export const getApiEventInfiniteOptions = (options?: Options<GetApiEventData>) => {
  return infiniteQueryOptions<
    GetApiEventResponse,
    DefaultError,
    InfiniteData<GetApiEventResponse>,
    QueryKey<Options<GetApiEventData>>,
    number | Pick<QueryKey<Options<GetApiEventData>>[0], 'body' | 'headers' | 'path' | 'query'>
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<QueryKey<Options<GetApiEventData>>[0], 'body' | 'headers' | 'path' | 'query'> =
          typeof pageParam === 'object'
            ? pageParam
            : {
                query: {
                  offset: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getApiEvent({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: getApiEventInfiniteQueryKey(options),
    },
  );
};

/**
 * Create event
 *
 * Create a new event. Requires 'events:create' permission.
 */
export const postApiEventMutation = (
  options?: Partial<Options<PostApiEventData>>,
): UseMutationOptions<PostApiEventResponse, DefaultError, Options<PostApiEventData>> => {
  const mutationOptions: UseMutationOptions<PostApiEventResponse, DefaultError, Options<PostApiEventData>> = {
    mutationFn: async (fnOptions) => {
      const { data } = await postApiEvent({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Update event
 *
 * Update an event by its ID. Event creators can update their own events. Users with 'events:update' or 'events:manage' permission can update any event.
 */
export const putApiEventIdMutation = (options?: Partial<Options<PutApiEventIdData>>): UseMutationOptions<unknown, DefaultError, Options<PutApiEventIdData>> => {
  const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<PutApiEventIdData>> = {
    mutationFn: async (fnOptions) => {
      const { data } = await putApiEventId({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Delete an event
 *
 * Delete an event by its ID. Event creators can delete their own events. Users with 'events:delete' permission can delete any event. This action is irreversible and will remove all associated data, including registrations and feedback.
 */
export const deleteApiEventEventIdMutation = (
  options?: Partial<Options<DeleteApiEventEventIdData>>,
): UseMutationOptions<unknown, DefaultError, Options<DeleteApiEventEventIdData>> => {
  const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<DeleteApiEventEventIdData>> = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteApiEventEventId({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Update event favorite
 */
export const putApiEventFavoriteIdMutation = (
  options?: Partial<Options<PutApiEventFavoriteIdData>>,
): UseMutationOptions<unknown, DefaultError, Options<PutApiEventFavoriteIdData>> => {
  const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<PutApiEventFavoriteIdData>> = {
    mutationFn: async (fnOptions) => {
      const { data } = await putApiEventFavoriteId({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getApiEventFavoriteQueryKey = (options?: Options<GetApiEventFavoriteData>) => createQueryKey('getApiEventFavorite', options);

/**
 * Get all my favorite events
 */
export const getApiEventFavoriteOptions = (options?: Options<GetApiEventFavoriteData>) =>
  queryOptions<GetApiEventFavoriteResponse, DefaultError, GetApiEventFavoriteResponse, ReturnType<typeof getApiEventFavoriteQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiEventFavorite({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getApiEventFavoriteQueryKey(options),
  });

/**
 * Unregister from event
 */
export const deleteApiEventEventIdRegistrationMutation = (
  options?: Partial<Options<DeleteApiEventEventIdRegistrationData>>,
): UseMutationOptions<DeleteApiEventEventIdRegistrationResponse, DefaultError, Options<DeleteApiEventEventIdRegistrationData>> => {
  const mutationOptions: UseMutationOptions<DeleteApiEventEventIdRegistrationResponse, DefaultError, Options<DeleteApiEventEventIdRegistrationData>> = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteApiEventEventIdRegistration({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getApiEventEventIdRegistrationQueryKey = (options: Options<GetApiEventEventIdRegistrationData>) =>
  createQueryKey('getApiEventEventIdRegistration', options);

/**
 * Get event registrations
 */
export const getApiEventEventIdRegistrationOptions = (options: Options<GetApiEventEventIdRegistrationData>) =>
  queryOptions<
    GetApiEventEventIdRegistrationResponse,
    DefaultError,
    GetApiEventEventIdRegistrationResponse,
    ReturnType<typeof getApiEventEventIdRegistrationQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiEventEventIdRegistration({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getApiEventEventIdRegistrationQueryKey(options),
  });

export const getApiEventEventIdRegistrationInfiniteQueryKey = (
  options: Options<GetApiEventEventIdRegistrationData>,
): QueryKey<Options<GetApiEventEventIdRegistrationData>> => createQueryKey('getApiEventEventIdRegistration', options, true);

/**
 * Get event registrations
 */
export const getApiEventEventIdRegistrationInfiniteOptions = (options: Options<GetApiEventEventIdRegistrationData>) => {
  return infiniteQueryOptions<
    GetApiEventEventIdRegistrationResponse,
    DefaultError,
    InfiniteData<GetApiEventEventIdRegistrationResponse>,
    QueryKey<Options<GetApiEventEventIdRegistrationData>>,
    number | Pick<QueryKey<Options<GetApiEventEventIdRegistrationData>>[0], 'body' | 'headers' | 'path' | 'query'>
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<QueryKey<Options<GetApiEventEventIdRegistrationData>>[0], 'body' | 'headers' | 'path' | 'query'> =
          typeof pageParam === 'object'
            ? pageParam
            : {
                query: {
                  offset: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getApiEventEventIdRegistration({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: getApiEventEventIdRegistrationInfiniteQueryKey(options),
    },
  );
};

/**
 * Register to an event
 */
export const postApiEventEventIdRegistrationMutation = (
  options?: Partial<Options<PostApiEventEventIdRegistrationData>>,
): UseMutationOptions<PostApiEventEventIdRegistrationResponse, DefaultError, Options<PostApiEventEventIdRegistrationData>> => {
  const mutationOptions: UseMutationOptions<PostApiEventEventIdRegistrationResponse, DefaultError, Options<PostApiEventEventIdRegistrationData>> = {
    mutationFn: async (fnOptions) => {
      const { data } = await postApiEventEventIdRegistration({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Create payment for event
 *
 * Initiates a Vipps payment for an event registration. User must have a registered status for the event.
 */
export const postApiEventEventIdPaymentMutation = (
  options?: Partial<Options<PostApiEventEventIdPaymentData>>,
): UseMutationOptions<PostApiEventEventIdPaymentResponse, DefaultError, Options<PostApiEventEventIdPaymentData>> => {
  const mutationOptions: UseMutationOptions<PostApiEventEventIdPaymentResponse, DefaultError, Options<PostApiEventEventIdPaymentData>> = {
    mutationFn: async (fnOptions) => {
      const { data } = await postApiEventEventIdPayment({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Vipps payment webhook
 *
 * Webhook endpoint for Vipps to notify about payment status changes. Updates payment record based on Vipps payment state.
 */
export const postApiEventPaymentWebhookMutation = (
  options?: Partial<Options<PostApiEventPaymentWebhookData>>,
): UseMutationOptions<unknown, DefaultError, Options<PostApiEventPaymentWebhookData>> => {
  const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<PostApiEventPaymentWebhookData>> = {
    mutationFn: async (fnOptions) => {
      const { data } = await postApiEventPaymentWebhook({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getApiEventEventIdFormsQueryKey = (options: Options<GetApiEventEventIdFormsData>) => createQueryKey('getApiEventEventIdForms', options);

/**
 * List event forms
 *
 * Get all forms (survey and evaluation) for an event
 */
export const getApiEventEventIdFormsOptions = (options: Options<GetApiEventEventIdFormsData>) =>
  queryOptions<GetApiEventEventIdFormsResponse, DefaultError, GetApiEventEventIdFormsResponse, ReturnType<typeof getApiEventEventIdFormsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiEventEventIdForms({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getApiEventEventIdFormsQueryKey(options),
  });

/**
 * Create event form
 *
 * Create a survey or evaluation form for an event. Requires event write permission.
 */
export const postApiEventEventIdFormsMutation = (
  options?: Partial<Options<PostApiEventEventIdFormsData>>,
): UseMutationOptions<unknown, DefaultError, Options<PostApiEventEventIdFormsData>> => {
  const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<PostApiEventEventIdFormsData>> = {
    mutationFn: async (fnOptions) => {
      const { data } = await postApiEventEventIdForms({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getApiEventEventIdFormsTypeQueryKey = (options: Options<GetApiEventEventIdFormsTypeData>) =>
  createQueryKey('getApiEventEventIdFormsType', options);

/**
 * Get event form
 *
 * Get a specific form (survey or evaluation) for an event with all fields and options
 */
export const getApiEventEventIdFormsTypeOptions = (options: Options<GetApiEventEventIdFormsTypeData>) =>
  queryOptions<GetApiEventEventIdFormsTypeResponse, DefaultError, GetApiEventEventIdFormsTypeResponse, ReturnType<typeof getApiEventEventIdFormsTypeQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiEventEventIdFormsType({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getApiEventEventIdFormsTypeQueryKey(options),
  });

export const getApiFormsQueryKey = (options?: Options<GetApiFormsData>) => createQueryKey('getApiForms', options);

/**
 * List forms
 *
 * List all form templates by default. Use ?all=true to include all forms. Returns template forms by default.
 */
export const getApiFormsOptions = (options?: Options<GetApiFormsData>) =>
  queryOptions<GetApiFormsResponse, DefaultError, GetApiFormsResponse, ReturnType<typeof getApiFormsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiForms({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getApiFormsQueryKey(options),
  });

/**
 * Create form
 *
 * Create a new base form template. Requires 'forms:create' permission.
 */
export const postApiFormsMutation = (
  options?: Partial<Options<PostApiFormsData>>,
): UseMutationOptions<PostApiFormsResponse, DefaultError, Options<PostApiFormsData>> => {
  const mutationOptions: UseMutationOptions<PostApiFormsResponse, DefaultError, Options<PostApiFormsData>> = {
    mutationFn: async (fnOptions) => {
      const { data } = await postApiForms({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Delete form
 *
 * Delete a form and all associated data. Requires permission to manage the form.
 */
export const deleteApiFormsIdMutation = (
  options?: Partial<Options<DeleteApiFormsIdData>>,
): UseMutationOptions<unknown, DefaultError, Options<DeleteApiFormsIdData>> => {
  const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<DeleteApiFormsIdData>> = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteApiFormsId({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getApiFormsIdQueryKey = (options: Options<GetApiFormsIdData>) => createQueryKey('getApiFormsId', options);

/**
 * Get form
 *
 * Get a form by ID with all fields and options
 */
export const getApiFormsIdOptions = (options: Options<GetApiFormsIdData>) =>
  queryOptions<GetApiFormsIdResponse, DefaultError, GetApiFormsIdResponse, ReturnType<typeof getApiFormsIdQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiFormsId({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getApiFormsIdQueryKey(options),
  });

/**
 * Update form
 *
 * Update a form. Requires permission to manage the form.
 */
export const patchApiFormsIdMutation = (
  options?: Partial<Options<PatchApiFormsIdData>>,
): UseMutationOptions<unknown, DefaultError, Options<PatchApiFormsIdData>> => {
  const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<PatchApiFormsIdData>> = {
    mutationFn: async (fnOptions) => {
      const { data } = await patchApiFormsId({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getApiFormsIdStatisticsQueryKey = (options: Options<GetApiFormsIdStatisticsData>) => createQueryKey('getApiFormsIdStatistics', options);

/**
 * Get form statistics
 *
 * Get aggregated statistics for a form. Requires permission to manage the form.
 */
export const getApiFormsIdStatisticsOptions = (options: Options<GetApiFormsIdStatisticsData>) =>
  queryOptions<GetApiFormsIdStatisticsResponse, DefaultError, GetApiFormsIdStatisticsResponse, ReturnType<typeof getApiFormsIdStatisticsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiFormsIdStatistics({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getApiFormsIdStatisticsQueryKey(options),
  });

export const getApiFormsFormIdSubmissionsQueryKey = (options: Options<GetApiFormsFormIdSubmissionsData>) =>
  createQueryKey('getApiFormsFormIdSubmissions', options);

/**
 * List submissions
 *
 * List all submissions for a form. Requires permission to manage the form.
 */
export const getApiFormsFormIdSubmissionsOptions = (options: Options<GetApiFormsFormIdSubmissionsData>) =>
  queryOptions<
    GetApiFormsFormIdSubmissionsResponse,
    DefaultError,
    GetApiFormsFormIdSubmissionsResponse,
    ReturnType<typeof getApiFormsFormIdSubmissionsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiFormsFormIdSubmissions({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getApiFormsFormIdSubmissionsQueryKey(options),
  });

/**
 * Create submission
 *
 * Submit answers to a form
 */
export const postApiFormsFormIdSubmissionsMutation = (
  options?: Partial<Options<PostApiFormsFormIdSubmissionsData>>,
): UseMutationOptions<unknown, DefaultError, Options<PostApiFormsFormIdSubmissionsData>> => {
  const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<PostApiFormsFormIdSubmissionsData>> = {
    mutationFn: async (fnOptions) => {
      const { data } = await postApiFormsFormIdSubmissions({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getApiFormsFormIdSubmissionsIdQueryKey = (options: Options<GetApiFormsFormIdSubmissionsIdData>) =>
  createQueryKey('getApiFormsFormIdSubmissionsId', options);

/**
 * Get submission
 *
 * Get a specific submission. Can view own submission or requires permission to manage the form.
 */
export const getApiFormsFormIdSubmissionsIdOptions = (options: Options<GetApiFormsFormIdSubmissionsIdData>) =>
  queryOptions<
    GetApiFormsFormIdSubmissionsIdResponse,
    DefaultError,
    GetApiFormsFormIdSubmissionsIdResponse,
    ReturnType<typeof getApiFormsFormIdSubmissionsIdQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiFormsFormIdSubmissionsId({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getApiFormsFormIdSubmissionsIdQueryKey(options),
  });

export const getApiFormsFormIdSubmissionsDownloadQueryKey = (options: Options<GetApiFormsFormIdSubmissionsDownloadData>) =>
  createQueryKey('getApiFormsFormIdSubmissionsDownload', options);

/**
 * Download submissions as CSV
 *
 * Download all submissions for a form as CSV. Requires permission to manage the form.
 */
export const getApiFormsFormIdSubmissionsDownloadOptions = (options: Options<GetApiFormsFormIdSubmissionsDownloadData>) =>
  queryOptions<unknown, DefaultError, unknown, ReturnType<typeof getApiFormsFormIdSubmissionsDownloadQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiFormsFormIdSubmissionsDownload({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getApiFormsFormIdSubmissionsDownloadQueryKey(options),
  });

/**
 * Delete submission with reason
 *
 * Delete a submission and notify the user with a reason. Admin only.
 */
export const deleteApiFormsFormIdSubmissionsIdDestroyWithReasonMutation = (
  options?: Partial<Options<DeleteApiFormsFormIdSubmissionsIdDestroyWithReasonData>>,
): UseMutationOptions<unknown, DefaultError, Options<DeleteApiFormsFormIdSubmissionsIdDestroyWithReasonData>> => {
  const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<DeleteApiFormsFormIdSubmissionsIdDestroyWithReasonData>> = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteApiFormsFormIdSubmissionsIdDestroyWithReason({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getApiNotificationQueryKey = (options?: Options<GetApiNotificationData>) => createQueryKey('getApiNotification', options);

/**
 * List notifications for authenticated user
 *
 * Returns paginated list of notifications for the authenticated user, ordered by most recent first
 */
export const getApiNotificationOptions = (options?: Options<GetApiNotificationData>) =>
  queryOptions<GetApiNotificationResponse, DefaultError, GetApiNotificationResponse, ReturnType<typeof getApiNotificationQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiNotification({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getApiNotificationQueryKey(options),
  });

export const getApiNotificationInfiniteQueryKey = (options?: Options<GetApiNotificationData>): QueryKey<Options<GetApiNotificationData>> =>
  createQueryKey('getApiNotification', options, true);

/**
 * List notifications for authenticated user
 *
 * Returns paginated list of notifications for the authenticated user, ordered by most recent first
 */
export const getApiNotificationInfiniteOptions = (options?: Options<GetApiNotificationData>) => {
  return infiniteQueryOptions<
    GetApiNotificationResponse,
    DefaultError,
    InfiniteData<GetApiNotificationResponse>,
    QueryKey<Options<GetApiNotificationData>>,
    number | Pick<QueryKey<Options<GetApiNotificationData>>[0], 'body' | 'headers' | 'path' | 'query'>
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<QueryKey<Options<GetApiNotificationData>>[0], 'body' | 'headers' | 'path' | 'query'> =
          typeof pageParam === 'object'
            ? pageParam
            : {
                query: {
                  offset: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getApiNotification({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: getApiNotificationInfiniteQueryKey(options),
    },
  );
};

/**
 * Delete notification
 *
 * Delete a notification by ID. User must be authenticated and own the notification.
 */
export const deleteApiNotificationIdMutation = (
  options?: Partial<Options<DeleteApiNotificationIdData>>,
): UseMutationOptions<DeleteApiNotificationIdResponse, DefaultError, Options<DeleteApiNotificationIdData>> => {
  const mutationOptions: UseMutationOptions<DeleteApiNotificationIdResponse, DefaultError, Options<DeleteApiNotificationIdData>> = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteApiNotificationId({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Mark notification as read or unread
 *
 * Update the read status of a notification. User must be authenticated and own the notification.
 */
export const patchApiNotificationIdReadMutation = (
  options?: Partial<Options<PatchApiNotificationIdReadData>>,
): UseMutationOptions<PatchApiNotificationIdReadResponse, DefaultError, Options<PatchApiNotificationIdReadData>> => {
  const mutationOptions: UseMutationOptions<PatchApiNotificationIdReadResponse, DefaultError, Options<PatchApiNotificationIdReadData>> = {
    mutationFn: async (fnOptions) => {
      const { data } = await patchApiNotificationIdRead({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getApiGroupsQueryKey = (options?: Options<GetApiGroupsData>) => createQueryKey('getApiGroups', options);

/**
 * List groups
 *
 * Retrieve a list of all groups. Supports optional filtering by type and search query.
 */
export const getApiGroupsOptions = (options?: Options<GetApiGroupsData>) =>
  queryOptions<GetApiGroupsResponse, DefaultError, GetApiGroupsResponse, ReturnType<typeof getApiGroupsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiGroups({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getApiGroupsQueryKey(options),
  });

/**
 * Create group
 *
 * Create a new group. Requires 'groups:create' permission.
 */
export const postApiGroupsMutation = (options?: Partial<Options<PostApiGroupsData>>): UseMutationOptions<unknown, DefaultError, Options<PostApiGroupsData>> => {
  const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<PostApiGroupsData>> = {
    mutationFn: async (fnOptions) => {
      const { data } = await postApiGroups({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Delete a group
 *
 * Delete a group by its slug. Requires being a group leader OR having 'groups:delete' permission (globally or scoped to this group). This action is irreversible and will remove all associated data, including memberships and fines.
 */
export const deleteApiGroupsSlugMutation = (
  options?: Partial<Options<DeleteApiGroupsSlugData>>,
): UseMutationOptions<DeleteApiGroupsSlugResponse, DefaultError, Options<DeleteApiGroupsSlugData>> => {
  const mutationOptions: UseMutationOptions<DeleteApiGroupsSlugResponse, DefaultError, Options<DeleteApiGroupsSlugData>> = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteApiGroupsSlug({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getApiGroupsSlugQueryKey = (options: Options<GetApiGroupsSlugData>) => createQueryKey('getApiGroupsSlug', options);

/**
 * Get group by slug
 *
 * Retrieve detailed information about a specific group by its slug identifier.
 */
export const getApiGroupsSlugOptions = (options: Options<GetApiGroupsSlugData>) =>
  queryOptions<GetApiGroupsSlugResponse, DefaultError, GetApiGroupsSlugResponse, ReturnType<typeof getApiGroupsSlugQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiGroupsSlug({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getApiGroupsSlugQueryKey(options),
  });

/**
 * Partially update group
 *
 * Partially update an existing group by its slug. Only provided fields will be updated. Requires being a group leader OR having 'groups:update' permission (globally or scoped to this group).
 */
export const patchApiGroupsSlugMutation = (
  options?: Partial<Options<PatchApiGroupsSlugData>>,
): UseMutationOptions<unknown, DefaultError, Options<PatchApiGroupsSlugData>> => {
  const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<PatchApiGroupsSlugData>> = {
    mutationFn: async (fnOptions) => {
      const { data } = await patchApiGroupsSlug({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getApiGroupsGroupSlugFinesQueryKey = (options: Options<GetApiGroupsGroupSlugFinesData>) => createQueryKey('getApiGroupsGroupSlugFines', options);

/**
 * List fines for a group
 *
 * Retrieve a list of fines for a group. Users can view their own fines, fines admins can view all fines for their group. Supports filtering by status and user.
 */
export const getApiGroupsGroupSlugFinesOptions = (options: Options<GetApiGroupsGroupSlugFinesData>) =>
  queryOptions<GetApiGroupsGroupSlugFinesResponse, DefaultError, GetApiGroupsGroupSlugFinesResponse, ReturnType<typeof getApiGroupsGroupSlugFinesQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiGroupsGroupSlugFines({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getApiGroupsGroupSlugFinesQueryKey(options),
  });

/**
 * Create fine
 *
 * Create a new fine for a group member. Requires being a group leader OR having 'fines:create' permission (globally or scoped to this group).
 */
export const postApiGroupsGroupSlugFinesMutation = (
  options?: Partial<Options<PostApiGroupsGroupSlugFinesData>>,
): UseMutationOptions<unknown, DefaultError, Options<PostApiGroupsGroupSlugFinesData>> => {
  const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<PostApiGroupsGroupSlugFinesData>> = {
    mutationFn: async (fnOptions) => {
      const { data } = await postApiGroupsGroupSlugFines({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Delete a fine
 *
 * Delete a fine by its ID. Requires being the fines admin OR having 'fines:delete' permission (globally or scoped to this group). This action is irreversible.
 */
export const deleteApiGroupsGroupSlugFinesFineIdMutation = (
  options?: Partial<Options<DeleteApiGroupsGroupSlugFinesFineIdData>>,
): UseMutationOptions<DeleteApiGroupsGroupSlugFinesFineIdResponse, DefaultError, Options<DeleteApiGroupsGroupSlugFinesFineIdData>> => {
  const mutationOptions: UseMutationOptions<DeleteApiGroupsGroupSlugFinesFineIdResponse, DefaultError, Options<DeleteApiGroupsGroupSlugFinesFineIdData>> = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteApiGroupsGroupSlugFinesFineId({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getApiGroupsGroupSlugFinesFineIdQueryKey = (options: Options<GetApiGroupsGroupSlugFinesFineIdData>) =>
  createQueryKey('getApiGroupsGroupSlugFinesFineId', options);

/**
 * Get fine by ID
 *
 * Retrieve detailed information about a specific fine. Users can view their own fines, fines admins can view all fines for their group.
 */
export const getApiGroupsGroupSlugFinesFineIdOptions = (options: Options<GetApiGroupsGroupSlugFinesFineIdData>) =>
  queryOptions<
    GetApiGroupsGroupSlugFinesFineIdResponse,
    DefaultError,
    GetApiGroupsGroupSlugFinesFineIdResponse,
    ReturnType<typeof getApiGroupsGroupSlugFinesFineIdQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiGroupsGroupSlugFinesFineId({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getApiGroupsGroupSlugFinesFineIdQueryKey(options),
  });

/**
 * Partially update fine
 *
 * Partially update a fine. Only provided fields will be updated. Users can add defense to their own fines. Fines admins can update status and approve/reject fines.
 */
export const patchApiGroupsGroupSlugFinesFineIdMutation = (
  options?: Partial<Options<PatchApiGroupsGroupSlugFinesFineIdData>>,
): UseMutationOptions<unknown, DefaultError, Options<PatchApiGroupsGroupSlugFinesFineIdData>> => {
  const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<PatchApiGroupsGroupSlugFinesFineIdData>> = {
    mutationFn: async (fnOptions) => {
      const { data } = await patchApiGroupsGroupSlugFinesFineId({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getApiGroupsGroupSlugMembersQueryKey = (options: Options<GetApiGroupsGroupSlugMembersData>) =>
  createQueryKey('getApiGroupsGroupSlugMembers', options);

/**
 * List group members
 *
 * Retrieve a list of all members in a group.
 */
export const getApiGroupsGroupSlugMembersOptions = (options: Options<GetApiGroupsGroupSlugMembersData>) =>
  queryOptions<
    GetApiGroupsGroupSlugMembersResponse,
    DefaultError,
    GetApiGroupsGroupSlugMembersResponse,
    ReturnType<typeof getApiGroupsGroupSlugMembersQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiGroupsGroupSlugMembers({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getApiGroupsGroupSlugMembersQueryKey(options),
  });

/**
 * Add member to group
 *
 * Add a member to a group. Requires 'groups:manage' permission.
 */
export const postApiGroupsGroupSlugMembersMutation = (
  options?: Partial<Options<PostApiGroupsGroupSlugMembersData>>,
): UseMutationOptions<unknown, DefaultError, Options<PostApiGroupsGroupSlugMembersData>> => {
  const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<PostApiGroupsGroupSlugMembersData>> = {
    mutationFn: async (fnOptions) => {
      const { data } = await postApiGroupsGroupSlugMembers({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Remove member from group
 *
 * Remove a member from a group. Requires 'groups:manage' permission.
 */
export const deleteApiGroupsGroupSlugMembersUserIdMutation = (
  options?: Partial<Options<DeleteApiGroupsGroupSlugMembersUserIdData>>,
): UseMutationOptions<DeleteApiGroupsGroupSlugMembersUserIdResponse, DefaultError, Options<DeleteApiGroupsGroupSlugMembersUserIdData>> => {
  const mutationOptions: UseMutationOptions<DeleteApiGroupsGroupSlugMembersUserIdResponse, DefaultError, Options<DeleteApiGroupsGroupSlugMembersUserIdData>> = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteApiGroupsGroupSlugMembersUserId({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Update member role
 *
 * Update a member's role in a group. Requires 'groups:manage' permission.
 */
export const patchApiGroupsGroupSlugMembersUserIdMutation = (
  options?: Partial<Options<PatchApiGroupsGroupSlugMembersUserIdData>>,
): UseMutationOptions<unknown, DefaultError, Options<PatchApiGroupsGroupSlugMembersUserIdData>> => {
  const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<PatchApiGroupsGroupSlugMembersUserIdData>> = {
    mutationFn: async (fnOptions) => {
      const { data } = await patchApiGroupsGroupSlugMembersUserId({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getApiGroupsSlugFormsQueryKey = (options: Options<GetApiGroupsSlugFormsData>) => createQueryKey('getApiGroupsSlugForms', options);

/**
 * List group forms
 *
 * Get all forms for a group, filtered by user permissions
 */
export const getApiGroupsSlugFormsOptions = (options: Options<GetApiGroupsSlugFormsData>) =>
  queryOptions<GetApiGroupsSlugFormsResponse, DefaultError, GetApiGroupsSlugFormsResponse, ReturnType<typeof getApiGroupsSlugFormsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiGroupsSlugForms({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getApiGroupsSlugFormsQueryKey(options),
  });

/**
 * Create group form
 *
 * Create a form for a group. Requires group leader permission or forms:create permission.
 */
export const postApiGroupsSlugFormsMutation = (
  options?: Partial<Options<PostApiGroupsSlugFormsData>>,
): UseMutationOptions<unknown, DefaultError, Options<PostApiGroupsSlugFormsData>> => {
  const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<PostApiGroupsSlugFormsData>> = {
    mutationFn: async (fnOptions) => {
      const { data } = await postApiGroupsSlugForms({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getApiNewsQueryKey = (options?: Options<GetApiNewsData>) => createQueryKey('getApiNews', options);

/**
 * List news articles
 *
 * Get a paginated list of all news articles. Public endpoint.
 */
export const getApiNewsOptions = (options?: Options<GetApiNewsData>) =>
  queryOptions<unknown, DefaultError, unknown, ReturnType<typeof getApiNewsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiNews({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getApiNewsQueryKey(options),
  });

/**
 * Create news article
 *
 * Create a new news article. Requires 'news:create' permission.
 */
export const postApiNewsMutation = (options?: Partial<Options<PostApiNewsData>>): UseMutationOptions<unknown, DefaultError, Options<PostApiNewsData>> => {
  const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<PostApiNewsData>> = {
    mutationFn: async (fnOptions) => {
      const { data } = await postApiNews({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Delete news article
 *
 * Delete a news article. Requires 'news:delete' or 'news:manage' permission (global or scoped) or being the creator.
 */
export const deleteApiNewsIdMutation = (
  options?: Partial<Options<DeleteApiNewsIdData>>,
): UseMutationOptions<unknown, DefaultError, Options<DeleteApiNewsIdData>> => {
  const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<DeleteApiNewsIdData>> = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteApiNewsId({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getApiNewsIdQueryKey = (options: Options<GetApiNewsIdData>) => createQueryKey('getApiNewsId', options);

/**
 * Get news article
 *
 * Get a single news article by ID. Public endpoint.
 */
export const getApiNewsIdOptions = (options: Options<GetApiNewsIdData>) =>
  queryOptions<unknown, DefaultError, unknown, ReturnType<typeof getApiNewsIdQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiNewsId({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getApiNewsIdQueryKey(options),
  });

/**
 * Update news article
 *
 * Update a news article. Requires 'news:update' or 'news:manage' permission (global or scoped) or being the creator.
 */
export const patchApiNewsIdMutation = (
  options?: Partial<Options<PatchApiNewsIdData>>,
): UseMutationOptions<unknown, DefaultError, Options<PatchApiNewsIdData>> => {
  const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<PatchApiNewsIdData>> = {
    mutationFn: async (fnOptions) => {
      const { data } = await patchApiNewsId({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Remove reaction from news
 *
 * Remove your emoji reaction from a news article.
 */
export const deleteApiNewsIdReactionsMutation = (
  options?: Partial<Options<DeleteApiNewsIdReactionsData>>,
): UseMutationOptions<unknown, DefaultError, Options<DeleteApiNewsIdReactionsData>> => {
  const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<DeleteApiNewsIdReactionsData>> = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteApiNewsIdReactions({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Add reaction to news
 *
 * Add or update emoji reaction to a news article. Requires authentication.
 */
export const postApiNewsIdReactionsMutation = (
  options?: Partial<Options<PostApiNewsIdReactionsData>>,
): UseMutationOptions<unknown, DefaultError, Options<PostApiNewsIdReactionsData>> => {
  const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<PostApiNewsIdReactionsData>> = {
    mutationFn: async (fnOptions) => {
      const { data } = await postApiNewsIdReactions({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getApiJobsQueryKey = (options?: Options<GetApiJobsData>) => createQueryKey('getApiJobs', options);

/**
 * List job postings
 *
 * Get a list of job postings. Supports search and expired filtering. Public endpoint.
 */
export const getApiJobsOptions = (options?: Options<GetApiJobsData>) =>
  queryOptions<unknown, DefaultError, unknown, ReturnType<typeof getApiJobsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiJobs({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getApiJobsQueryKey(options),
  });

/**
 * Create job posting
 *
 * Create a new job posting. Requires 'jobs:create' permission.
 */
export const postApiJobsMutation = (options?: Partial<Options<PostApiJobsData>>): UseMutationOptions<unknown, DefaultError, Options<PostApiJobsData>> => {
  const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<PostApiJobsData>> = {
    mutationFn: async (fnOptions) => {
      const { data } = await postApiJobs({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Delete job posting
 *
 * Delete a job posting. Requires 'jobs:delete' or 'jobs:manage' permission (global or scoped) or being the creator.
 */
export const deleteApiJobsIdMutation = (
  options?: Partial<Options<DeleteApiJobsIdData>>,
): UseMutationOptions<unknown, DefaultError, Options<DeleteApiJobsIdData>> => {
  const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<DeleteApiJobsIdData>> = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteApiJobsId({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getApiJobsIdQueryKey = (options: Options<GetApiJobsIdData>) => createQueryKey('getApiJobsId', options);

/**
 * Get job posting
 *
 * Get a single job posting by ID. Public endpoint.
 */
export const getApiJobsIdOptions = (options: Options<GetApiJobsIdData>) =>
  queryOptions<unknown, DefaultError, unknown, ReturnType<typeof getApiJobsIdQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiJobsId({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getApiJobsIdQueryKey(options),
  });

/**
 * Update job posting
 *
 * Update a job posting. Requires 'jobs:update' or 'jobs:manage' permission (global or scoped) or being the creator.
 */
export const patchApiJobsIdMutation = (
  options?: Partial<Options<PatchApiJobsIdData>>,
): UseMutationOptions<unknown, DefaultError, Options<PatchApiJobsIdData>> => {
  const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<PatchApiJobsIdData>> = {
    mutationFn: async (fnOptions) => {
      const { data } = await patchApiJobsId({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getApiUserMeSettingsQueryKey = (options?: Options<GetApiUserMeSettingsData>) => createQueryKey('getApiUserMeSettings', options);

/**
 * Get current user settings
 *
 * Retrieve the authenticated user's settings including preferences and allergies.
 */
export const getApiUserMeSettingsOptions = (options?: Options<GetApiUserMeSettingsData>) =>
  queryOptions<GetApiUserMeSettingsResponse, DefaultError, GetApiUserMeSettingsResponse, ReturnType<typeof getApiUserMeSettingsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiUserMeSettings({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getApiUserMeSettingsQueryKey(options),
  });

/**
 * Update user settings
 *
 * Partially update the authenticated user's settings. Only provided fields will be updated. User must have completed onboarding first.
 */
export const patchApiUserMeSettingsMutation = (
  options?: Partial<Options<PatchApiUserMeSettingsData>>,
): UseMutationOptions<PatchApiUserMeSettingsResponse, DefaultError, Options<PatchApiUserMeSettingsData>> => {
  const mutationOptions: UseMutationOptions<PatchApiUserMeSettingsResponse, DefaultError, Options<PatchApiUserMeSettingsData>> = {
    mutationFn: async (fnOptions) => {
      const { data } = await patchApiUserMeSettings({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Complete user onboarding
 *
 * Create initial user settings and mark the user as onboarded. Can only be called once per user.
 */
export const postApiUserMeSettingsMutation = (
  options?: Partial<Options<PostApiUserMeSettingsData>>,
): UseMutationOptions<PostApiUserMeSettingsResponse, DefaultError, Options<PostApiUserMeSettingsData>> => {
  const mutationOptions: UseMutationOptions<PostApiUserMeSettingsResponse, DefaultError, Options<PostApiUserMeSettingsData>> = {
    mutationFn: async (fnOptions) => {
      const { data } = await postApiUserMeSettings({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getApiUserAllergyQueryKey = (options?: Options<GetApiUserAllergyData>) => createQueryKey('getApiUserAllergy', options);

/**
 * List all allergies
 *
 * Retrieve a list of all possible allergies that users can have.
 */
export const getApiUserAllergyOptions = (options?: Options<GetApiUserAllergyData>) =>
  queryOptions<GetApiUserAllergyResponse, DefaultError, GetApiUserAllergyResponse, ReturnType<typeof getApiUserAllergyQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiUserAllergy({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getApiUserAllergyQueryKey(options),
  });
