/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DotPagesMainLayoutRouteImport } from './pages/MainLayout'
import { Route as DotPagesLandingIndexRouteImport } from './pages/Landing/index'
import { Route as DotRoutesAuthNewAccountRouteImport } from './routes/auth/new-account'
import { Route as DotRoutesAuthLoginRouteImport } from './routes/auth/login'
import { Route as DotRoutesAuthForgotPasswordRouteImport } from './routes/auth/forgot-password'

const DotPagesMainLayoutRoute = DotPagesMainLayoutRouteImport.update({
  id: '/_MainLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const DotPagesLandingIndexRoute = DotPagesLandingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DotPagesMainLayoutRoute,
} as any)
const DotRoutesAuthNewAccountRoute = DotRoutesAuthNewAccountRouteImport.update({
  id: '/ny-bruker',
  path: '/ny-bruker',
  getParentRoute: () => DotPagesMainLayoutRoute,
} as any)
const DotRoutesAuthLoginRoute = DotRoutesAuthLoginRouteImport.update({
  id: '/logg-inn',
  path: '/logg-inn',
  getParentRoute: () => DotPagesMainLayoutRoute,
} as any)
const DotRoutesAuthForgotPasswordRoute =
  DotRoutesAuthForgotPasswordRouteImport.update({
    id: '/glemt-passord',
    path: '/glemt-passord',
    getParentRoute: () => DotPagesMainLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/glemt-passord': typeof DotRoutesAuthForgotPasswordRoute
  '/logg-inn': typeof DotRoutesAuthLoginRoute
  '/ny-bruker': typeof DotRoutesAuthNewAccountRoute
  '/': typeof DotPagesLandingIndexRoute
}
export interface FileRoutesByTo {
  '/glemt-passord': typeof DotRoutesAuthForgotPasswordRoute
  '/logg-inn': typeof DotRoutesAuthLoginRoute
  '/ny-bruker': typeof DotRoutesAuthNewAccountRoute
  '/': typeof DotPagesLandingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_MainLayout': typeof DotPagesMainLayoutRouteWithChildren
  '/_MainLayout/glemt-passord': typeof DotRoutesAuthForgotPasswordRoute
  '/_MainLayout/logg-inn': typeof DotRoutesAuthLoginRoute
  '/_MainLayout/ny-bruker': typeof DotRoutesAuthNewAccountRoute
  '/_MainLayout/': typeof DotPagesLandingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/glemt-passord' | '/logg-inn' | '/ny-bruker' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/glemt-passord' | '/logg-inn' | '/ny-bruker' | '/'
  id:
    | '__root__'
    | '/_MainLayout'
    | '/_MainLayout/glemt-passord'
    | '/_MainLayout/logg-inn'
    | '/_MainLayout/ny-bruker'
    | '/_MainLayout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DotPagesMainLayoutRoute: typeof DotPagesMainLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_MainLayout': {
      id: '/_MainLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DotPagesMainLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_MainLayout/': {
      id: '/_MainLayout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DotPagesLandingIndexRouteImport
      parentRoute: typeof DotPagesMainLayoutRoute
    }
    '/_MainLayout/ny-bruker': {
      id: '/_MainLayout/ny-bruker'
      path: '/ny-bruker'
      fullPath: '/ny-bruker'
      preLoaderRoute: typeof DotRoutesAuthNewAccountRouteImport
      parentRoute: typeof DotPagesMainLayoutRoute
    }
    '/_MainLayout/logg-inn': {
      id: '/_MainLayout/logg-inn'
      path: '/logg-inn'
      fullPath: '/logg-inn'
      preLoaderRoute: typeof DotRoutesAuthLoginRouteImport
      parentRoute: typeof DotPagesMainLayoutRoute
    }
    '/_MainLayout/glemt-passord': {
      id: '/_MainLayout/glemt-passord'
      path: '/glemt-passord'
      fullPath: '/glemt-passord'
      preLoaderRoute: typeof DotRoutesAuthForgotPasswordRouteImport
      parentRoute: typeof DotPagesMainLayoutRoute
    }
  }
}

interface DotPagesMainLayoutRouteChildren {
  DotRoutesAuthForgotPasswordRoute: typeof DotRoutesAuthForgotPasswordRoute
  DotRoutesAuthLoginRoute: typeof DotRoutesAuthLoginRoute
  DotRoutesAuthNewAccountRoute: typeof DotRoutesAuthNewAccountRoute
  DotPagesLandingIndexRoute: typeof DotPagesLandingIndexRoute
}

const DotPagesMainLayoutRouteChildren: DotPagesMainLayoutRouteChildren = {
  DotRoutesAuthForgotPasswordRoute: DotRoutesAuthForgotPasswordRoute,
  DotRoutesAuthLoginRoute: DotRoutesAuthLoginRoute,
  DotRoutesAuthNewAccountRoute: DotRoutesAuthNewAccountRoute,
  DotPagesLandingIndexRoute: DotPagesLandingIndexRoute,
}

const DotPagesMainLayoutRouteWithChildren =
  DotPagesMainLayoutRoute._addFileChildren(DotPagesMainLayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  DotPagesMainLayoutRoute: DotPagesMainLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
