import type { Badge, BadgeCategory, Group } from '~/types';

const WIKI = 'https://wiki.tihlde.org/';
const WIKI_URLS = {
  wiki: WIKI,
  ABOUT_INDEX: 'https://wiki.tihlde.org/instruks-index',
  CONTACT_US: 'https://wiki.tihlde.org/kontakt',
  EVENT_RULES: 'https://wiki.tihlde.org/arrangementer',
  NEW_STUDENT: 'https://wiki.tihlde.org/ny-student',
} as const;

const MOBILE_APP = {
  Android: 'https://play.google.com/store/apps/details?id=com.tihlde.app',
  iOS: 'https://apps.apple.com/no/app/tihlde/id6742454079',
} as const;

const URLS = {
  badges: {
    index: '/badges',
    categories: '/badges/kategorier',
    category_leaderboard: (categoryId: BadgeCategory['id']) => `${URLS.badges.categories}/${categoryId}`,
    category_badges_relative: 'badges',
    category_badges: (categoryId: BadgeCategory['id']) => `${URLS.badges.category_leaderboard(categoryId)}/${URLS.badges.category_badges_relative}`,
    public_badges_relative: 'alle',
    public_badges: () => `${URLS.badges.index}/${URLS.badges.public_badges_relative}`,
    badge_leaderboard: (badgeId: Badge['id']) => `${URLS.badges.index}/${badgeId}`,
    get_badge_relative: 'erverv',
    get_badge: () => `${URLS.badges.index}/${URLS.badges.get_badge_relative}`,
  },
  feedback: '/tilbakemelding',
  cheatsheet: '/kokebok',
  company: '/bedrifter',
  events: '/arrangementer',
  eventRegister: 'registrering',
  forgotPassword: '/glemt-passord',
  form: '/sporreskjema',
  groups: {
    index: '/grupper',
    interest: '/interessegrupper',
    details: (groupSlug: Group['slug']) => `${URLS.groups.index}/${groupSlug}`,
    events_relative: 'arrangementer',
    events: (groupSlug: Group['slug']) => `${URLS.groups.details(groupSlug)}/${URLS.groups.events_relative}`,
    fines_relative: 'boter',
    fines: (groupSlug: Group['slug']) => `${URLS.groups.details(groupSlug)}/${URLS.groups.fines_relative}`,
    forms_relative: 'sporreskjema',
    forms: (groupSlug: Group['slug']) => `${URLS.groups.details(groupSlug)}/${URLS.groups.forms_relative}`,
    laws_relative: 'lovverk',
    laws: (groupSlug: Group['slug']) => `${URLS.groups.details(groupSlug)}/${URLS.groups.laws_relative}`,
  },
  jobposts: '/stillingsannonser',
  landing: '/',
  login: '/logg-inn',
  newStudent: '/ny-student',
  news: '/nyheter',
  toddel: '/toddel',
  profile: '/profil',
  signup: '/ny-bruker',
  signupForm: '/ny-bruker/skjema',
  signupFeide: '/ny-bruker/feide',
  shortLinks: '/linker',
  qrCodes: '/qr-koder',
  gallery: '/galleri',
  userAdmin: '/admin/brukere',
  newGroupAdmin: '/admin/ny-gruppe',
  strikeAdmin: '/admin/prikker',
  eventAdmin: '/admin/arrangementer',
  jobpostsAdmin: '/admin/stillingsannonser',
  newsAdmin: '/admin/nyheter',
  bannerAdmin: '/admin/bannere',
  external: {
    wiki: WIKI_URLS,
    mobileApp: MOBILE_APP,
    jubilee: 'https://jubileum.tihlde.org',
    fondet: 'https://fondet.tihlde.org',
    kontRes: 'https://kontres.tihlde.org',
    github: 'https://github.com/TIHLDE',
    pythons: 'https://pythons.tihlde.org',
    discord: 'https://discord.gg/HNt5XQdyxy',
    pythonsLadies: 'https://pythons-damer.tihlde.org',
  },
  changelog: '/endringslogg',
  admissions: '/opptak',
  opptakAdmin: '/admin/opptak',
} as const;

export default URLS;
