export default {
  landing: '/',
  events: '/arrangementer/',
  company: '/bedrifter/',
  about: '/om-tihlde/',
  contactInfo: '/kontakt/',
  services: '/tjenester/',
  newStudent: '/nystudent/',
  jobposts: '/karriere/',
  profile: '/profil/',
  login: '/logg-inn/',
  forgotPassword: '/glemt-passord/',
  laws: '/lover/',
  newlanding: '/newlanding/',
  signup: '/ny-bruker/',
  privacyPolicy: '/personvern/',
  eventRules: '/arrangementsregler/',
  cheatsheet: '/kokebok/',
  news: '/nyheter/',
  pages: '/om/',
  aboutIndex: '/om/undergrupper/index/',

  userAdmin: '/admin/brukere/',
  eventAdmin: '/admin/arrangementer/',
  jobpostsAdmin: '/admin/karriere/',
  newsAdmin: '/admin/nyheter/',
};
