export default {
    landing: '/',
    events: '/arrangementer/',
    company: '/bedrifter/',
    about: '/om/',
    contactInfo: '/kontakt/',
    services: '/tjenester/',
    newStudent: '/nystudent/',
    jobposts: '/karriere/',
    profile: '/profil/',
    login: '/logg-inn/',
    laws: '/lover/',
    newlanding: '/newlanding/',
    signup: '/ny-bruker/',
    privacyPolicy: '/personvern/',

    admin: '/admin/',
    userAdmin: '/admin/brukere/',
    eventAdmin: '/admin/arrangementer/',
    jobpostsAdmin: '/admin/karriere/',
};
