// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type {
  DeleteApiApiKeysIdData,
  DeleteApiApiKeysIdErrors,
  DeleteApiApiKeysIdResponses,
  DeleteApiEventEventIdData,
  DeleteApiEventEventIdErrors,
  DeleteApiEventEventIdRegistrationData,
  DeleteApiEventEventIdRegistrationResponses,
  DeleteApiEventEventIdResponses,
  DeleteApiFormsFormIdSubmissionsIdDestroyWithReasonData,
  DeleteApiFormsFormIdSubmissionsIdDestroyWithReasonErrors,
  DeleteApiFormsFormIdSubmissionsIdDestroyWithReasonResponses,
  DeleteApiFormsIdData,
  DeleteApiFormsIdErrors,
  DeleteApiFormsIdResponses,
  DeleteApiGroupsGroupSlugFinesFineIdData,
  DeleteApiGroupsGroupSlugFinesFineIdErrors,
  DeleteApiGroupsGroupSlugFinesFineIdResponses,
  DeleteApiGroupsGroupSlugMembersUserIdData,
  DeleteApiGroupsGroupSlugMembersUserIdErrors,
  DeleteApiGroupsGroupSlugMembersUserIdResponses,
  DeleteApiGroupsSlugData,
  DeleteApiGroupsSlugErrors,
  DeleteApiGroupsSlugResponses,
  DeleteApiJobsIdData,
  DeleteApiJobsIdErrors,
  DeleteApiJobsIdResponses,
  DeleteApiNewsIdData,
  DeleteApiNewsIdErrors,
  DeleteApiNewsIdReactionsData,
  DeleteApiNewsIdReactionsErrors,
  DeleteApiNewsIdReactionsResponses,
  DeleteApiNewsIdResponses,
  DeleteApiNotificationIdData,
  DeleteApiNotificationIdErrors,
  DeleteApiNotificationIdResponses,
  GetApiApiKeysData,
  GetApiApiKeysErrors,
  GetApiApiKeysIdData,
  GetApiApiKeysIdErrors,
  GetApiApiKeysIdResponses,
  GetApiApiKeysResponses,
  GetApiEventData,
  GetApiEventEventIdFormsData,
  GetApiEventEventIdFormsErrors,
  GetApiEventEventIdFormsResponses,
  GetApiEventEventIdFormsTypeData,
  GetApiEventEventIdFormsTypeErrors,
  GetApiEventEventIdFormsTypeResponses,
  GetApiEventEventIdRegistrationData,
  GetApiEventEventIdRegistrationResponses,
  GetApiEventFavoriteData,
  GetApiEventFavoriteResponses,
  GetApiEventResponses,
  GetApiFormsData,
  GetApiFormsFormIdSubmissionsData,
  GetApiFormsFormIdSubmissionsDownloadData,
  GetApiFormsFormIdSubmissionsDownloadErrors,
  GetApiFormsFormIdSubmissionsDownloadResponses,
  GetApiFormsFormIdSubmissionsErrors,
  GetApiFormsFormIdSubmissionsIdData,
  GetApiFormsFormIdSubmissionsIdErrors,
  GetApiFormsFormIdSubmissionsIdResponses,
  GetApiFormsFormIdSubmissionsResponses,
  GetApiFormsIdData,
  GetApiFormsIdErrors,
  GetApiFormsIdResponses,
  GetApiFormsIdStatisticsData,
  GetApiFormsIdStatisticsErrors,
  GetApiFormsIdStatisticsResponses,
  GetApiFormsResponses,
  GetApiGroupsData,
  GetApiGroupsGroupSlugFinesData,
  GetApiGroupsGroupSlugFinesErrors,
  GetApiGroupsGroupSlugFinesFineIdData,
  GetApiGroupsGroupSlugFinesFineIdErrors,
  GetApiGroupsGroupSlugFinesFineIdResponses,
  GetApiGroupsGroupSlugFinesResponses,
  GetApiGroupsGroupSlugMembersData,
  GetApiGroupsGroupSlugMembersErrors,
  GetApiGroupsGroupSlugMembersResponses,
  GetApiGroupsResponses,
  GetApiGroupsSlugData,
  GetApiGroupsSlugErrors,
  GetApiGroupsSlugFormsData,
  GetApiGroupsSlugFormsErrors,
  GetApiGroupsSlugFormsResponses,
  GetApiGroupsSlugResponses,
  GetApiJobsData,
  GetApiJobsIdData,
  GetApiJobsIdErrors,
  GetApiJobsIdResponses,
  GetApiJobsResponses,
  GetApiNewsData,
  GetApiNewsIdData,
  GetApiNewsIdErrors,
  GetApiNewsIdResponses,
  GetApiNewsResponses,
  GetApiNotificationData,
  GetApiNotificationErrors,
  GetApiNotificationResponses,
  GetApiUserAllergyData,
  GetApiUserAllergyResponses,
  GetApiUserMeSettingsData,
  GetApiUserMeSettingsErrors,
  GetApiUserMeSettingsResponses,
  PatchApiApiKeysIdData,
  PatchApiApiKeysIdErrors,
  PatchApiApiKeysIdResponses,
  PatchApiFormsIdData,
  PatchApiFormsIdErrors,
  PatchApiFormsIdResponses,
  PatchApiGroupsGroupSlugFinesFineIdData,
  PatchApiGroupsGroupSlugFinesFineIdErrors,
  PatchApiGroupsGroupSlugFinesFineIdResponses,
  PatchApiGroupsGroupSlugMembersUserIdData,
  PatchApiGroupsGroupSlugMembersUserIdErrors,
  PatchApiGroupsGroupSlugMembersUserIdResponses,
  PatchApiGroupsSlugData,
  PatchApiGroupsSlugErrors,
  PatchApiGroupsSlugResponses,
  PatchApiJobsIdData,
  PatchApiJobsIdErrors,
  PatchApiJobsIdResponses,
  PatchApiNewsIdData,
  PatchApiNewsIdErrors,
  PatchApiNewsIdResponses,
  PatchApiNotificationIdReadData,
  PatchApiNotificationIdReadErrors,
  PatchApiNotificationIdReadResponses,
  PatchApiUserMeSettingsData,
  PatchApiUserMeSettingsErrors,
  PatchApiUserMeSettingsResponses,
  PostApiApiKeysData,
  PostApiApiKeysErrors,
  PostApiApiKeysIdRegenerateData,
  PostApiApiKeysIdRegenerateErrors,
  PostApiApiKeysIdRegenerateResponses,
  PostApiApiKeysResponses,
  PostApiApiKeysValidateData,
  PostApiApiKeysValidateResponses,
  PostApiEmailSendData,
  PostApiEmailSendErrors,
  PostApiEmailSendResponses,
  PostApiEventData,
  PostApiEventErrors,
  PostApiEventEventIdFormsData,
  PostApiEventEventIdFormsErrors,
  PostApiEventEventIdFormsResponses,
  PostApiEventEventIdPaymentData,
  PostApiEventEventIdPaymentErrors,
  PostApiEventEventIdPaymentResponses,
  PostApiEventEventIdRegistrationData,
  PostApiEventEventIdRegistrationErrors,
  PostApiEventEventIdRegistrationResponses,
  PostApiEventPaymentWebhookData,
  PostApiEventPaymentWebhookErrors,
  PostApiEventPaymentWebhookResponses,
  PostApiEventResponses,
  PostApiFormsData,
  PostApiFormsErrors,
  PostApiFormsFormIdSubmissionsData,
  PostApiFormsFormIdSubmissionsErrors,
  PostApiFormsFormIdSubmissionsResponses,
  PostApiFormsResponses,
  PostApiGroupsData,
  PostApiGroupsErrors,
  PostApiGroupsGroupSlugFinesData,
  PostApiGroupsGroupSlugFinesErrors,
  PostApiGroupsGroupSlugFinesResponses,
  PostApiGroupsGroupSlugMembersData,
  PostApiGroupsGroupSlugMembersErrors,
  PostApiGroupsGroupSlugMembersResponses,
  PostApiGroupsResponses,
  PostApiGroupsSlugFormsData,
  PostApiGroupsSlugFormsErrors,
  PostApiGroupsSlugFormsResponses,
  PostApiJobsData,
  PostApiJobsErrors,
  PostApiJobsResponses,
  PostApiNewsData,
  PostApiNewsErrors,
  PostApiNewsIdReactionsData,
  PostApiNewsIdReactionsErrors,
  PostApiNewsIdReactionsResponses,
  PostApiNewsResponses,
  PostApiUserMeSettingsData,
  PostApiUserMeSettingsErrors,
  PostApiUserMeSettingsResponses,
  PutApiEventFavoriteIdData,
  PutApiEventFavoriteIdErrors,
  PutApiEventFavoriteIdResponses,
  PutApiEventIdData,
  PutApiEventIdErrors,
  PutApiEventIdResponses,
} from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * List API keys
 *
 * Get a list of all API keys. Does not include the full key values. Requires 'api-keys:view' permission.
 */
export const getApiApiKeys = <ThrowOnError extends boolean = false>(options?: Options<GetApiApiKeysData, ThrowOnError>) => {
  return (options?.client ?? client).get<GetApiApiKeysResponses, GetApiApiKeysErrors, ThrowOnError>({
    url: '/api/api-keys',
    ...options,
  });
};

/**
 * Create API key
 *
 * Create a new API key. The full key is returned only once and cannot be retrieved again. Requires 'api-keys:create' permission.
 */
export const postApiApiKeys = <ThrowOnError extends boolean = false>(options?: Options<PostApiApiKeysData, ThrowOnError>) => {
  return (options?.client ?? client).post<PostApiApiKeysResponses, PostApiApiKeysErrors, ThrowOnError>({
    url: '/api/api-keys',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * Delete API key
 *
 * Delete an API key. This action is irreversible. Requires 'api-keys:delete' permission.
 */
export const deleteApiApiKeysId = <ThrowOnError extends boolean = false>(options: Options<DeleteApiApiKeysIdData, ThrowOnError>) => {
  return (options.client ?? client).delete<DeleteApiApiKeysIdResponses, DeleteApiApiKeysIdErrors, ThrowOnError>({
    url: '/api/api-keys/{id}',
    ...options,
  });
};

/**
 * Get API key
 *
 * Get a single API key by ID. Does not include the full key value. Requires 'api-keys:view' permission.
 */
export const getApiApiKeysId = <ThrowOnError extends boolean = false>(options: Options<GetApiApiKeysIdData, ThrowOnError>) => {
  return (options.client ?? client).get<GetApiApiKeysIdResponses, GetApiApiKeysIdErrors, ThrowOnError>({
    url: '/api/api-keys/{id}',
    ...options,
  });
};

/**
 * Update API key
 *
 * Update an API key's metadata (name, description, permissions, metadata). Cannot update the key itself - use regenerate for that. Requires 'api-keys:update' permission.
 */
export const patchApiApiKeysId = <ThrowOnError extends boolean = false>(options: Options<PatchApiApiKeysIdData, ThrowOnError>) => {
  return (options.client ?? client).patch<PatchApiApiKeysIdResponses, PatchApiApiKeysIdErrors, ThrowOnError>({
    url: '/api/api-keys/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * Regenerate API key
 *
 * Generate a new key value for an existing API key. The old key will be invalidated. The new full key is returned only once and cannot be retrieved again. Requires 'api-keys:update' permission.
 */
export const postApiApiKeysIdRegenerate = <ThrowOnError extends boolean = false>(options: Options<PostApiApiKeysIdRegenerateData, ThrowOnError>) => {
  return (options.client ?? client).post<PostApiApiKeysIdRegenerateResponses, PostApiApiKeysIdRegenerateErrors, ThrowOnError>({
    url: '/api/api-keys/{id}/regenerate',
    ...options,
  });
};

/**
 * Validate API key
 *
 * Check if an API key is valid and return its details. This is a public endpoint that does not require authentication. Updates the lastUsedAt timestamp if the key is valid.
 */
export const postApiApiKeysValidate = <ThrowOnError extends boolean = false>(options?: Options<PostApiApiKeysValidateData, ThrowOnError>) => {
  return (options?.client ?? client).post<PostApiApiKeysValidateResponses, unknown, ThrowOnError>({
    url: '/api/api-keys/validate',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * Send custom email
 *
 * Send a custom email with structured content blocks. Requires API key authentication via Bearer token.
 */
export const postApiEmailSend = <ThrowOnError extends boolean = false>(options?: Options<PostApiEmailSendData, ThrowOnError>) => {
  return (options?.client ?? client).post<PostApiEmailSendResponses, PostApiEmailSendErrors, ThrowOnError>({
    url: '/api/email/send',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * List events
 */
export const getApiEvent = <ThrowOnError extends boolean = false>(options?: Options<GetApiEventData, ThrowOnError>) => {
  return (options?.client ?? client).get<GetApiEventResponses, unknown, ThrowOnError>({
    url: '/api/event',
    ...options,
  });
};

/**
 * Create event
 *
 * Create a new event. Requires 'events:create' permission.
 */
export const postApiEvent = <ThrowOnError extends boolean = false>(options?: Options<PostApiEventData, ThrowOnError>) => {
  return (options?.client ?? client).post<PostApiEventResponses, PostApiEventErrors, ThrowOnError>({
    url: '/api/event',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * Update event
 *
 * Update an event by its ID. Event creators can update their own events. Users with 'events:update' or 'events:manage' permission can update any event.
 */
export const putApiEventId = <ThrowOnError extends boolean = false>(options: Options<PutApiEventIdData, ThrowOnError>) => {
  return (options.client ?? client).put<PutApiEventIdResponses, PutApiEventIdErrors, ThrowOnError>({
    url: '/api/event/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * Delete an event
 *
 * Delete an event by its ID. Event creators can delete their own events. Users with 'events:delete' permission can delete any event. This action is irreversible and will remove all associated data, including registrations and feedback.
 */
export const deleteApiEventEventId = <ThrowOnError extends boolean = false>(options: Options<DeleteApiEventEventIdData, ThrowOnError>) => {
  return (options.client ?? client).delete<DeleteApiEventEventIdResponses, DeleteApiEventEventIdErrors, ThrowOnError>({
    url: '/api/event/{eventId}',
    ...options,
  });
};

/**
 * Update event favorite
 */
export const putApiEventFavoriteId = <ThrowOnError extends boolean = false>(options: Options<PutApiEventFavoriteIdData, ThrowOnError>) => {
  return (options.client ?? client).put<PutApiEventFavoriteIdResponses, PutApiEventFavoriteIdErrors, ThrowOnError>({
    url: '/api/event/favorite/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * Get all my favorite events
 */
export const getApiEventFavorite = <ThrowOnError extends boolean = false>(options?: Options<GetApiEventFavoriteData, ThrowOnError>) => {
  return (options?.client ?? client).get<GetApiEventFavoriteResponses, unknown, ThrowOnError>({
    url: '/api/event/favorite',
    ...options,
  });
};

/**
 * Unregister from event
 */
export const deleteApiEventEventIdRegistration = <ThrowOnError extends boolean = false>(
  options: Options<DeleteApiEventEventIdRegistrationData, ThrowOnError>,
) => {
  return (options.client ?? client).delete<DeleteApiEventEventIdRegistrationResponses, unknown, ThrowOnError>({
    url: '/api/event/{eventId}/registration',
    ...options,
  });
};

/**
 * Get event registrations
 */
export const getApiEventEventIdRegistration = <ThrowOnError extends boolean = false>(options: Options<GetApiEventEventIdRegistrationData, ThrowOnError>) => {
  return (options.client ?? client).get<GetApiEventEventIdRegistrationResponses, unknown, ThrowOnError>({
    url: '/api/event/{eventId}/registration',
    ...options,
  });
};

/**
 * Register to an event
 */
export const postApiEventEventIdRegistration = <ThrowOnError extends boolean = false>(options: Options<PostApiEventEventIdRegistrationData, ThrowOnError>) => {
  return (options.client ?? client).post<PostApiEventEventIdRegistrationResponses, PostApiEventEventIdRegistrationErrors, ThrowOnError>({
    url: '/api/event/{eventId}/registration',
    ...options,
  });
};

/**
 * Create payment for event
 *
 * Initiates a Vipps payment for an event registration. User must have a registered status for the event.
 */
export const postApiEventEventIdPayment = <ThrowOnError extends boolean = false>(options: Options<PostApiEventEventIdPaymentData, ThrowOnError>) => {
  return (options.client ?? client).post<PostApiEventEventIdPaymentResponses, PostApiEventEventIdPaymentErrors, ThrowOnError>({
    url: '/api/event/{eventId}/payment',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * Vipps payment webhook
 *
 * Webhook endpoint for Vipps to notify about payment status changes. Updates payment record based on Vipps payment state.
 */
export const postApiEventPaymentWebhook = <ThrowOnError extends boolean = false>(options?: Options<PostApiEventPaymentWebhookData, ThrowOnError>) => {
  return (options?.client ?? client).post<PostApiEventPaymentWebhookResponses, PostApiEventPaymentWebhookErrors, ThrowOnError>({
    url: '/api/event/payment/webhook',
    ...options,
  });
};

/**
 * List event forms
 *
 * Get all forms (survey and evaluation) for an event
 */
export const getApiEventEventIdForms = <ThrowOnError extends boolean = false>(options: Options<GetApiEventEventIdFormsData, ThrowOnError>) => {
  return (options.client ?? client).get<GetApiEventEventIdFormsResponses, GetApiEventEventIdFormsErrors, ThrowOnError>({
    url: '/api/event/{eventId}/forms',
    ...options,
  });
};

/**
 * Create event form
 *
 * Create a survey or evaluation form for an event. Requires event write permission.
 */
export const postApiEventEventIdForms = <ThrowOnError extends boolean = false>(options: Options<PostApiEventEventIdFormsData, ThrowOnError>) => {
  return (options.client ?? client).post<PostApiEventEventIdFormsResponses, PostApiEventEventIdFormsErrors, ThrowOnError>({
    url: '/api/event/{eventId}/forms',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * Get event form
 *
 * Get a specific form (survey or evaluation) for an event with all fields and options
 */
export const getApiEventEventIdFormsType = <ThrowOnError extends boolean = false>(options: Options<GetApiEventEventIdFormsTypeData, ThrowOnError>) => {
  return (options.client ?? client).get<GetApiEventEventIdFormsTypeResponses, GetApiEventEventIdFormsTypeErrors, ThrowOnError>({
    url: '/api/event/{eventId}/forms/{type}',
    ...options,
  });
};

/**
 * List forms
 *
 * List all form templates by default. Use ?all=true to include all forms. Returns template forms by default.
 */
export const getApiForms = <ThrowOnError extends boolean = false>(options?: Options<GetApiFormsData, ThrowOnError>) => {
  return (options?.client ?? client).get<GetApiFormsResponses, unknown, ThrowOnError>({
    url: '/api/forms',
    ...options,
  });
};

/**
 * Create form
 *
 * Create a new base form template. Requires 'forms:create' permission.
 */
export const postApiForms = <ThrowOnError extends boolean = false>(options?: Options<PostApiFormsData, ThrowOnError>) => {
  return (options?.client ?? client).post<PostApiFormsResponses, PostApiFormsErrors, ThrowOnError>({
    url: '/api/forms',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * Delete form
 *
 * Delete a form and all associated data. Requires permission to manage the form.
 */
export const deleteApiFormsId = <ThrowOnError extends boolean = false>(options: Options<DeleteApiFormsIdData, ThrowOnError>) => {
  return (options.client ?? client).delete<DeleteApiFormsIdResponses, DeleteApiFormsIdErrors, ThrowOnError>({
    url: '/api/forms/{id}',
    ...options,
  });
};

/**
 * Get form
 *
 * Get a form by ID with all fields and options
 */
export const getApiFormsId = <ThrowOnError extends boolean = false>(options: Options<GetApiFormsIdData, ThrowOnError>) => {
  return (options.client ?? client).get<GetApiFormsIdResponses, GetApiFormsIdErrors, ThrowOnError>({
    url: '/api/forms/{id}',
    ...options,
  });
};

/**
 * Update form
 *
 * Update a form. Requires permission to manage the form.
 */
export const patchApiFormsId = <ThrowOnError extends boolean = false>(options: Options<PatchApiFormsIdData, ThrowOnError>) => {
  return (options.client ?? client).patch<PatchApiFormsIdResponses, PatchApiFormsIdErrors, ThrowOnError>({
    url: '/api/forms/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * Get form statistics
 *
 * Get aggregated statistics for a form. Requires permission to manage the form.
 */
export const getApiFormsIdStatistics = <ThrowOnError extends boolean = false>(options: Options<GetApiFormsIdStatisticsData, ThrowOnError>) => {
  return (options.client ?? client).get<GetApiFormsIdStatisticsResponses, GetApiFormsIdStatisticsErrors, ThrowOnError>({
    url: '/api/forms/{id}/statistics',
    ...options,
  });
};

/**
 * List submissions
 *
 * List all submissions for a form. Requires permission to manage the form.
 */
export const getApiFormsFormIdSubmissions = <ThrowOnError extends boolean = false>(options: Options<GetApiFormsFormIdSubmissionsData, ThrowOnError>) => {
  return (options.client ?? client).get<GetApiFormsFormIdSubmissionsResponses, GetApiFormsFormIdSubmissionsErrors, ThrowOnError>({
    url: '/api/forms/{formId}/submissions',
    ...options,
  });
};

/**
 * Create submission
 *
 * Submit answers to a form
 */
export const postApiFormsFormIdSubmissions = <ThrowOnError extends boolean = false>(options: Options<PostApiFormsFormIdSubmissionsData, ThrowOnError>) => {
  return (options.client ?? client).post<PostApiFormsFormIdSubmissionsResponses, PostApiFormsFormIdSubmissionsErrors, ThrowOnError>({
    url: '/api/forms/{formId}/submissions',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * Get submission
 *
 * Get a specific submission. Can view own submission or requires permission to manage the form.
 */
export const getApiFormsFormIdSubmissionsId = <ThrowOnError extends boolean = false>(options: Options<GetApiFormsFormIdSubmissionsIdData, ThrowOnError>) => {
  return (options.client ?? client).get<GetApiFormsFormIdSubmissionsIdResponses, GetApiFormsFormIdSubmissionsIdErrors, ThrowOnError>({
    url: '/api/forms/{formId}/submissions/{id}',
    ...options,
  });
};

/**
 * Download submissions as CSV
 *
 * Download all submissions for a form as CSV. Requires permission to manage the form.
 */
export const getApiFormsFormIdSubmissionsDownload = <ThrowOnError extends boolean = false>(
  options: Options<GetApiFormsFormIdSubmissionsDownloadData, ThrowOnError>,
) => {
  return (options.client ?? client).get<GetApiFormsFormIdSubmissionsDownloadResponses, GetApiFormsFormIdSubmissionsDownloadErrors, ThrowOnError>({
    url: '/api/forms/{formId}/submissions/download',
    ...options,
  });
};

/**
 * Delete submission with reason
 *
 * Delete a submission and notify the user with a reason. Admin only.
 */
export const deleteApiFormsFormIdSubmissionsIdDestroyWithReason = <ThrowOnError extends boolean = false>(
  options: Options<DeleteApiFormsFormIdSubmissionsIdDestroyWithReasonData, ThrowOnError>,
) => {
  return (options.client ?? client).delete<
    DeleteApiFormsFormIdSubmissionsIdDestroyWithReasonResponses,
    DeleteApiFormsFormIdSubmissionsIdDestroyWithReasonErrors,
    ThrowOnError
  >({
    url: '/api/forms/{formId}/submissions/{id}/destroy_with_reason',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * List notifications for authenticated user
 *
 * Returns paginated list of notifications for the authenticated user, ordered by most recent first
 */
export const getApiNotification = <ThrowOnError extends boolean = false>(options?: Options<GetApiNotificationData, ThrowOnError>) => {
  return (options?.client ?? client).get<GetApiNotificationResponses, GetApiNotificationErrors, ThrowOnError>({
    url: '/api/notification',
    ...options,
  });
};

/**
 * Delete notification
 *
 * Delete a notification by ID. User must be authenticated and own the notification.
 */
export const deleteApiNotificationId = <ThrowOnError extends boolean = false>(options: Options<DeleteApiNotificationIdData, ThrowOnError>) => {
  return (options.client ?? client).delete<DeleteApiNotificationIdResponses, DeleteApiNotificationIdErrors, ThrowOnError>({
    url: '/api/notification/{id}',
    ...options,
  });
};

/**
 * Mark notification as read or unread
 *
 * Update the read status of a notification. User must be authenticated and own the notification.
 */
export const patchApiNotificationIdRead = <ThrowOnError extends boolean = false>(options: Options<PatchApiNotificationIdReadData, ThrowOnError>) => {
  return (options.client ?? client).patch<PatchApiNotificationIdReadResponses, PatchApiNotificationIdReadErrors, ThrowOnError>({
    url: '/api/notification/{id}/read',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * List groups
 *
 * Retrieve a list of all groups. Supports optional filtering by type and search query.
 */
export const getApiGroups = <ThrowOnError extends boolean = false>(options?: Options<GetApiGroupsData, ThrowOnError>) => {
  return (options?.client ?? client).get<GetApiGroupsResponses, unknown, ThrowOnError>({
    url: '/api/groups',
    ...options,
  });
};

/**
 * Create group
 *
 * Create a new group. Requires 'groups:create' permission.
 */
export const postApiGroups = <ThrowOnError extends boolean = false>(options?: Options<PostApiGroupsData, ThrowOnError>) => {
  return (options?.client ?? client).post<PostApiGroupsResponses, PostApiGroupsErrors, ThrowOnError>({
    url: '/api/groups',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * Delete a group
 *
 * Delete a group by its slug. Requires being a group leader OR having 'groups:delete' permission (globally or scoped to this group). This action is irreversible and will remove all associated data, including memberships and fines.
 */
export const deleteApiGroupsSlug = <ThrowOnError extends boolean = false>(options: Options<DeleteApiGroupsSlugData, ThrowOnError>) => {
  return (options.client ?? client).delete<DeleteApiGroupsSlugResponses, DeleteApiGroupsSlugErrors, ThrowOnError>({
    url: '/api/groups/{slug}',
    ...options,
  });
};

/**
 * Get group by slug
 *
 * Retrieve detailed information about a specific group by its slug identifier.
 */
export const getApiGroupsSlug = <ThrowOnError extends boolean = false>(options: Options<GetApiGroupsSlugData, ThrowOnError>) => {
  return (options.client ?? client).get<GetApiGroupsSlugResponses, GetApiGroupsSlugErrors, ThrowOnError>({
    url: '/api/groups/{slug}',
    ...options,
  });
};

/**
 * Partially update group
 *
 * Partially update an existing group by its slug. Only provided fields will be updated. Requires being a group leader OR having 'groups:update' permission (globally or scoped to this group).
 */
export const patchApiGroupsSlug = <ThrowOnError extends boolean = false>(options: Options<PatchApiGroupsSlugData, ThrowOnError>) => {
  return (options.client ?? client).patch<PatchApiGroupsSlugResponses, PatchApiGroupsSlugErrors, ThrowOnError>({
    url: '/api/groups/{slug}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * List fines for a group
 *
 * Retrieve a list of fines for a group. Users can view their own fines, fines admins can view all fines for their group. Supports filtering by status and user.
 */
export const getApiGroupsGroupSlugFines = <ThrowOnError extends boolean = false>(options: Options<GetApiGroupsGroupSlugFinesData, ThrowOnError>) => {
  return (options.client ?? client).get<GetApiGroupsGroupSlugFinesResponses, GetApiGroupsGroupSlugFinesErrors, ThrowOnError>({
    url: '/api/groups/{groupSlug}/fines',
    ...options,
  });
};

/**
 * Create fine
 *
 * Create a new fine for a group member. Requires being a group leader OR having 'fines:create' permission (globally or scoped to this group).
 */
export const postApiGroupsGroupSlugFines = <ThrowOnError extends boolean = false>(options: Options<PostApiGroupsGroupSlugFinesData, ThrowOnError>) => {
  return (options.client ?? client).post<PostApiGroupsGroupSlugFinesResponses, PostApiGroupsGroupSlugFinesErrors, ThrowOnError>({
    url: '/api/groups/{groupSlug}/fines',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * Delete a fine
 *
 * Delete a fine by its ID. Requires being the fines admin OR having 'fines:delete' permission (globally or scoped to this group). This action is irreversible.
 */
export const deleteApiGroupsGroupSlugFinesFineId = <ThrowOnError extends boolean = false>(
  options: Options<DeleteApiGroupsGroupSlugFinesFineIdData, ThrowOnError>,
) => {
  return (options.client ?? client).delete<DeleteApiGroupsGroupSlugFinesFineIdResponses, DeleteApiGroupsGroupSlugFinesFineIdErrors, ThrowOnError>({
    url: '/api/groups/{groupSlug}/fines/{fineId}',
    ...options,
  });
};

/**
 * Get fine by ID
 *
 * Retrieve detailed information about a specific fine. Users can view their own fines, fines admins can view all fines for their group.
 */
export const getApiGroupsGroupSlugFinesFineId = <ThrowOnError extends boolean = false>(
  options: Options<GetApiGroupsGroupSlugFinesFineIdData, ThrowOnError>,
) => {
  return (options.client ?? client).get<GetApiGroupsGroupSlugFinesFineIdResponses, GetApiGroupsGroupSlugFinesFineIdErrors, ThrowOnError>({
    url: '/api/groups/{groupSlug}/fines/{fineId}',
    ...options,
  });
};

/**
 * Partially update fine
 *
 * Partially update a fine. Only provided fields will be updated. Users can add defense to their own fines. Fines admins can update status and approve/reject fines.
 */
export const patchApiGroupsGroupSlugFinesFineId = <ThrowOnError extends boolean = false>(
  options: Options<PatchApiGroupsGroupSlugFinesFineIdData, ThrowOnError>,
) => {
  return (options.client ?? client).patch<PatchApiGroupsGroupSlugFinesFineIdResponses, PatchApiGroupsGroupSlugFinesFineIdErrors, ThrowOnError>({
    url: '/api/groups/{groupSlug}/fines/{fineId}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * List group members
 *
 * Retrieve a list of all members in a group.
 */
export const getApiGroupsGroupSlugMembers = <ThrowOnError extends boolean = false>(options: Options<GetApiGroupsGroupSlugMembersData, ThrowOnError>) => {
  return (options.client ?? client).get<GetApiGroupsGroupSlugMembersResponses, GetApiGroupsGroupSlugMembersErrors, ThrowOnError>({
    url: '/api/groups/{groupSlug}/members',
    ...options,
  });
};

/**
 * Add member to group
 *
 * Add a member to a group. Requires 'groups:manage' permission.
 */
export const postApiGroupsGroupSlugMembers = <ThrowOnError extends boolean = false>(options: Options<PostApiGroupsGroupSlugMembersData, ThrowOnError>) => {
  return (options.client ?? client).post<PostApiGroupsGroupSlugMembersResponses, PostApiGroupsGroupSlugMembersErrors, ThrowOnError>({
    url: '/api/groups/{groupSlug}/members',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * Remove member from group
 *
 * Remove a member from a group. Requires 'groups:manage' permission.
 */
export const deleteApiGroupsGroupSlugMembersUserId = <ThrowOnError extends boolean = false>(
  options: Options<DeleteApiGroupsGroupSlugMembersUserIdData, ThrowOnError>,
) => {
  return (options.client ?? client).delete<DeleteApiGroupsGroupSlugMembersUserIdResponses, DeleteApiGroupsGroupSlugMembersUserIdErrors, ThrowOnError>({
    url: '/api/groups/{groupSlug}/members/{userId}',
    ...options,
  });
};

/**
 * Update member role
 *
 * Update a member's role in a group. Requires 'groups:manage' permission.
 */
export const patchApiGroupsGroupSlugMembersUserId = <ThrowOnError extends boolean = false>(
  options: Options<PatchApiGroupsGroupSlugMembersUserIdData, ThrowOnError>,
) => {
  return (options.client ?? client).patch<PatchApiGroupsGroupSlugMembersUserIdResponses, PatchApiGroupsGroupSlugMembersUserIdErrors, ThrowOnError>({
    url: '/api/groups/{groupSlug}/members/{userId}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * List group forms
 *
 * Get all forms for a group, filtered by user permissions
 */
export const getApiGroupsSlugForms = <ThrowOnError extends boolean = false>(options: Options<GetApiGroupsSlugFormsData, ThrowOnError>) => {
  return (options.client ?? client).get<GetApiGroupsSlugFormsResponses, GetApiGroupsSlugFormsErrors, ThrowOnError>({
    url: '/api/groups/{slug}/forms',
    ...options,
  });
};

/**
 * Create group form
 *
 * Create a form for a group. Requires group leader permission or forms:create permission.
 */
export const postApiGroupsSlugForms = <ThrowOnError extends boolean = false>(options: Options<PostApiGroupsSlugFormsData, ThrowOnError>) => {
  return (options.client ?? client).post<PostApiGroupsSlugFormsResponses, PostApiGroupsSlugFormsErrors, ThrowOnError>({
    url: '/api/groups/{slug}/forms',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * List news articles
 *
 * Get a paginated list of all news articles. Public endpoint.
 */
export const getApiNews = <ThrowOnError extends boolean = false>(options?: Options<GetApiNewsData, ThrowOnError>) => {
  return (options?.client ?? client).get<GetApiNewsResponses, unknown, ThrowOnError>({
    url: '/api/news',
    ...options,
  });
};

/**
 * Create news article
 *
 * Create a new news article. Requires 'news:create' permission.
 */
export const postApiNews = <ThrowOnError extends boolean = false>(options?: Options<PostApiNewsData, ThrowOnError>) => {
  return (options?.client ?? client).post<PostApiNewsResponses, PostApiNewsErrors, ThrowOnError>({
    url: '/api/news',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * Delete news article
 *
 * Delete a news article. Requires 'news:delete' or 'news:manage' permission (global or scoped) or being the creator.
 */
export const deleteApiNewsId = <ThrowOnError extends boolean = false>(options: Options<DeleteApiNewsIdData, ThrowOnError>) => {
  return (options.client ?? client).delete<DeleteApiNewsIdResponses, DeleteApiNewsIdErrors, ThrowOnError>({
    url: '/api/news/{id}',
    ...options,
  });
};

/**
 * Get news article
 *
 * Get a single news article by ID. Public endpoint.
 */
export const getApiNewsId = <ThrowOnError extends boolean = false>(options: Options<GetApiNewsIdData, ThrowOnError>) => {
  return (options.client ?? client).get<GetApiNewsIdResponses, GetApiNewsIdErrors, ThrowOnError>({
    url: '/api/news/{id}',
    ...options,
  });
};

/**
 * Update news article
 *
 * Update a news article. Requires 'news:update' or 'news:manage' permission (global or scoped) or being the creator.
 */
export const patchApiNewsId = <ThrowOnError extends boolean = false>(options: Options<PatchApiNewsIdData, ThrowOnError>) => {
  return (options.client ?? client).patch<PatchApiNewsIdResponses, PatchApiNewsIdErrors, ThrowOnError>({
    url: '/api/news/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * Remove reaction from news
 *
 * Remove your emoji reaction from a news article.
 */
export const deleteApiNewsIdReactions = <ThrowOnError extends boolean = false>(options: Options<DeleteApiNewsIdReactionsData, ThrowOnError>) => {
  return (options.client ?? client).delete<DeleteApiNewsIdReactionsResponses, DeleteApiNewsIdReactionsErrors, ThrowOnError>({
    url: '/api/news/{id}/reactions',
    ...options,
  });
};

/**
 * Add reaction to news
 *
 * Add or update emoji reaction to a news article. Requires authentication.
 */
export const postApiNewsIdReactions = <ThrowOnError extends boolean = false>(options: Options<PostApiNewsIdReactionsData, ThrowOnError>) => {
  return (options.client ?? client).post<PostApiNewsIdReactionsResponses, PostApiNewsIdReactionsErrors, ThrowOnError>({
    url: '/api/news/{id}/reactions',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * List job postings
 *
 * Get a list of job postings. Supports search and expired filtering. Public endpoint.
 */
export const getApiJobs = <ThrowOnError extends boolean = false>(options?: Options<GetApiJobsData, ThrowOnError>) => {
  return (options?.client ?? client).get<GetApiJobsResponses, unknown, ThrowOnError>({
    url: '/api/jobs',
    ...options,
  });
};

/**
 * Create job posting
 *
 * Create a new job posting. Requires 'jobs:create' permission.
 */
export const postApiJobs = <ThrowOnError extends boolean = false>(options?: Options<PostApiJobsData, ThrowOnError>) => {
  return (options?.client ?? client).post<PostApiJobsResponses, PostApiJobsErrors, ThrowOnError>({
    url: '/api/jobs',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * Delete job posting
 *
 * Delete a job posting. Requires 'jobs:delete' or 'jobs:manage' permission (global or scoped) or being the creator.
 */
export const deleteApiJobsId = <ThrowOnError extends boolean = false>(options: Options<DeleteApiJobsIdData, ThrowOnError>) => {
  return (options.client ?? client).delete<DeleteApiJobsIdResponses, DeleteApiJobsIdErrors, ThrowOnError>({
    url: '/api/jobs/{id}',
    ...options,
  });
};

/**
 * Get job posting
 *
 * Get a single job posting by ID. Public endpoint.
 */
export const getApiJobsId = <ThrowOnError extends boolean = false>(options: Options<GetApiJobsIdData, ThrowOnError>) => {
  return (options.client ?? client).get<GetApiJobsIdResponses, GetApiJobsIdErrors, ThrowOnError>({
    url: '/api/jobs/{id}',
    ...options,
  });
};

/**
 * Update job posting
 *
 * Update a job posting. Requires 'jobs:update' or 'jobs:manage' permission (global or scoped) or being the creator.
 */
export const patchApiJobsId = <ThrowOnError extends boolean = false>(options: Options<PatchApiJobsIdData, ThrowOnError>) => {
  return (options.client ?? client).patch<PatchApiJobsIdResponses, PatchApiJobsIdErrors, ThrowOnError>({
    url: '/api/jobs/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * Get current user settings
 *
 * Retrieve the authenticated user's settings including preferences and allergies.
 */
export const getApiUserMeSettings = <ThrowOnError extends boolean = false>(options?: Options<GetApiUserMeSettingsData, ThrowOnError>) => {
  return (options?.client ?? client).get<GetApiUserMeSettingsResponses, GetApiUserMeSettingsErrors, ThrowOnError>({
    url: '/api/user/me/settings',
    ...options,
  });
};

/**
 * Update user settings
 *
 * Partially update the authenticated user's settings. Only provided fields will be updated. User must have completed onboarding first.
 */
export const patchApiUserMeSettings = <ThrowOnError extends boolean = false>(options?: Options<PatchApiUserMeSettingsData, ThrowOnError>) => {
  return (options?.client ?? client).patch<PatchApiUserMeSettingsResponses, PatchApiUserMeSettingsErrors, ThrowOnError>({
    url: '/api/user/me/settings',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * Complete user onboarding
 *
 * Create initial user settings and mark the user as onboarded. Can only be called once per user.
 */
export const postApiUserMeSettings = <ThrowOnError extends boolean = false>(options?: Options<PostApiUserMeSettingsData, ThrowOnError>) => {
  return (options?.client ?? client).post<PostApiUserMeSettingsResponses, PostApiUserMeSettingsErrors, ThrowOnError>({
    url: '/api/user/me/settings',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * List all allergies
 *
 * Retrieve a list of all possible allergies that users can have.
 */
export const getApiUserAllergy = <ThrowOnError extends boolean = false>(options?: Options<GetApiUserAllergyData, ThrowOnError>) => {
  return (options?.client ?? client).get<GetApiUserAllergyResponses, unknown, ThrowOnError>({
    url: '/api/user/allergy',
    ...options,
  });
};
