// This file is auto-generated by @hey-api/openapi-ts

import type {
  GetApiApiKeysIdResponse,
  GetApiApiKeysResponse,
  GetApiEventFavoriteResponse,
  GetApiEventResponse,
  GetApiNotificationResponse,
  PatchApiApiKeysIdResponse,
  PatchApiNotificationIdReadResponse,
  PostApiApiKeysIdRegenerateResponse,
  PostApiApiKeysResponse,
  PostApiApiKeysValidateResponse,
} from './types.gen';

export const getApiApiKeysResponseTransformer = async (data: any): Promise<GetApiApiKeysResponse> => {
  data = data.map((item: any) => {
    if (item.lastUsedAt) {
      item.lastUsedAt = new Date(item.lastUsedAt);
    }
    item.createdAt = new Date(item.createdAt);
    item.updatedAt = new Date(item.updatedAt);
    return item;
  });
  return data;
};

export const postApiApiKeysResponseTransformer = async (data: any): Promise<PostApiApiKeysResponse> => {
  if (data.lastUsedAt) {
    data.lastUsedAt = new Date(data.lastUsedAt);
  }
  data.createdAt = new Date(data.createdAt);
  data.updatedAt = new Date(data.updatedAt);
  return data;
};

export const getApiApiKeysIdResponseTransformer = async (data: any): Promise<GetApiApiKeysIdResponse> => {
  if (data.lastUsedAt) {
    data.lastUsedAt = new Date(data.lastUsedAt);
  }
  data.createdAt = new Date(data.createdAt);
  data.updatedAt = new Date(data.updatedAt);
  return data;
};

export const patchApiApiKeysIdResponseTransformer = async (data: any): Promise<PatchApiApiKeysIdResponse> => {
  if (data.lastUsedAt) {
    data.lastUsedAt = new Date(data.lastUsedAt);
  }
  data.createdAt = new Date(data.createdAt);
  data.updatedAt = new Date(data.updatedAt);
  return data;
};

export const postApiApiKeysIdRegenerateResponseTransformer = async (data: any): Promise<PostApiApiKeysIdRegenerateResponse> => {
  if (data.lastUsedAt) {
    data.lastUsedAt = new Date(data.lastUsedAt);
  }
  data.createdAt = new Date(data.createdAt);
  data.updatedAt = new Date(data.updatedAt);
  return data;
};

export const postApiApiKeysValidateResponseTransformer = async (data: any): Promise<PostApiApiKeysValidateResponse> => {
  if (data.apiKey) {
    if (data.apiKey.lastUsedAt) {
      data.apiKey.lastUsedAt = new Date(data.apiKey.lastUsedAt);
    }
    data.apiKey.createdAt = new Date(data.apiKey.createdAt);
    data.apiKey.updatedAt = new Date(data.apiKey.updatedAt);
  }
  return data;
};

export const getApiEventResponseTransformer = async (data: any): Promise<GetApiEventResponse> => {
  data = data.map((item: any) => {
    item.startTime = new Date(item.startTime);
    item.endTime = new Date(item.endTime);
    item.createdAt = new Date(item.createdAt);
    item.updatedAt = new Date(item.updatedAt);
    return item;
  });
  return data;
};

export const getApiEventFavoriteResponseTransformer = async (data: any): Promise<GetApiEventFavoriteResponse> => {
  data = data.map((item: any) => {
    item.createdAt = new Date(item.createdAt);
    return item;
  });
  return data;
};

export const getApiNotificationResponseTransformer = async (data: any): Promise<GetApiNotificationResponse> => {
  data = data.map((item: any) => {
    item.createdAt = new Date(item.createdAt);
    item.updatedAt = new Date(item.updatedAt);
    return item;
  });
  return data;
};

export const patchApiNotificationIdReadResponseTransformer = async (data: any): Promise<PatchApiNotificationIdReadResponse> => {
  data.updatedAt = new Date(data.updatedAt);
  return data;
};
