// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: 'http://localhost:4000' | 'https://photon.tihlde.org' | (string & {});
};

export type GetApiApiKeysData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/api-keys';
};

export type GetApiApiKeysErrors = {
  /**
   * Forbidden - Missing api-keys:view permission
   */
  403: unknown;
};

export type GetApiApiKeysResponses = {
  /**
   * List of API keys
   */
  200: Array<{
    /**
     * API key ID
     */
    id: string;
    /**
     * Name of the API key
     */
    name: string;
    /**
     * Description of the API key
     */
    description: string;
    /**
     * First 12 characters of the key for display
     */
    keyPrefix: string;
    /**
     * User ID who created this key
     */
    createdById: string | null;
    /**
     * When the key was last used
     */
    lastUsedAt: string | null;
    /**
     * Array of permissions granted to this API key
     */
    permissions: Array<string>;
    /**
     * Optional metadata as key-value pairs
     */
    metadata: {
      [key: string]: unknown;
    } | null;
    /**
     * When the key was created
     */
    createdAt: string;
    /**
     * When the key was last updated
     */
    updatedAt: string;
  }>;
};

export type GetApiApiKeysResponse = GetApiApiKeysResponses[keyof GetApiApiKeysResponses];

export type PostApiApiKeysData = {
  body?: {
    /**
     * Name for the API key
     */
    name: string;
    /**
     * Detailed description of the API key's purpose
     */
    description: string;
    /**
     * Array of permissions granted to this API key (e.g., ['email:send', 'news:create']). Service validates against allowed permissions.
     */
    permissions: Array<string>;
    /**
     * Optional metadata as key-value pairs
     */
    metadata?: {
      [key: string]: unknown;
    };
  };
  path?: never;
  query?: never;
  url: '/api/api-keys';
};

export type PostApiApiKeysErrors = {
  /**
   * Forbidden - Missing api-keys:create permission
   */
  403: unknown;
};

export type PostApiApiKeysResponses = {
  /**
   * API key created successfully. The 'key' field contains the full API key and will not be shown again.
   */
  201: {
    /**
     * API key ID
     */
    id: string;
    /**
     * Name of the API key
     */
    name: string;
    /**
     * Description of the API key
     */
    description: string;
    /**
     * First 12 characters of the key for display
     */
    keyPrefix: string;
    /**
     * User ID who created this key
     */
    createdById: string | null;
    /**
     * When the key was last used
     */
    lastUsedAt: string | null;
    /**
     * Array of permissions granted to this API key
     */
    permissions: Array<string>;
    /**
     * Optional metadata as key-value pairs
     */
    metadata: {
      [key: string]: unknown;
    } | null;
    /**
     * When the key was created
     */
    createdAt: string;
    /**
     * When the key was last updated
     */
    updatedAt: string;
    /**
     * The full API key - ONLY returned on creation and regeneration. Cannot be retrieved again.
     */
    key: string;
  };
};

export type PostApiApiKeysResponse = PostApiApiKeysResponses[keyof PostApiApiKeysResponses];

export type DeleteApiApiKeysIdData = {
  body?: never;
  path: {
    /**
     * API key ID
     */
    id: string;
  };
  query?: never;
  url: '/api/api-keys/{id}';
};

export type DeleteApiApiKeysIdErrors = {
  /**
   * Forbidden - Missing api-keys:delete permission
   */
  403: unknown;
  /**
   * API key not found
   */
  404: unknown;
};

export type DeleteApiApiKeysIdResponses = {
  /**
   * API key deleted successfully
   */
  200: {
    /**
     * Success message
     */
    message: string;
  };
};

export type DeleteApiApiKeysIdResponse = DeleteApiApiKeysIdResponses[keyof DeleteApiApiKeysIdResponses];

export type GetApiApiKeysIdData = {
  body?: never;
  path: {
    /**
     * API key ID
     */
    id: string;
  };
  query?: never;
  url: '/api/api-keys/{id}';
};

export type GetApiApiKeysIdErrors = {
  /**
   * Forbidden - Missing api-keys:view permission
   */
  403: unknown;
  /**
   * API key not found
   */
  404: unknown;
};

export type GetApiApiKeysIdResponses = {
  /**
   * API key details
   */
  200: {
    /**
     * API key ID
     */
    id: string;
    /**
     * Name of the API key
     */
    name: string;
    /**
     * Description of the API key
     */
    description: string;
    /**
     * First 12 characters of the key for display
     */
    keyPrefix: string;
    /**
     * User ID who created this key
     */
    createdById: string | null;
    /**
     * When the key was last used
     */
    lastUsedAt: string | null;
    /**
     * Array of permissions granted to this API key
     */
    permissions: Array<string>;
    /**
     * Optional metadata as key-value pairs
     */
    metadata: {
      [key: string]: unknown;
    } | null;
    /**
     * When the key was created
     */
    createdAt: string;
    /**
     * When the key was last updated
     */
    updatedAt: string;
  };
};

export type GetApiApiKeysIdResponse = GetApiApiKeysIdResponses[keyof GetApiApiKeysIdResponses];

export type PatchApiApiKeysIdData = {
  body?: {
    /**
     * Name for the API key
     */
    name?: string;
    /**
     * Detailed description of the API key's purpose
     */
    description?: string;
    /**
     * Array of permissions granted to this API key
     */
    permissions?: Array<string>;
    /**
     * Optional metadata as key-value pairs
     */
    metadata?: {
      [key: string]: unknown;
    };
  };
  path: {
    /**
     * API key ID
     */
    id: string;
  };
  query?: never;
  url: '/api/api-keys/{id}';
};

export type PatchApiApiKeysIdErrors = {
  /**
   * Forbidden - Missing api-keys:update permission
   */
  403: unknown;
  /**
   * API key not found
   */
  404: unknown;
};

export type PatchApiApiKeysIdResponses = {
  /**
   * API key updated successfully
   */
  200: {
    /**
     * API key ID
     */
    id: string;
    /**
     * Name of the API key
     */
    name: string;
    /**
     * Description of the API key
     */
    description: string;
    /**
     * First 12 characters of the key for display
     */
    keyPrefix: string;
    /**
     * User ID who created this key
     */
    createdById: string | null;
    /**
     * When the key was last used
     */
    lastUsedAt: string | null;
    /**
     * Array of permissions granted to this API key
     */
    permissions: Array<string>;
    /**
     * Optional metadata as key-value pairs
     */
    metadata: {
      [key: string]: unknown;
    } | null;
    /**
     * When the key was created
     */
    createdAt: string;
    /**
     * When the key was last updated
     */
    updatedAt: string;
  };
};

export type PatchApiApiKeysIdResponse = PatchApiApiKeysIdResponses[keyof PatchApiApiKeysIdResponses];

export type PostApiApiKeysIdRegenerateData = {
  body?: never;
  path: {
    /**
     * API key ID
     */
    id: string;
  };
  query?: never;
  url: '/api/api-keys/{id}/regenerate';
};

export type PostApiApiKeysIdRegenerateErrors = {
  /**
   * Forbidden - Missing api-keys:update permission
   */
  403: unknown;
  /**
   * API key not found
   */
  404: unknown;
};

export type PostApiApiKeysIdRegenerateResponses = {
  /**
   * API key regenerated successfully. The 'key' field contains the new API key and will not be shown again.
   */
  200: {
    /**
     * API key ID
     */
    id: string;
    /**
     * Name of the API key
     */
    name: string;
    /**
     * Description of the API key
     */
    description: string;
    /**
     * First 12 characters of the key for display
     */
    keyPrefix: string;
    /**
     * User ID who created this key
     */
    createdById: string | null;
    /**
     * When the key was last used
     */
    lastUsedAt: string | null;
    /**
     * Array of permissions granted to this API key
     */
    permissions: Array<string>;
    /**
     * Optional metadata as key-value pairs
     */
    metadata: {
      [key: string]: unknown;
    } | null;
    /**
     * When the key was created
     */
    createdAt: string;
    /**
     * When the key was last updated
     */
    updatedAt: string;
    /**
     * The full API key - ONLY returned on creation and regeneration. Cannot be retrieved again.
     */
    key: string;
  };
};

export type PostApiApiKeysIdRegenerateResponse = PostApiApiKeysIdRegenerateResponses[keyof PostApiApiKeysIdRegenerateResponses];

export type PostApiApiKeysValidateData = {
  body?: {
    /**
     * The API key to validate
     */
    key: string;
  };
  path?: never;
  query?: never;
  url: '/api/api-keys/validate';
};

export type PostApiApiKeysValidateResponses = {
  /**
   * Validation result. If valid=true, includes the API key details and permissions.
   */
  200: {
    /**
     * Whether the API key is valid
     */
    valid: boolean;
    /**
     * The API key details and permissions if valid. Undefined if invalid.
     */
    apiKey?: {
      /**
       * API key ID
       */
      id: string;
      /**
       * Name of the API key
       */
      name: string;
      /**
       * Description of the API key
       */
      description: string;
      /**
       * First 12 characters of the key for display
       */
      keyPrefix: string;
      /**
       * User ID who created this key
       */
      createdById: string | null;
      /**
       * When the key was last used
       */
      lastUsedAt: string | null;
      /**
       * Array of permissions granted to this API key
       */
      permissions: Array<string>;
      /**
       * Optional metadata as key-value pairs
       */
      metadata: {
        [key: string]: unknown;
      } | null;
      /**
       * When the key was created
       */
      createdAt: string;
      /**
       * When the key was last updated
       */
      updatedAt: string;
    };
  };
};

export type PostApiApiKeysValidateResponse = PostApiApiKeysValidateResponses[keyof PostApiApiKeysValidateResponses];

export type PostApiEmailSendData = {
  body?: {
    /**
     * Recipient email address (string) or list of recipient email addresses (array)
     */
    to: string | Array<string>;
    /**
     * Email subject line
     */
    subject: string;
    /**
     * Array of content blocks (title, text, or button) to render in the email
     */
    content: Array<
      | {
          /**
           * Content block type
           */
          type: 'title';
          /**
           * The title text to display
           */
          content: string;
        }
      | {
          /**
           * Content block type
           */
          type: 'text';
          /**
           * The paragraph text to display
           */
          content: string;
        }
      | {
          /**
           * Content block type
           */
          type: 'button';
          /**
           * The button label text
           */
          text: string;
          /**
           * The URL the button links to
           */
          url: string;
        }
    >;
  };
  path?: never;
  query?: never;
  url: '/api/email/send';
};

export type PostApiEmailSendErrors = {
  /**
   * Missing or invalid Authorization header
   */
  401: unknown;
  /**
   * Invalid API key
   */
  403: unknown;
  /**
   * Email API not configured
   */
  503: unknown;
};

export type PostApiEmailSendResponses = {
  /**
   * Email queued successfully
   */
  200: {
    success: boolean;
    message: string;
    jobIds: Array<string>;
    recipientCount: number;
  };
};

export type PostApiEmailSendResponse = PostApiEmailSendResponses[keyof PostApiEmailSendResponses];

export type GetApiEventData = {
  body?: never;
  path?: never;
  query?: {
    limit?: number;
    offset?: number;
  };
  url: '/api/event';
};

export type GetApiEventResponses = {
  /**
   * OK
   */
  200: Array<{
    /**
     * Event ID
     */
    id: string;
    /**
     * Event slug
     */
    slug: string;
    /**
     * Event title
     */
    title: string;
    /**
     * Event location (nullable)
     */
    location?: string | null;
    /**
     * Event start time (ISO 8601)
     */
    startTime: string;
    /**
     * Event end time (ISO 8601)
     */
    endTime: string;
    /**
     * Event organizer (nullable)
     */
    organizer: {
      /**
       * Organizer name
       */
      name: string;
      /**
       * Organizer slug
       */
      slug: string;
      /**
       * Organizer type
       */
      type: string;
    } | null;
    /**
     * Is registration closed
     */
    closed: boolean;
    /**
     * Event image URL (nullable)
     */
    image: string | null;
    /**
     * Event creation time (ISO 8601)
     */
    createdAt: string;
    /**
     * Event update time (ISO 8601)
     */
    updatedAt: string;
    /**
     * Event category
     */
    category: {
      /**
       * Category slug
       */
      slug: string;
      /**
       * Category label
       */
      label: string;
    };
  }>;
};

export type GetApiEventResponse = GetApiEventResponses[keyof GetApiEventResponses];

export type PostApiEventData = {
  body?: {
    /**
     * Short title of the event
     */
    title: string;
    /**
     * Description of the event
     */
    description: string;
    /**
     * Category slug for the event
     */
    categorySlug: string;
    /**
     * Slug of the group organizing the event
     */
    organizerGroupSlug: string;
    /**
     * Location of the event (physical or online)
     */
    location: string;
    /**
     * Main image to display for the event
     */
    imageUrl: string | null;
    /**
     * When the event starts
     */
    start: string;
    /**
     * When the event ends
     */
    end: string;
    /**
     * Timestamp for when registrations open. If null, open immediately.
     */
    registrationStart: string | null;
    /**
     * When the registration for the event ends. After this time, users cannot sign up.
     */
    registrationEnd: string;
    /**
     * Deadline timestamp for when users cannot cancel anymore. After this, no-shows may receive strikes.
     */
    cancellationDeadline: string | null;
    /**
     * Maximum number of participants allowed. If null, no capacity limit.
     */
    capacity: number | null;
    /**
     * Is the event closed for new registrations? This overrides registrationStart/End
     */
    isRegistrationClosed: boolean;
    /**
     * Do users need to sign up to attend the event?
     */
    requiresSigningUp: boolean;
    /**
     * Should users be allowed to join a waitlist if the event is full?
     */
    allowWaitlist: boolean;
    /**
     * List of priority pools, with priority in descending order. Each pool contains a list of group slugs. Users in groups in the first pool have highest priority, then second pool, etc. Users not in any pool have lowest priority.
     */
    priorityPools: Array<{
      /**
       * Group slugs in this pool
       */
      groups: Array<string>;
    }> | null;
    /**
     * Only allow users in at least one priority pool to sign up. Can only be true if at least one group is in priorityPools.
     */
    onlyAllowPrioritized: boolean;
    /**
     * Can this event give strike penalties to users?
     */
    canCauseStrikes: boolean;
    /**
     * Should the system enforce strike rules for this event?
     */
    enforcesPreviousStrikes: boolean;
    /**
     * Is this a paid event?
     */
    isPaidEvent: boolean;
    /**
     * Price in NOK for attending the event. Can only be set if isPaidEvent is true.
     */
    price: number | null;
    /**
     * The time (in minutes) between sign up and payment must be made. After this period, unpaid registrations are cancelled. Can only be set if isPaidEvent is true.
     */
    paymentGracePeriodMinutes: number | null;
    /**
     * User ID of the primary contact person for the event
     */
    contactPersonUserId: string | null;
    /**
     * Should users be able to react to this event with emojis?
     */
    reactionsAllowed: boolean;
  };
  path?: never;
  query?: never;
  url: '/api/event';
};

export type PostApiEventErrors = {
  /**
   * Forbidden - Missing events:create permission
   */
  403: unknown;
};

export type PostApiEventResponses = {
  /**
   * Created
   */
  201: {
    eventId: string;
  };
};

export type PostApiEventResponse = PostApiEventResponses[keyof PostApiEventResponses];

export type PutApiEventIdData = {
  body?: {
    /**
     * Short title of the event
     */
    title?: string;
    /**
     * Description of the event
     */
    description?: string;
    /**
     * Category slug for the event
     */
    categorySlug?: string;
    /**
     * Slug of the group organizing the event
     */
    organizerGroupSlug?: string;
    /**
     * Location of the event (physical or online)
     */
    location?: string;
    /**
     * Main image to display for the event
     */
    imageUrl?: string | null;
    /**
     * When the event starts
     */
    start?: string;
    /**
     * When the event ends
     */
    end?: string;
    /**
     * Timestamp for when registrations open. If null, open immediately.
     */
    registrationStart?: string | null;
    /**
     * When the registration for the event ends. After this time, users cannot sign up.
     */
    registrationEnd?: string;
    /**
     * Deadline timestamp for when users cannot cancel anymore. After this, no-shows may receive strikes.
     */
    cancellationDeadline?: string | null;
    /**
     * Maximum number of participants allowed. If null, no capacity limit.
     */
    capacity?: number | null;
    /**
     * Is the event closed for new registrations? This overrides registrationStart/End
     */
    isRegistrationClosed?: boolean;
    /**
     * Do users need to sign up to attend the event?
     */
    requiresSigningUp?: boolean;
    /**
     * Should users be allowed to join a waitlist if the event is full?
     */
    allowWaitlist?: boolean;
    /**
     * List of priority pools, with priority in descending order. Each pool contains a list of group slugs. Users in groups in the first pool have highest priority, then second pool, etc. Users not in any pool have lowest priority.
     */
    priorityPools?: Array<{
      /**
       * Group slugs in this pool
       */
      groups: Array<string>;
    }> | null;
    /**
     * Only allow users in at least one priority pool to sign up. Can only be true if at least one group is in priorityPools.
     */
    onlyAllowPrioritized?: boolean;
    /**
     * Can this event give strike penalties to users?
     */
    canCauseStrikes?: boolean;
    /**
     * Should the system enforce strike rules for this event?
     */
    enforcesPreviousStrikes?: boolean;
    /**
     * Is this a paid event?
     */
    isPaidEvent?: boolean;
    /**
     * Price in NOK for attending the event. Can only be set if isPaidEvent is true.
     */
    price?: number | null;
    /**
     * The time (in minutes) between sign up and payment must be made. After this period, unpaid registrations are cancelled. Can only be set if isPaidEvent is true.
     */
    paymentGracePeriodMinutes?: number | null;
    /**
     * User ID of the primary contact person for the event
     */
    contactPersonUserId?: string | null;
    /**
     * Should users be able to react to this event with emojis?
     */
    reactionsAllowed?: boolean;
  };
  path: {
    id: string;
  };
  query?: never;
  url: '/api/event/{id}';
};

export type PutApiEventIdErrors = {
  /**
   * Forbidden - You must be the event creator or have events:update/events:manage permission
   */
  403: unknown;
  /**
   * Not found
   */
  404: unknown;
};

export type PutApiEventIdResponses = {
  /**
   * Updated
   */
  200: unknown;
};

export type DeleteApiEventEventIdData = {
  body?: never;
  path: {
    eventId: string;
  };
  query?: never;
  url: '/api/event/{eventId}';
};

export type DeleteApiEventEventIdErrors = {
  /**
   * Forbidden - You must be the event creator or have events:delete permission
   */
  403: unknown;
  /**
   * Not Found - Event with the specified ID does not exist
   */
  404: unknown;
};

export type DeleteApiEventEventIdResponses = {
  /**
   * Event successfully deleted
   */
  200: unknown;
};

export type PutApiEventFavoriteIdData = {
  body?: {
    /**
     * Is favorite
     */
    isFavorite: boolean;
  };
  path: {
    id: string;
  };
  query?: never;
  url: '/api/event/favorite/{id}';
};

export type PutApiEventFavoriteIdErrors = {
  /**
   * Not found
   */
  404: unknown;
};

export type PutApiEventFavoriteIdResponses = {
  /**
   * Updated
   */
  200: unknown;
};

export type GetApiEventFavoriteData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/event/favorite';
};

export type GetApiEventFavoriteResponses = {
  /**
   * List of favorite events
   */
  200: Array<{
    /**
     * Event ID
     */
    eventId: string;
    /**
     * Event title
     */
    title: string;
    /**
     * Event slug
     */
    slug: string;
    /**
     * When you added this event to your favorites
     */
    createdAt: string;
  }>;
};

export type GetApiEventFavoriteResponse = GetApiEventFavoriteResponses[keyof GetApiEventFavoriteResponses];

export type DeleteApiEventEventIdRegistrationData = {
  body?: never;
  path: {
    eventId: string;
  };
  query?: never;
  url: '/api/event/{eventId}/registration';
};

export type DeleteApiEventEventIdRegistrationResponses = {
  /**
   * OK
   */
  200: {
    [key: string]: unknown;
  };
};

export type DeleteApiEventEventIdRegistrationResponse = DeleteApiEventEventIdRegistrationResponses[keyof DeleteApiEventEventIdRegistrationResponses];

export type GetApiEventEventIdRegistrationData = {
  body?: never;
  path: {
    eventId: string;
  };
  query?: {
    limit?: number;
    offset?: number;
  };
  url: '/api/event/{eventId}/registration';
};

export type GetApiEventEventIdRegistrationResponses = {
  /**
   * OK
   */
  200: Array<{
    registeredUsers: Array<{
      /**
       * User id
       */
      id: string;
      /**
       * User name
       */
      name: string;
      /**
       * User image url (if any)
       */
      image: string | null;
    }>;
    /**
     * Total registered users. These users have access to the event.
     */
    registeredCount: number;
    /**
     * Number of users on the waitlist. These users are waiting in queue for a spot.
     */
    waitlistCount: number;
  }>;
};

export type GetApiEventEventIdRegistrationResponse = GetApiEventEventIdRegistrationResponses[keyof GetApiEventEventIdRegistrationResponses];

export type PostApiEventEventIdRegistrationData = {
  body?: never;
  path: {
    eventId: string;
  };
  query?: never;
  url: '/api/event/{eventId}/registration';
};

export type PostApiEventEventIdRegistrationErrors = {
  /**
   * Event not found
   */
  404: unknown;
  /**
   * Event is not open for registration or user already registered
   */
  409: unknown;
};

export type PostApiEventEventIdRegistrationResponses = {
  /**
   * OK
   */
  200: {
    eventId: string;
    userId: string;
    status: 'pending';
    createdAt: string;
  };
};

export type PostApiEventEventIdRegistrationResponse = PostApiEventEventIdRegistrationResponses[keyof PostApiEventEventIdRegistrationResponses];

export type PostApiEventEventIdPaymentData = {
  body?: {
    /**
     * URL to redirect user after payment
     */
    returnUrl: string;
    /**
     * User flow type for payment
     */
    userFlow?: 'WEB_REDIRECT' | 'NATIVE_REDIRECT';
  };
  path: {
    eventId: string;
  };
  query?: never;
  url: '/api/event/{eventId}/payment';
};

export type PostApiEventEventIdPaymentErrors = {
  /**
   * Bad request - event not found or not a paid event
   */
  400: unknown;
  /**
   * Event or registration not found
   */
  404: unknown;
  /**
   * Payment already exists for this user and event
   */
  409: unknown;
};

export type PostApiEventEventIdPaymentResponses = {
  /**
   * Payment created successfully
   */
  201: {
    eventId: string;
    userId: string;
    checkoutUrl: string;
    amount: number;
    currency: string;
  };
};

export type PostApiEventEventIdPaymentResponse = PostApiEventEventIdPaymentResponses[keyof PostApiEventEventIdPaymentResponses];

export type PostApiEventPaymentWebhookData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/event/payment/webhook';
};

export type PostApiEventPaymentWebhookErrors = {
  /**
   * Invalid webhook payload
   */
  400: unknown;
  /**
   * Payment not found
   */
  404: unknown;
};

export type PostApiEventPaymentWebhookResponses = {
  /**
   * Webhook processed successfully
   */
  200: unknown;
};

export type GetApiEventEventIdFormsData = {
  body?: never;
  path: {
    eventId: string;
  };
  query?: never;
  url: '/api/event/{eventId}/forms';
};

export type GetApiEventEventIdFormsErrors = {
  /**
   * Event not found
   */
  404: unknown;
};

export type GetApiEventEventIdFormsResponses = {
  /**
   * Success
   */
  200: Array<{
    id: string;
    title: string;
    description: string | null;
    type: 'survey' | 'evaluation';
    resource_type: string;
    viewer_has_answered: boolean;
    created_at: string;
    updated_at: string;
  }>;
};

export type GetApiEventEventIdFormsResponse = GetApiEventEventIdFormsResponses[keyof GetApiEventEventIdFormsResponses];

export type PostApiEventEventIdFormsData = {
  body?: {
    title: string;
    description?: string;
    template?: boolean;
    fields?: Array<{
      title: string;
      type: 'text_answer' | 'multiple_select' | 'single_select';
      required?: boolean;
      order?: number;
      options?: Array<{
        title: string;
        order?: number;
      }>;
    }>;
    event: string;
    type: 'survey' | 'evaluation';
  };
  path: {
    eventId: string;
  };
  query?: never;
  url: '/api/event/{eventId}/forms';
};

export type PostApiEventEventIdFormsErrors = {
  /**
   * Bad request - Form already exists for this event type
   */
  400: unknown;
  /**
   * Forbidden
   */
  403: unknown;
  /**
   * Event not found
   */
  404: unknown;
};

export type PostApiEventEventIdFormsResponses = {
  /**
   * Created
   */
  201: unknown;
};

export type GetApiEventEventIdFormsTypeData = {
  body?: never;
  path: {
    eventId: string;
    type: string;
  };
  query?: never;
  url: '/api/event/{eventId}/forms/{type}';
};

export type GetApiEventEventIdFormsTypeErrors = {
  /**
   * Forbidden - Evaluation forms require attendance
   */
  403: unknown;
  /**
   * Form not found
   */
  404: unknown;
};

export type GetApiEventEventIdFormsTypeResponses = {
  /**
   * Success
   */
  200: {
    id: string;
    title: string;
    description: string | null;
    type: 'survey' | 'evaluation';
    resource_type: string;
    viewer_has_answered: boolean;
    website_url: string;
    created_at: string;
    updated_at: string;
    fields: Array<{
      id: string;
      title: string;
      type: 'text_answer' | 'multiple_select' | 'single_select';
      required: boolean;
      order: number;
      options: Array<{
        id: string;
        title: string;
        order: number;
      }>;
    }>;
  };
};

export type GetApiEventEventIdFormsTypeResponse = GetApiEventEventIdFormsTypeResponses[keyof GetApiEventEventIdFormsTypeResponses];

export type GetApiFormsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/forms';
};

export type GetApiFormsResponses = {
  /**
   * Success
   */
  200: Array<{
    id: string;
    title: string;
    description: string | null;
    template: boolean;
    resource_type: string;
    viewer_has_answered: boolean;
    created_at: string;
    updated_at: string;
  }>;
};

export type GetApiFormsResponse = GetApiFormsResponses[keyof GetApiFormsResponses];

export type PostApiFormsData = {
  body?: {
    title: string;
    description?: string;
    template?: boolean;
    fields?: Array<{
      title: string;
      type: 'text_answer' | 'multiple_select' | 'single_select';
      required?: boolean;
      order?: number;
      options?: Array<{
        title: string;
        order?: number;
      }>;
    }>;
  };
  path?: never;
  query?: never;
  url: '/api/forms';
};

export type PostApiFormsErrors = {
  /**
   * Forbidden - Missing forms:create permission
   */
  403: unknown;
};

export type PostApiFormsResponses = {
  /**
   * Created
   */
  201: {
    id: string;
    title: string;
    description: string | null;
    template: boolean;
    created_at: string;
    updated_at: string;
  };
};

export type PostApiFormsResponse = PostApiFormsResponses[keyof PostApiFormsResponses];

export type DeleteApiFormsIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/api/forms/{id}';
};

export type DeleteApiFormsIdErrors = {
  /**
   * Forbidden
   */
  403: unknown;
  /**
   * Form not found
   */
  404: unknown;
};

export type DeleteApiFormsIdResponses = {
  /**
   * Success
   */
  200: unknown;
};

export type GetApiFormsIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/api/forms/{id}';
};

export type GetApiFormsIdErrors = {
  /**
   * Form not found
   */
  404: unknown;
};

export type GetApiFormsIdResponses = {
  /**
   * Success
   */
  200: {
    id: string;
    title: string;
    description: string | null;
    template: boolean;
    resource_type: string;
    viewer_has_answered: boolean;
    website_url: string;
    created_at: string;
    updated_at: string;
    fields: Array<{
      id: string;
      title: string;
      type: 'text_answer' | 'multiple_select' | 'single_select';
      required: boolean;
      order: number;
      options: Array<{
        id: string;
        title: string;
        order: number;
      }>;
    }>;
  };
};

export type GetApiFormsIdResponse = GetApiFormsIdResponses[keyof GetApiFormsIdResponses];

export type PatchApiFormsIdData = {
  body?: {
    title?: string;
    description?: string;
    template?: boolean;
    fields?: Array<{
      id?: string;
      title: string;
      type: 'text_answer' | 'multiple_select' | 'single_select';
      required?: boolean;
      order?: number;
      options?: Array<{
        id?: string;
        title: string;
        order?: number;
      }>;
    }>;
  };
  path: {
    id: string;
  };
  query?: never;
  url: '/api/forms/{id}';
};

export type PatchApiFormsIdErrors = {
  /**
   * Forbidden
   */
  403: unknown;
  /**
   * Form not found
   */
  404: unknown;
};

export type PatchApiFormsIdResponses = {
  /**
   * Success
   */
  200: unknown;
};

export type GetApiFormsIdStatisticsData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/api/forms/{id}/statistics';
};

export type GetApiFormsIdStatisticsErrors = {
  /**
   * Forbidden
   */
  403: unknown;
  /**
   * Form not found
   */
  404: unknown;
};

export type GetApiFormsIdStatisticsResponses = {
  /**
   * Success
   */
  200: {
    id: string;
    title: string;
    resource_type: string;
    statistics: Array<{
      id: string;
      title: string;
      type: 'multiple_select' | 'single_select';
      required: boolean;
      options: Array<{
        id: string;
        title: string;
        answer_amount: number;
        answer_percentage: number;
      }>;
    }>;
  };
};

export type GetApiFormsIdStatisticsResponse = GetApiFormsIdStatisticsResponses[keyof GetApiFormsIdStatisticsResponses];

export type GetApiFormsFormIdSubmissionsData = {
  body?: never;
  path: {
    formId: string;
  };
  query?: never;
  url: '/api/forms/{formId}/submissions';
};

export type GetApiFormsFormIdSubmissionsErrors = {
  /**
   * Forbidden
   */
  403: unknown;
  /**
   * Form not found
   */
  404: unknown;
};

export type GetApiFormsFormIdSubmissionsResponses = {
  /**
   * Success
   */
  200: Array<{
    id: string;
    user: {
      id: string;
      name: string;
      email: string;
    };
    created_at: string;
    updated_at: string;
    answers: Array<{
      id: string;
      field_id: string | null;
      answer_text: string | null;
      selected_options: Array<{
        id: string;
        title: string;
      }>;
    }>;
  }>;
};

export type GetApiFormsFormIdSubmissionsResponse = GetApiFormsFormIdSubmissionsResponses[keyof GetApiFormsFormIdSubmissionsResponses];

export type PostApiFormsFormIdSubmissionsData = {
  body?: {
    answers: Array<{
      field: {
        id: string;
      };
      answer_text?: string;
      selected_options?: Array<{
        id: string;
      }>;
    }>;
  };
  path: {
    formId: string;
  };
  query?: never;
  url: '/api/forms/{formId}/submissions';
};

export type PostApiFormsFormIdSubmissionsErrors = {
  /**
   * Forbidden - Cannot submit to this form
   */
  403: unknown;
  /**
   * Form not found
   */
  404: unknown;
  /**
   * Conflict - Duplicate submission not allowed
   */
  409: unknown;
};

export type PostApiFormsFormIdSubmissionsResponses = {
  /**
   * Created
   */
  201: unknown;
};

export type GetApiFormsFormIdSubmissionsIdData = {
  body?: never;
  path: {
    formId: string;
    id: string;
  };
  query?: never;
  url: '/api/forms/{formId}/submissions/{id}';
};

export type GetApiFormsFormIdSubmissionsIdErrors = {
  /**
   * Forbidden
   */
  403: unknown;
  /**
   * Submission not found
   */
  404: unknown;
};

export type GetApiFormsFormIdSubmissionsIdResponses = {
  /**
   * Success
   */
  200: {
    id: string;
    user: {
      id: string;
      name: string;
      email: string;
    };
    created_at: string;
    updated_at: string;
    answers: Array<{
      id: string;
      field_id: string | null;
      answer_text: string | null;
      selected_options: Array<{
        id: string;
        title: string;
      }>;
    }>;
  };
};

export type GetApiFormsFormIdSubmissionsIdResponse = GetApiFormsFormIdSubmissionsIdResponses[keyof GetApiFormsFormIdSubmissionsIdResponses];

export type GetApiFormsFormIdSubmissionsDownloadData = {
  body?: never;
  path: {
    formId: string;
  };
  query?: never;
  url: '/api/forms/{formId}/submissions/download';
};

export type GetApiFormsFormIdSubmissionsDownloadErrors = {
  /**
   * Forbidden
   */
  403: unknown;
  /**
   * Form not found
   */
  404: unknown;
};

export type GetApiFormsFormIdSubmissionsDownloadResponses = {
  /**
   * Success - Returns CSV file
   */
  200: unknown;
};

export type DeleteApiFormsFormIdSubmissionsIdDestroyWithReasonData = {
  body?: {
    reason: string;
  };
  path: {
    formId: string;
    id: string;
  };
  query?: never;
  url: '/api/forms/{formId}/submissions/{id}/destroy_with_reason';
};

export type DeleteApiFormsFormIdSubmissionsIdDestroyWithReasonErrors = {
  /**
   * Submission not found
   */
  404: unknown;
};

export type DeleteApiFormsFormIdSubmissionsIdDestroyWithReasonResponses = {
  /**
   * Success
   */
  200: unknown;
};

export type GetApiNotificationData = {
  body?: never;
  path?: never;
  query?: {
    limit?: number;
    offset?: number;
  };
  url: '/api/notification';
};

export type GetApiNotificationErrors = {
  /**
   * Unauthorized - user not authenticated
   */
  401: unknown;
};

export type GetApiNotificationResponses = {
  /**
   * OK
   */
  200: Array<{
    /**
     * Notification ID
     */
    id: string;
    /**
     * User ID
     */
    userId: string;
    /**
     * Notification title
     */
    title: string;
    /**
     * Notification description
     */
    description: string;
    /**
     * Optional link URL (nullable)
     */
    link: string | null;
    /**
     * Whether notification is read
     */
    isRead: boolean;
    /**
     * Notification creation time (ISO 8601)
     */
    createdAt: string;
    /**
     * Notification update time (ISO 8601)
     */
    updatedAt: string;
  }>;
};

export type GetApiNotificationResponse = GetApiNotificationResponses[keyof GetApiNotificationResponses];

export type DeleteApiNotificationIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/api/notification/{id}';
};

export type DeleteApiNotificationIdErrors = {
  /**
   * Unauthorized - user not authenticated
   */
  401: unknown;
  /**
   * Notification not found or not owned by user
   */
  404: unknown;
};

export type DeleteApiNotificationIdResponses = {
  /**
   * Notification deleted successfully
   */
  200: {
    /**
     * Whether deletion was successful
     */
    success: boolean;
  };
};

export type DeleteApiNotificationIdResponse = DeleteApiNotificationIdResponses[keyof DeleteApiNotificationIdResponses];

export type PatchApiNotificationIdReadData = {
  body?: {
    /**
     * Whether notification should be marked as read
     */
    isRead: boolean;
  };
  path: {
    id: string;
  };
  query?: never;
  url: '/api/notification/{id}/read';
};

export type PatchApiNotificationIdReadErrors = {
  /**
   * Unauthorized - user not authenticated
   */
  401: unknown;
  /**
   * Notification not found or not owned by user
   */
  404: unknown;
};

export type PatchApiNotificationIdReadResponses = {
  /**
   * Notification updated successfully
   */
  200: {
    /**
     * Notification ID
     */
    id: string;
    /**
     * Updated read status
     */
    isRead: boolean;
    /**
     * Notification update time (ISO 8601)
     */
    updatedAt: string;
  };
};

export type PatchApiNotificationIdReadResponse = PatchApiNotificationIdReadResponses[keyof PatchApiNotificationIdReadResponses];

export type GetApiGroupsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/groups';
};

export type GetApiGroupsResponses = {
  /**
   * List of groups retrieved successfully
   */
  200: Array<{
    /**
     * Group slug
     */
    slug: string;
    /**
     * Group image URL
     */
    imageUrl: string | null;
    /**
     * Group name
     */
    name: string;
    /**
     * Group description
     */
    description: string | null;
    /**
     * Group contact email
     */
    contactEmail: string | null;
    /**
     * Group type
     */
    type: string;
    /**
     * Group fines info
     */
    finesInfo: string;
    /**
     * Group fines activated
     */
    finesActivated: boolean;
    /**
     * Group fines admin ID
     */
    finesAdminId: string | null;
    /**
     * Creation timestamp
     */
    createdAt: string;
    /**
     * Last update timestamp
     */
    updatedAt: string;
  }>;
};

export type GetApiGroupsResponse = GetApiGroupsResponses[keyof GetApiGroupsResponses];

export type PostApiGroupsData = {
  body?: {
    /**
     * Unique group slug identifier
     */
    slug: string;
    /**
     * Group image URL
     */
    imageUrl?: string;
    /**
     * Group name
     */
    name: string;
    /**
     * Group description
     */
    description?: string;
    /**
     * Group contact email
     */
    contactEmail?: string;
    /**
     * Group type (e.g., committee, study, interestgroup)
     */
    type: string;
    /**
     * Information about group fines policy
     */
    finesInfo?: string;
    /**
     * Whether fines are activated for this group
     */
    finesActivated?: boolean;
    /**
     * User ID of the fines administrator
     */
    finesAdminId?: string;
  };
  path?: never;
  query?: never;
  url: '/api/groups';
};

export type PostApiGroupsErrors = {
  /**
   * Bad Request - Invalid input or slug already exists
   */
  400: unknown;
  /**
   * Forbidden - Missing groups:create permission
   */
  403: unknown;
};

export type PostApiGroupsResponses = {
  /**
   * Group created successfully
   */
  201: unknown;
};

export type DeleteApiGroupsSlugData = {
  body?: never;
  path: {
    slug: string;
  };
  query?: never;
  url: '/api/groups/{slug}';
};

export type DeleteApiGroupsSlugErrors = {
  /**
   * Forbidden - Not a group leader or missing groups:delete permission
   */
  403: unknown;
  /**
   * Not Found - Group with the specified slug does not exist
   */
  404: unknown;
};

export type DeleteApiGroupsSlugResponses = {
  /**
   * Group successfully deleted
   */
  204: void;
};

export type DeleteApiGroupsSlugResponse = DeleteApiGroupsSlugResponses[keyof DeleteApiGroupsSlugResponses];

export type GetApiGroupsSlugData = {
  body?: never;
  path: {
    slug: string;
  };
  query?: never;
  url: '/api/groups/{slug}';
};

export type GetApiGroupsSlugErrors = {
  /**
   * Not Found - Group with the specified slug does not exist
   */
  404: unknown;
};

export type GetApiGroupsSlugResponses = {
  /**
   * Group details retrieved successfully
   */
  200: {
    /**
     * Group slug
     */
    slug: string;
    /**
     * Group image URL
     */
    imageUrl: string | null;
    /**
     * Group name
     */
    name: string;
    /**
     * Group description
     */
    description: string | null;
    /**
     * Group contact email
     */
    contactEmail: string | null;
    /**
     * Group type
     */
    type: string;
    /**
     * Group fines info
     */
    finesInfo: string;
    /**
     * Group fines activated
     */
    finesActivated: boolean;
    /**
     * Group fines admin ID
     */
    finesAdminId: string | null;
    /**
     * Creation timestamp
     */
    createdAt: string;
    /**
     * Last update timestamp
     */
    updatedAt: string;
  };
};

export type GetApiGroupsSlugResponse = GetApiGroupsSlugResponses[keyof GetApiGroupsSlugResponses];

export type PatchApiGroupsSlugData = {
  body?: {
    /**
     * Group image URL
     */
    imageUrl?: string;
    /**
     * Group name
     */
    name?: string;
    /**
     * Group description
     */
    description?: string | null;
    /**
     * Group contact email
     */
    contactEmail?: string | null;
    /**
     * Group type
     */
    type?: string;
    /**
     * Information about group fines policy
     */
    finesInfo?: string;
    /**
     * Whether fines are activated for this group
     */
    finesActivated?: boolean;
    /**
     * User ID of the fines administrator
     */
    finesAdminId?: string | null;
  };
  path: {
    slug: string;
  };
  query?: never;
  url: '/api/groups/{slug}';
};

export type PatchApiGroupsSlugErrors = {
  /**
   * Bad Request - Invalid input
   */
  400: unknown;
  /**
   * Forbidden - Not a group leader or missing groups:update permission
   */
  403: unknown;
  /**
   * Not Found - Group with the specified slug does not exist
   */
  404: unknown;
};

export type PatchApiGroupsSlugResponses = {
  /**
   * Group updated successfully
   */
  200: unknown;
};

export type GetApiGroupsGroupSlugFinesData = {
  body?: never;
  path: {
    groupSlug: string;
  };
  query?: never;
  url: '/api/groups/{groupSlug}/fines';
};

export type GetApiGroupsGroupSlugFinesErrors = {
  /**
   * Forbidden - Not authorized to view fines for this group
   */
  403: unknown;
  /**
   * Not Found - Group not found
   */
  404: unknown;
};

export type GetApiGroupsGroupSlugFinesResponses = {
  /**
   * List of fines retrieved successfully
   */
  200: Array<{
    /**
     * Fine ID
     */
    id: string;
    /**
     * User ID who received the fine
     */
    userId: string;
    /**
     * Group slug that issued the fine
     */
    groupSlug: string;
    /**
     * Reason for the fine
     */
    reason: string;
    /**
     * Fine amount in NOK
     */
    amount: number;
    /**
     * User's defense text
     */
    defense: string | null;
    /**
     * Fine status (pending, approved, paid, rejected)
     */
    status: string;
    /**
     * User who created the fine
     */
    createdByUserId: string | null;
    /**
     * User who approved the fine
     */
    approvedByUserId: string | null;
    /**
     * Approval timestamp
     */
    approvedAt: string | null;
    /**
     * Payment timestamp
     */
    paidAt: string | null;
    /**
     * Creation timestamp
     */
    createdAt: string;
    /**
     * Last update timestamp
     */
    updatedAt: string;
  }>;
};

export type GetApiGroupsGroupSlugFinesResponse = GetApiGroupsGroupSlugFinesResponses[keyof GetApiGroupsGroupSlugFinesResponses];

export type PostApiGroupsGroupSlugFinesData = {
  body?: {
    /**
     * User ID who receives the fine
     */
    userId: string;
    /**
     * Group slug that issues the fine
     */
    groupSlug: string;
    /**
     * Reason for the fine
     */
    reason: string;
    /**
     * Fine amount in NOK
     */
    amount: number;
    /**
     * User's defense text
     */
    defense?: string;
  };
  path: {
    groupSlug: string;
  };
  query?: never;
  url: '/api/groups/{groupSlug}/fines';
};

export type PostApiGroupsGroupSlugFinesErrors = {
  /**
   * Bad Request - Invalid input or fines not activated for group
   */
  400: unknown;
  /**
   * Forbidden - Not authorized to create fines for this group
   */
  403: unknown;
  /**
   * Not Found - Group or user not found
   */
  404: unknown;
};

export type PostApiGroupsGroupSlugFinesResponses = {
  /**
   * Fine created successfully
   */
  201: unknown;
};

export type DeleteApiGroupsGroupSlugFinesFineIdData = {
  body?: never;
  path: {
    groupSlug: string;
    fineId: string;
  };
  query?: never;
  url: '/api/groups/{groupSlug}/fines/{fineId}';
};

export type DeleteApiGroupsGroupSlugFinesFineIdErrors = {
  /**
   * Forbidden - Not authorized to delete this fine
   */
  403: unknown;
  /**
   * Not Found - Fine or group not found
   */
  404: unknown;
};

export type DeleteApiGroupsGroupSlugFinesFineIdResponses = {
  /**
   * Fine successfully deleted
   */
  204: void;
};

export type DeleteApiGroupsGroupSlugFinesFineIdResponse = DeleteApiGroupsGroupSlugFinesFineIdResponses[keyof DeleteApiGroupsGroupSlugFinesFineIdResponses];

export type GetApiGroupsGroupSlugFinesFineIdData = {
  body?: never;
  path: {
    groupSlug: string;
    fineId: string;
  };
  query?: never;
  url: '/api/groups/{groupSlug}/fines/{fineId}';
};

export type GetApiGroupsGroupSlugFinesFineIdErrors = {
  /**
   * Forbidden - Not authorized to view this fine
   */
  403: unknown;
  /**
   * Not Found - Fine or group not found
   */
  404: unknown;
};

export type GetApiGroupsGroupSlugFinesFineIdResponses = {
  /**
   * Fine details retrieved successfully
   */
  200: {
    /**
     * Fine ID
     */
    id: string;
    /**
     * User ID who received the fine
     */
    userId: string;
    /**
     * Group slug that issued the fine
     */
    groupSlug: string;
    /**
     * Reason for the fine
     */
    reason: string;
    /**
     * Fine amount in NOK
     */
    amount: number;
    /**
     * User's defense text
     */
    defense: string | null;
    /**
     * Fine status (pending, approved, paid, rejected)
     */
    status: string;
    /**
     * User who created the fine
     */
    createdByUserId: string | null;
    /**
     * User who approved the fine
     */
    approvedByUserId: string | null;
    /**
     * Approval timestamp
     */
    approvedAt: string | null;
    /**
     * Payment timestamp
     */
    paidAt: string | null;
    /**
     * Creation timestamp
     */
    createdAt: string;
    /**
     * Last update timestamp
     */
    updatedAt: string;
  };
};

export type GetApiGroupsGroupSlugFinesFineIdResponse = GetApiGroupsGroupSlugFinesFineIdResponses[keyof GetApiGroupsGroupSlugFinesFineIdResponses];

export type PatchApiGroupsGroupSlugFinesFineIdData = {
  body?: {
    /**
     * User's defense text
     */
    defense?: string;
    /**
     * Fine status
     */
    status?: 'pending' | 'approved' | 'paid' | 'rejected';
    /**
     * User who approved the fine
     */
    approvedByUserId?: string;
  };
  path: {
    groupSlug: string;
    fineId: string;
  };
  query?: never;
  url: '/api/groups/{groupSlug}/fines/{fineId}';
};

export type PatchApiGroupsGroupSlugFinesFineIdErrors = {
  /**
   * Bad Request - Invalid status transition
   */
  400: unknown;
  /**
   * Forbidden - Not authorized to update this fine
   */
  403: unknown;
  /**
   * Not Found - Fine or group not found
   */
  404: unknown;
};

export type PatchApiGroupsGroupSlugFinesFineIdResponses = {
  /**
   * Fine updated successfully
   */
  200: unknown;
};

export type GetApiGroupsGroupSlugMembersData = {
  body?: never;
  path: {
    groupSlug: string;
  };
  query?: never;
  url: '/api/groups/{groupSlug}/members';
};

export type GetApiGroupsGroupSlugMembersErrors = {
  /**
   * Not Found - Group not found
   */
  404: unknown;
};

export type GetApiGroupsGroupSlugMembersResponses = {
  /**
   * List of members retrieved successfully
   */
  200: Array<{
    /**
     * User ID
     */
    userId: string;
    /**
     * Group slug
     */
    groupSlug: string;
    /**
     * Membership role
     */
    role: string;
    /**
     * Membership creation timestamp
     */
    createdAt: string;
    /**
     * Membership update timestamp
     */
    updatedAt: string;
  }>;
};

export type GetApiGroupsGroupSlugMembersResponse = GetApiGroupsGroupSlugMembersResponses[keyof GetApiGroupsGroupSlugMembersResponses];

export type PostApiGroupsGroupSlugMembersData = {
  body?: {
    /**
     * User ID to add as member
     */
    userId: string;
    /**
     * Membership role
     */
    role?: 'member' | 'leader';
  };
  path: {
    groupSlug: string;
  };
  query?: never;
  url: '/api/groups/{groupSlug}/members';
};

export type PostApiGroupsGroupSlugMembersErrors = {
  /**
   * Bad Request - User already a member or user not found
   */
  400: unknown;
  /**
   * Forbidden - Missing groups:manage permission
   */
  403: unknown;
  /**
   * Not Found - Group not found
   */
  404: unknown;
};

export type PostApiGroupsGroupSlugMembersResponses = {
  /**
   * Member added successfully
   */
  201: unknown;
};

export type DeleteApiGroupsGroupSlugMembersUserIdData = {
  body?: never;
  path: {
    groupSlug: string;
    userId: string;
  };
  query?: never;
  url: '/api/groups/{groupSlug}/members/{userId}';
};

export type DeleteApiGroupsGroupSlugMembersUserIdErrors = {
  /**
   * Forbidden - Missing groups:manage permission
   */
  403: unknown;
  /**
   * Not Found - Group, user, or membership not found
   */
  404: unknown;
};

export type DeleteApiGroupsGroupSlugMembersUserIdResponses = {
  /**
   * Member removed successfully
   */
  204: void;
};

export type DeleteApiGroupsGroupSlugMembersUserIdResponse =
  DeleteApiGroupsGroupSlugMembersUserIdResponses[keyof DeleteApiGroupsGroupSlugMembersUserIdResponses];

export type PatchApiGroupsGroupSlugMembersUserIdData = {
  body?: {
    /**
     * Membership role
     */
    role: 'member' | 'leader';
  };
  path: {
    groupSlug: string;
    userId: string;
  };
  query?: never;
  url: '/api/groups/{groupSlug}/members/{userId}';
};

export type PatchApiGroupsGroupSlugMembersUserIdErrors = {
  /**
   * Forbidden - Missing groups:manage permission
   */
  403: unknown;
  /**
   * Not Found - Group, user, or membership not found
   */
  404: unknown;
};

export type PatchApiGroupsGroupSlugMembersUserIdResponses = {
  /**
   * Member role updated successfully
   */
  200: unknown;
};

export type GetApiGroupsSlugFormsData = {
  body?: never;
  path: {
    slug: string;
  };
  query?: never;
  url: '/api/groups/{slug}/forms';
};

export type GetApiGroupsSlugFormsErrors = {
  /**
   * Group not found
   */
  404: unknown;
};

export type GetApiGroupsSlugFormsResponses = {
  /**
   * Success
   */
  200: Array<{
    id: string;
    title: string;
    description: string | null;
    group: string;
    email_receiver_on_submit: string | null;
    can_submit_multiple: boolean;
    is_open_for_submissions: boolean;
    only_for_group_members: boolean;
    resource_type: string;
    viewer_has_answered: boolean;
    created_at: string;
    updated_at: string;
  }>;
};

export type GetApiGroupsSlugFormsResponse = GetApiGroupsSlugFormsResponses[keyof GetApiGroupsSlugFormsResponses];

export type PostApiGroupsSlugFormsData = {
  body?: {
    title: string;
    description?: string;
    template?: boolean;
    fields?: Array<{
      title: string;
      type: 'text_answer' | 'multiple_select' | 'single_select';
      required?: boolean;
      order?: number;
      options?: Array<{
        title: string;
        order?: number;
      }>;
    }>;
    group: string;
    email_receiver_on_submit?: string;
    can_submit_multiple?: boolean;
    is_open_for_submissions?: boolean;
    only_for_group_members?: boolean;
  };
  path: {
    slug: string;
  };
  query?: never;
  url: '/api/groups/{slug}/forms';
};

export type PostApiGroupsSlugFormsErrors = {
  /**
   * Forbidden
   */
  403: unknown;
  /**
   * Group not found
   */
  404: unknown;
};

export type PostApiGroupsSlugFormsResponses = {
  /**
   * Created
   */
  201: unknown;
};

export type GetApiNewsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/news';
};

export type GetApiNewsResponses = {
  /**
   * List of news articles
   */
  200: unknown;
};

export type PostApiNewsData = {
  body?: {
    /**
     * News article title
     */
    title: string;
    /**
     * News article subtitle/ingress
     */
    header: string;
    /**
     * Main content of the news
     */
    body: string;
    /**
     * Optional image URL
     */
    imageUrl?: string;
    /**
     * Alt text for the image
     */
    imageAlt?: string;
    /**
     * Whether reactions are enabled
     */
    emojisAllowed?: boolean;
  };
  path?: never;
  query?: never;
  url: '/api/news';
};

export type PostApiNewsErrors = {
  /**
   * Forbidden - Missing news:create permission
   */
  403: unknown;
};

export type PostApiNewsResponses = {
  /**
   * News article created successfully
   */
  201: unknown;
};

export type DeleteApiNewsIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/api/news/{id}';
};

export type DeleteApiNewsIdErrors = {
  /**
   * Forbidden - Insufficient permissions
   */
  403: unknown;
  /**
   * News article not found
   */
  404: unknown;
};

export type DeleteApiNewsIdResponses = {
  /**
   * News article deleted successfully
   */
  200: unknown;
};

export type GetApiNewsIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/api/news/{id}';
};

export type GetApiNewsIdErrors = {
  /**
   * News article not found
   */
  404: unknown;
};

export type GetApiNewsIdResponses = {
  /**
   * News article details
   */
  200: unknown;
};

export type PatchApiNewsIdData = {
  body?: {
    title?: string;
    header?: string;
    body?: string;
    imageUrl?: string | null;
    imageAlt?: string | null;
    emojisAllowed?: boolean;
  };
  path: {
    id: string;
  };
  query?: never;
  url: '/api/news/{id}';
};

export type PatchApiNewsIdErrors = {
  /**
   * Forbidden - Insufficient permissions
   */
  403: unknown;
  /**
   * News article not found
   */
  404: unknown;
};

export type PatchApiNewsIdResponses = {
  /**
   * News article updated successfully
   */
  200: unknown;
};

export type DeleteApiNewsIdReactionsData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/api/news/{id}/reactions';
};

export type DeleteApiNewsIdReactionsErrors = {
  /**
   * News article or reaction not found
   */
  404: unknown;
};

export type DeleteApiNewsIdReactionsResponses = {
  /**
   * Reaction removed successfully
   */
  200: unknown;
};

export type PostApiNewsIdReactionsData = {
  body?: {
    /**
     * Emoji reaction (e.g., 👍, ❤️, 😂)
     */
    emoji: string;
  };
  path: {
    id: string;
  };
  query?: never;
  url: '/api/news/{id}/reactions';
};

export type PostApiNewsIdReactionsErrors = {
  /**
   * Forbidden - Reactions not allowed on this news article
   */
  403: unknown;
  /**
   * News article not found
   */
  404: unknown;
};

export type PostApiNewsIdReactionsResponses = {
  /**
   * Reaction added successfully
   */
  201: unknown;
};

export type GetApiJobsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/jobs';
};

export type GetApiJobsResponses = {
  /**
   * List of job postings
   */
  200: unknown;
};

export type PostApiJobsData = {
  body?: {
    /**
     * Job posting title
     */
    title: string;
    /**
     * Short description/summary
     */
    ingress?: string;
    /**
     * Full job description
     */
    body?: string;
    /**
     * Company name
     */
    company: string;
    /**
     * Job location
     */
    location: string;
    /**
     * Application deadline
     */
    deadline?: string;
    /**
     * Whether hiring is ongoing
     */
    isContinuouslyHiring?: boolean;
    /**
     * Type of employment
     */
    jobType?: 'full_time' | 'part_time' | 'summer_job' | 'other';
    /**
     * Contact email
     */
    email?: string;
    /**
     * Application or company URL
     */
    link?: string;
    /**
     * Target class start
     */
    classStart?: 'first' | 'second' | 'third' | 'fourth' | 'fifth' | 'alumni';
    /**
     * Target class end
     */
    classEnd?: 'first' | 'second' | 'third' | 'fourth' | 'fifth' | 'alumni';
    /**
     * Company logo
     */
    imageUrl?: string;
    /**
     * Logo alt text
     */
    imageAlt?: string;
  };
  path?: never;
  query?: never;
  url: '/api/jobs';
};

export type PostApiJobsErrors = {
  /**
   * Bad Request - Invalid input
   */
  400: unknown;
  /**
   * Forbidden - Missing jobs:create permission
   */
  403: unknown;
};

export type PostApiJobsResponses = {
  /**
   * Job posting created successfully
   */
  201: unknown;
};

export type DeleteApiJobsIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/api/jobs/{id}';
};

export type DeleteApiJobsIdErrors = {
  /**
   * Forbidden - Insufficient permissions
   */
  403: unknown;
  /**
   * Job posting not found
   */
  404: unknown;
};

export type DeleteApiJobsIdResponses = {
  /**
   * Job posting deleted successfully
   */
  200: unknown;
};

export type GetApiJobsIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/api/jobs/{id}';
};

export type GetApiJobsIdErrors = {
  /**
   * Job posting not found
   */
  404: unknown;
};

export type GetApiJobsIdResponses = {
  /**
   * Job posting details
   */
  200: unknown;
};

export type PatchApiJobsIdData = {
  body?: {
    title?: string;
    ingress?: string;
    body?: string;
    company?: string;
    location?: string;
    deadline?: string | null;
    isContinuouslyHiring?: boolean;
    jobType?: 'full_time' | 'part_time' | 'summer_job' | 'other';
    email?: string | null;
    link?: string | null;
    classStart?: 'first' | 'second' | 'third' | 'fourth' | 'fifth' | 'alumni';
    classEnd?: 'first' | 'second' | 'third' | 'fourth' | 'fifth' | 'alumni';
    imageUrl?: string | null;
    imageAlt?: string | null;
  };
  path: {
    id: string;
  };
  query?: never;
  url: '/api/jobs/{id}';
};

export type PatchApiJobsIdErrors = {
  /**
   * Forbidden - Insufficient permissions
   */
  403: unknown;
  /**
   * Job posting not found
   */
  404: unknown;
};

export type PatchApiJobsIdResponses = {
  /**
   * Job posting updated successfully
   */
  200: unknown;
};

export type GetApiUserMeSettingsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/user/me/settings';
};

export type GetApiUserMeSettingsErrors = {
  /**
   * Not Found - User settings do not exist (user needs to complete onboarding)
   */
  404: unknown;
};

export type GetApiUserMeSettingsResponses = {
  /**
   * User settings retrieved successfully
   */
  200: {
    gender: 'male' | 'female' | 'other';
    allowsPhotosByDefault: boolean;
    acceptsEventRules: boolean;
    imageUrl?: string;
    bioDescription?: string;
    githubUrl?: string;
    linkedinUrl?: string;
    receiveMailCommunication: boolean;
    allergies?: Array<string>;
    /**
     * Whether the user has completed onboarding
     */
    isOnboarded: boolean;
  };
};

export type GetApiUserMeSettingsResponse = GetApiUserMeSettingsResponses[keyof GetApiUserMeSettingsResponses];

export type PatchApiUserMeSettingsData = {
  body?: {
    gender?: 'male' | 'female' | 'other';
    allowsPhotosByDefault?: boolean;
    acceptsEventRules?: boolean;
    imageUrl?: string;
    bioDescription?: string;
    githubUrl?: string;
    linkedinUrl?: string;
    receiveMailCommunication?: boolean;
    allergies?: Array<string>;
  };
  path?: never;
  query?: never;
  url: '/api/user/me/settings';
};

export type PatchApiUserMeSettingsErrors = {
  /**
   * Bad Request - Invalid input
   */
  400: unknown;
  /**
   * Not Found - User settings do not exist (user needs to complete onboarding first)
   */
  404: unknown;
};

export type PatchApiUserMeSettingsResponses = {
  /**
   * Settings updated successfully
   */
  200: {
    gender?: 'male' | 'female' | 'other';
    allowsPhotosByDefault?: boolean;
    acceptsEventRules?: boolean;
    imageUrl?: string;
    bioDescription?: string;
    githubUrl?: string;
    linkedinUrl?: string;
    receiveMailCommunication?: boolean;
    allergies?: Array<string>;
  };
};

export type PatchApiUserMeSettingsResponse = PatchApiUserMeSettingsResponses[keyof PatchApiUserMeSettingsResponses];

export type PostApiUserMeSettingsData = {
  body?: {
    gender: 'male' | 'female' | 'other';
    allowsPhotosByDefault: boolean;
    acceptsEventRules: boolean;
    imageUrl?: string;
    bioDescription?: string;
    githubUrl?: string;
    linkedinUrl?: string;
    receiveMailCommunication: boolean;
    allergies?: Array<string>;
  };
  path?: never;
  query?: never;
  url: '/api/user/me/settings';
};

export type PostApiUserMeSettingsErrors = {
  /**
   * Bad Request - User has already completed onboarding
   */
  400: unknown;
};

export type PostApiUserMeSettingsResponses = {
  /**
   * User onboarded successfully
   */
  201: {
    gender: 'male' | 'female' | 'other';
    allowsPhotosByDefault: boolean;
    acceptsEventRules: boolean;
    imageUrl?: string;
    bioDescription?: string;
    githubUrl?: string;
    linkedinUrl?: string;
    receiveMailCommunication: boolean;
    allergies?: Array<string>;
  };
};

export type PostApiUserMeSettingsResponse = PostApiUserMeSettingsResponses[keyof PostApiUserMeSettingsResponses];

export type GetApiUserAllergyData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/user/allergy';
};

export type GetApiUserAllergyResponses = {
  /**
   * List of allergies retrieved successfully
   */
  200: Array<{
    /**
     * Unique identifier for the allergy
     */
    slug: string;
    /**
     * Display name of the allergy
     */
    label: string;
    /**
     * Detailed description of the allergy
     */
    description: string | null;
  }>;
};

export type GetApiUserAllergyResponse = GetApiUserAllergyResponses[keyof GetApiUserAllergyResponses];
