import { Comment } from '../types';

export const sampleComments: Comment[] = [
  {
    author: {
      first_name: 'John',
      last_name: 'Doe',
      image: 'avatar1.jpg',
      user_id: '2',
    },
    body: 'This is a great article!',
    created_at: new Date('2023-10-03T10:30:00Z'),
    updated_at: new Date('2023-10-03T10:30:00Z'),
    id: 125,
    indentation_level: 0,
    parent_id: null,
    children: [
      {
        author: {
          first_name: 'Jane',
          last_name: 'Doe',
          image: 'avatar2.jpg',
          user_id: '3',
        },
        updated_at: new Date('2023-10-03T10:35:00Z'),
        body: 'I agree with John!',
        created_at: new Date('2023-10-03T10:35:00Z'),
        id: 126,
        indentation_level: 1,
        children: [],
        parent_id: 125,
      },
      {
        author: {
          first_name: 'Sam',
          last_name: 'Smith',
          image: 'avatar3.jpg',
          user_id: '4',
        },
        updated_at: new Date('2023-10-03T10:40:00Z'),
        body: 'Thanks for sharing!',
        created_at: new Date('2023-10-03T10:40:00Z'),
        id: 127,
        indentation_level: 1,
        children: [],
        parent_id: 125,
      },
    ],
  },
  {
    author: {
      first_name: 'Lisa',
      last_name: 'Johnson',
      image: 'avatar4.jpg',
      user_id: '5',
    },
    body: 'Interesting topic!',
    created_at: new Date('2023-10-03T10:50:00Z'),
    updated_at: new Date('2023-10-03T10:50:00Z'),
    id: 128,
    indentation_level: 0,
    parent_id: null,
    children: [
      {
        author: {
          first_name: 'Alex',
          last_name: 'Brown',
          image: 'avatar5.jpg',
          user_id: '6',
        },
        updated_at: new Date('2023-10-03T10:55:00Z'),
        body: 'I have a question about this.',
        created_at: new Date('2023-10-03T10:55:00Z'),
        id: 129,
        indentation_level: 1,
        children: [
          {
            author: {
              first_name: 'Alex',
              last_name: 'Brown',
              image: 'avatar5.jpg',
              user_id: '6',
            },
            updated_at: new Date('2023-10-03T10:55:00Z'),
            body: 'Nice. Let me help you by replying to your question fjdsaklø fjadkslø fklsadøjfkldøsa jfkløads jfklødsa jfklødsa jflkøsadjfølkdsj fkløsad jfløksdaj øfkldsj fklødsjøl :).',
            created_at: new Date('2023-10-03T10:55:00Z'),
            id: 130,
            indentation_level: 1,
            children: [
              {
                author: {
                  first_name: 'Alex',
                  last_name: 'Brown',
                  image: 'avatar5.jpg',
                  user_id: '6',
                },
                updated_at: new Date('2023-10-03T10:55:00Z'),
                body: 'I have a question about this.',
                created_at: new Date('2023-10-03T10:55:00Z'),
                id: 134,
                indentation_level: 1,
                children: [],
                parent_id: 130,
              },
            ],
            parent_id: 129,
          },
        ],
        parent_id: 128,
      },
      {
        author: {
          first_name: 'Alex',
          last_name: 'Brown',
          image: 'avatar5.jpg',
          user_id: '6',
        },
        updated_at: new Date('2023-10-03T10:55:00Z'),
        body: 'I have a question about this.',
        created_at: new Date('2023-10-03T10:55:00Z'),
        id: 131,
        indentation_level: 1,
        children: [],
        parent_id: 128,
      },
    ],
  },
];
